import { useState } from 'react';
import { muscles, type Muscle } from '../../../../lib/domain';
import type { MuscleRoleAssignment } from '../../data/domain';
import './workout-planning.css';
import { useI18n } from '../../i18n';

export function MuscleRolesEditor({ value, exerciseName, readOnly, onChange }: { value: MuscleRoleAssignment[] | null; exerciseName: string; readOnly?: boolean; onChange: (value: MuscleRoleAssignment[] | null) => void }) {
  const { t } = useI18n();
  const [muscle, setMuscle] = useState<Muscle | ''>('');
  const [role, setRole] = useState<MuscleRoleAssignment['role'] | ''>('');
  const assigned = value ?? [];
  return <details className="muscle-roles-editor"><summary>{assigned.length ? t('training.roles', { count: assigned.length }) : t('training.rolesUnset')}</summary><p className="field-hint">{t('training.rolesHint')}</p><fieldset disabled={readOnly} className="muscle-roles-fields"><legend className="sr-only">{t('training.rolesLegend', { exercise: exerciseName })}</legend>{assigned.map(assignment => <div className="muscle-role-row" key={assignment.muscle}><span>{t(`muscle.${assignment.muscle}`)}</span><select aria-label={t('training.roleFor', { muscle: t(`muscle.${assignment.muscle}`), exercise: exerciseName })} value={assignment.role} onChange={event => onChange(assigned.map(current => current.muscle === assignment.muscle ? { ...current, role: event.target.value as MuscleRoleAssignment['role'] } : current))}><option value="direct">{t('training.direct')}</option><option value="indirect">{t('training.indirect')}</option></select><button type="button" className="text-button" aria-label={t('training.removeRoleFor', { muscle: t(`muscle.${assignment.muscle}`), exercise: exerciseName })} onClick={() => { const next = assigned.filter(current => current.muscle !== assignment.muscle); onChange(next.length ? next : null); }}>{t('training.removeRole')}</button></div>)}{!readOnly && <><div className="muscle-role-add"><label className="field">{t('training.muscle')}<select value={muscle} aria-label={t('training.addMuscleFor', { exercise: exerciseName })} onChange={event => setMuscle(event.target.value as Muscle | '')}><option value="">{t('training.chooseMuscle')}</option>{(Object.entries(muscles) as [Muscle, string][]).filter(([id]) => !assigned.some(current => current.muscle === id)).map(([id]) => <option key={id} value={id}>{t(`muscle.${id}`)}</option>)}</select></label><label className="field">{t('training.role')}<select value={role} aria-label={t('training.addRoleFor', { exercise: exerciseName })} onChange={event => setRole(event.target.value as MuscleRoleAssignment['role'] | '')}><option value="">{t('training.chooseRole')}</option><option value="direct">{t('training.direct')}</option><option value="indirect">{t('training.indirect')}</option></select></label></div><button type="button" className="we-secondary" disabled={!muscle || !role || assigned.some(current => current.muscle === muscle)} onClick={() => { if (!muscle || !role || assigned.some(current => current.muscle === muscle)) return; onChange([...assigned, { muscle, role }]); setMuscle(''); setRole(''); }}>{t('training.addRole')}</button>{assigned.length > 0 && <button type="button" className="text-button" onClick={() => onChange(null)}>{t('training.leaveUnset')}</button>}</>}</fieldset></details>;
}
