import { useState } from 'react';
import type { LocalSnapshot, Muscle, MuscleTarget, Workout } from '../../data/domain';
import type { LocalRepository } from '../../data/repository';
import { addDays, monday, muscleTargetForWeek, muscleWorkSummary } from '../../data/analytics';
import { dateLabel } from '../../ui/common';
import { AnatomyFigure } from './AnatomyFigure';
import { amount, geometryMuscles, targetPresentation } from './presentation';
import { useI18n } from '../../i18n';
import { MuscleTargetEditor } from './MuscleTargetEditor';
import { PlanningDialog } from '../planning/PlanningDialog';
import './anatomy.css';
export function WeeklyMuscleMap({ snapshot, repository, week, onChanged, onOpenWorkout }: { snapshot: LocalSnapshot; repository: LocalRepository; week: string; onChanged: () => Promise<void>; onOpenWorkout?: (workout: Workout) => void }) {
  const { t } = useI18n();
  const [mode, setMode] = useState<'planned' | 'actual'>('planned');
  const [detail, setDetail] = useState<Muscle | null>(null), [editing, setEditing] = useState<Muscle | null>(null), [help, setHelp] = useState(false);
  const start = monday(week), end = addDays(start, 6);
  const summary = muscleWorkSummary(snapshot.workouts, start, end, mode);
  const targets = new Map<Muscle, MuscleTarget | null>(summary.muscles.map(row => [row.muscle, muscleTargetForWeek(snapshot.muscleTargets, row.muscle, start)]));
  const rows = summary.muscles.map(row => { const target = targets.get(row.muscle) ?? null, value = target?.unit === 'exposures' ? row.exposures : row.effectiveSets; return { ...row, target, value, presentation: targetPresentation(value, target, summary.hasData) }; });
  const colors = Object.fromEntries(Object.entries(geometryMuscles).map(([id, muscle]) => [id, rows.find(row => row.muscle === muscle)?.presentation.color ?? '#AEB6A8']));
  const selected = rows.find(row => row.muscle === detail);
  return <section className="muscle-map stack" aria-label={t('muscleMap.label')}><div className="planning-section-heading"><div><h2>{t('muscleMap.title')}</h2><p>{t('muscleMap.subtitle')}</p></div><button className="secondary planning-help" aria-label={t('muscleMap.explain')} onClick={() => setHelp(true)}>?</button></div><p className="field-hint">{t('muscleMap.rangeHint', { start: dateLabel(start), end: dateLabel(end) })}</p><div className="muscle-mode-switch" role="group" aria-label={t('muscleMap.data')}><button className="secondary" aria-pressed={mode === 'planned'} onClick={() => setMode('planned')}>{t('muscleMap.plan')}</button><button className="secondary" aria-pressed={mode === 'actual'} onClick={() => setMode('actual')}>{t('muscleMap.actual')}</button></div><AnatomyFigure colors={colors} onSelect={setDetail}/>
    {!summary.complete && <p role="status">{t(summary.hasData ? 'muscleMap.incomplete' : 'muscleMap.noDataStatus', { roles: summary.unknownRolesCount, sets: summary.unknownSetsCount, actual: summary.missingActualCount })}</p>}
    {onOpenWorkout && summary.incompleteWorkoutIds.length > 0 && <details><summary>{t('muscleMap.completeSessions', { count: summary.incompleteWorkoutIds.length })}</summary><ul className="planning-section-list detail-content">{snapshot.workouts.filter(workout => summary.incompleteWorkoutIds.includes(workout.id)).map(workout => <li key={workout.id}><button className="secondary" onClick={() => onOpenWorkout(workout)}>{t('muscleMap.sessionRow', { title: workout.title, date: dateLabel(workout.date) })}</button></li>)}</ul></details>}
    <details><summary>{t('muscleMap.values')}</summary><ul className="muscle-list detail-content">{rows.map(row => <li key={row.muscle}><button className="muscle-list-button" onClick={() => setDetail(row.muscle)}><span className={`muscle-color ${row.complete ? '' : 'incomplete'}`} style={{ backgroundColor: row.presentation.color }} aria-hidden="true"/><span className="muscle-list-copy"><strong>{t(`muscle.${row.muscle}`)}</strong><span>{row.effectiveSets === null && summary.hasData ? t('muscleMap.rowKnown', { sets: amount(row.knownEffectiveSets), exposures: amount(row.exposures) }) : t('muscleMap.rowEffective', { sets: amount(row.effectiveSets), exposures: amount(row.exposures) })}</span></span><span className="muscle-list-goal"><span>{t(row.presentation.text)}</span>{row.target?.target != null && <span>{t(`muscleMap.goal_${row.target.unit}`, { value: amount(row.target.target) })}</span>}{row.presentation.percent !== null && <strong>{row.presentation.percent}%{row.presentation.percent > 100 ? ' ↑' : ''}</strong>}</span></button><button className="text-button muscle-edit-goal" onClick={() => setEditing(row.muscle)} aria-label={t('muscleMap.setGoalFor', { muscle: t(`muscle.${row.muscle}`) })}>{t('muscleMap.setGoal')}</button></li>)}</ul></details>
    {selected && <PlanningDialog title={t(`muscle.${selected.muscle}`)} onClose={() => setDetail(null)}><p>{t('muscleMap.detailRange', { mode: t(mode === 'planned' ? 'muscleMap.plan' : 'muscleMap.actual'), start: dateLabel(start), end: dateLabel(end) })}</p><dl className="muscle-detail-metrics"><div><dt>{t('muscleMap.directSets')}</dt><dd>{amount(selected.directSets)}</dd></div><div><dt>{t('muscleMap.indirectSets')}</dt><dd>{amount(selected.indirectSets)}</dd></div><div><dt>{t('muscleMap.effectiveSets')}</dt><dd>{selected.effectiveSets === null && summary.hasData ? t('muscleMap.knownPart', { value: amount(selected.effectiveSets), known: amount(selected.knownEffectiveSets) }) : amount(selected.effectiveSets)}</dd></div><div><dt>{t('muscleMap.exposures')}</dt><dd>{amount(selected.exposures)}</dd></div></dl><p>{selected.presentation.percent !== null ? t('muscleMap.statusPercent', { status: t(selected.presentation.text), percent: selected.presentation.percent }) : t(selected.presentation.text)}</p>{selected.target ? <p>{selected.target.target === null ? t('muscleMap.goalNotSet') : t(`muscleMap.goal_${selected.target.unit}`, { value: amount(selected.target.target) })} · {t(selected.target.scope === 'week-override' ? 'muscleMap.scope_override' : 'muscleMap.scope_period')}<br/>{t('muscleMap.targetValidity', { start: dateLabel(selected.target.start), end: dateLabel(selected.target.end), revision: selected.target.definitionRevision })}<br/>{t('muscleMap.provenance', { provenance: selected.target.provenance })}</p> : <p>{t('muscleMap.noTarget')}</p>}<p className="field-hint">{t('muscleMap.groupHint')}</p><button className="secondary" onClick={() => { setDetail(null); setEditing(selected.muscle); }}>{t('muscleMap.setGoalFor', { muscle: t(`muscle.${selected.muscle}`) })}</button></PlanningDialog>}
    {editing && <MuscleTargetEditor key={`${editing}:${start}:${snapshot.epoch}`} snapshot={snapshot} repository={repository} week={start} muscle={editing} target={targets.get(editing) ?? null} onClose={() => setEditing(null)} onSaved={async () => { await onChanged(); setEditing(null); }}/>} 
    {help && <PlanningDialog title={t('muscleMap.helpTitle')} onClose={() => setHelp(false)}><p>{t('muscleMap.help1')}</p><p>{t('muscleMap.help2')}</p><p>{t('muscleMap.help3')}</p><p>{t('muscleMap.help4')}</p><p>{t('muscleMap.help5')}</p><p>{t('muscleMap.help6')}</p><p>{t('muscleMap.sourceBefore')} <a href="https://doi.org/10.1007/s40279-025-02344-w" target="_blank" rel="noreferrer">{t('muscleMap.sourceLink')}</a>. {t('muscleMap.sourceAfter')}</p></PlanningDialog>}
  </section>;
}

