import { useState, type FormEvent } from 'react';
import type { EventInput, LocalEvent, LocalSnapshot } from '../../data/domain';
import type { LocalRepository } from '../../data/repository';
import { Feedback, useAction } from '../../ui/common';
import { PlanningDialog } from './PlanningDialog';
import { currentTranslator, useI18n } from '../../i18n';
export function EventEditor({ repository, snapshot, event, day, onClose, onSaved }: { repository: LocalRepository; snapshot: LocalSnapshot; event: LocalEvent | null; day: string; onClose: () => void; onSaved: () => Promise<void> }) {
  const [epoch] = useState(snapshot.epoch), [revision] = useState(event?.revision);
  const [deleting, setDeleting] = useState(false), [committed, setCommitted] = useState(false);
  const { t } = useI18n();
  const action = useAction();
  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const form = new FormData(e.currentTarget);
    const input: EventInput = { profileId: snapshot.profile!.id, kind: String(form.get('kind')) as EventInput['kind'], title: String(form.get('title')), start: String(form.get('start')), end: String(form.get('end')), time: String(form.get('time')) || null, location: String(form.get('location')), notes: String(form.get('notes')), availability: (String(form.get('availability')) || null) as EventInput['availability'] };
    await action.run(async () => { if (event) await repository.updateEvent(event.id, revision!, input, epoch); else await repository.createEvent(input, epoch); setCommitted(true); action.setNotice(currentTranslator().t('planning.savedOnDevice')); await onSaved(); });
  }
  return <section className="stack"><button className="back" disabled={action.busy} onClick={onClose}>{t('planning.backToPlan')}</button><h1>{t(event ? 'planning.editEvent' : 'planning.newEvent')}</h1><Feedback {...action}/><form className="form-layout" onSubmit={submit}><fieldset className="card stack" disabled={action.busy || committed}><legend className="sr-only">{t('planning.eventData')}</legend><label className="field">{t('planning.eventKind')}<select name="kind" defaultValue={event?.kind ?? 'event'}><option value="event">{t('eventKind.event')}</option><option value="competition">{t('eventKind.competition')}</option><option value="trip">{t('eventKind.trip')}</option></select></label><label className="field">{t('planning.eventTitle')}<input name="title" required maxLength={160} defaultValue={event?.title ?? ''}/></label><div className="form-row"><label className="field">{t('planning.eventStart')}<input name="start" type="date" required defaultValue={event?.start ?? day}/></label><label className="field">{t('planning.eventEnd')}<input name="end" type="date" required defaultValue={event?.end ?? day}/></label></div><label className="field">{t('planning.timeOptional')}<input name="time" type="time" defaultValue={event?.time ?? ''}/></label><label className="field">{t('planning.location')}<input name="location" maxLength={300} defaultValue={event?.location ?? ''}/></label><label className="field">{t('planning.availability')}<select name="availability" defaultValue={event?.availability ?? ''}><option value="">{t('planning.availabilityUnset')}</option><option value="available">{t('planning.availability_available')}</option><option value="limited">{t('planning.availability_limited')}</option><option value="unavailable">{t('planning.availability_unavailable')}</option></select></label><label className="field">{t('planning.notes')}<textarea name="notes" maxLength={10000} defaultValue={event?.notes ?? ''}/></label></fieldset><button className="primary" disabled={action.busy || committed}>{t('planning.saveEvent')}</button></form>{event && <button className="text-button danger" disabled={committed || action.busy} onClick={() => setDeleting(true)}>{t('planning.deleteEvent')}</button>}{deleting && event && <PlanningDialog title={t('planning.deleteEventTitle')} onClose={() => setDeleting(false)}><p>{t('planning.deleteEventText', { title: event.title })}</p><button className="secondary danger" disabled={action.busy || committed} onClick={() => action.run(async () => { await repository.deleteEvent(event.id, revision!, epoch); setCommitted(true); action.setNotice(currentTranslator().t('planning.savedOnDevice')); await onSaved(); })}>{t('planning.confirmDeleteEvent')}</button></PlanningDialog>}</section>;
}

