/** French and Spanish names and descriptions of the built-in period presets (Polish and English come from lib/period-presets). */
export const presetTexts: Record<string, { fr: { name: string; description: string }; es: { name: string; description: string } }> = {
  'general-preparation': { fr: { name: 'Préparation générale', description: 'Développer la condition physique générale avant un travail plus spécifique au sport.' }, es: { name: 'Preparación general', description: 'Desarrollar la forma física general antes de un trabajo más específico del deporte.' } },
  'movement-foundations': { fr: { name: 'Technique et bases du mouvement', description: 'Apprendre ou affiner les schémas moteurs utilisés en musculation.' }, es: { name: 'Técnica y bases del movimiento', description: 'Aprender o perfeccionar los patrones de movimiento del entrenamiento de fuerza.' } },
  hypertrophy: { fr: { name: 'Développement de la masse musculaire', description: 'Priorité facultative à la prise de masse musculaire lorsqu’elle sert les objectifs de l’athlète.' }, es: { name: 'Desarrollo de la masa muscular', description: 'Prioridad opcional de ganar masa muscular cuando sirve a los objetivos del deportista.' } },
  'maximal-strength': { fr: { name: 'Développement de la force', description: 'Priorité à la capacité de produire une force élevée.' }, es: { name: 'Desarrollo de la fuerza', description: 'Prioridad de la capacidad de producir mucha fuerza.' } },
  power: { fr: { name: 'Développement de la puissance', description: 'Priorité à l’exécution rapide du travail en produisant de la force.' }, es: { name: 'Desarrollo de la potencia', description: 'Prioridad de realizar el trabajo con rapidez produciendo fuerza.' } },
  acceleration: { fr: { name: 'Accélération', description: 'Priorité aux premiers appuis et à l’augmentation de la vitesse de course.' }, es: { name: 'Aceleración', description: 'Prioridad de los primeros pasos y del aumento de la velocidad de carrera.' } },
  'maximum-speed': { fr: { name: 'Vitesse maximale', description: 'Priorité à la qualité de la course après la phase de mise en vitesse.' }, es: { name: 'Velocidad máxima', description: 'Prioridad de la calidad de la carrera tras la fase de lanzamiento.' } },
  'change-of-direction': { fr: { name: 'Freinage et changement de direction', description: 'Priorité au contrôle de la vitesse et à l’exécution d’un changement de direction planifié.' }, es: { name: 'Frenada y cambio de dirección', description: 'Prioridad de controlar la velocidad y ejecutar un cambio de dirección planificado.' } },
  'reactive-agility': { fr: { name: 'Agilité réactive', description: 'Priorité à l’adaptation du mouvement à un signal et à la situation de jeu.' }, es: { name: 'Agilidad reactiva', description: 'Prioridad de adaptar el movimiento a una señal y a la situación de juego.' } },
  'aerobic-base': { fr: { name: 'Base aérobie', description: 'Priorité à la capacité aérobie dans le cadre de la préparation physique.' }, es: { name: 'Base aeróbica', description: 'Prioridad de la capacidad aeróbica como parte de la preparación física.' } },
  'repeated-efforts': { fr: { name: 'Efforts intenses répétés', description: 'Priorité à la répétition d’actions rapides avec une récupération limitée.' }, es: { name: 'Esfuerzos intensos repetidos', description: 'Prioridad de repetir acciones rápidas con una recuperación limitada.' } },
  'throwing-skills': { fr: { name: 'Technique de lancer', description: 'Priorité à la passe du disque dans les conditions rencontrées en jeu.' }, es: { name: 'Técnica de lanzamiento', description: 'Prioridad de pasar el disco en las condiciones propias del juego.' } },
  'competition-maintenance': { fr: { name: 'Compétitions et maintien de la forme', description: 'Organiser l’entraînement autour des matchs et des tournois.' }, es: { name: 'Competiciones y mantenimiento de la forma', description: 'Organizar el entrenamiento en torno a los partidos y torneos.' } },
  taper: { fr: { name: 'Affûtage avant la compétition', description: 'Réduire la charge avant une échéance importante pour limiter la fatigue.' }, es: { name: 'Puesta a punto antes de competir', description: 'Reducir la carga antes de una competición importante para limitar la fatiga.' } },
  deload: { fr: { name: 'Décharge · deload', description: 'Période de moindre stress d’entraînement pour récupérer avant de poursuivre le travail.' }, es: { name: 'Descarga · deload', description: 'Periodo de menor estrés de entrenamiento para recuperarse antes de seguir trabajando.' } },
  'active-rest': { fr: { name: 'Repos actif · période de transition', description: 'Activité moins exigeante après la période de compétition ou entre deux cycles.' }, es: { name: 'Descanso activo · periodo de transición', description: 'Actividad menos exigente tras el periodo de competición o entre ciclos.' } },
};
/** Built-in workout templates, keyed by the template ID from lib/seed. */
export const templateNames: Record<string, { pl: string; en: string; fr: string; es: string }> = {
  'warmup-basic': { pl: 'Rozgrzewka ogólna', en: 'General warm-up', fr: 'Échauffement général', es: 'Calentamiento general' },
  'main-strength': { pl: 'Siła · całe ciało', en: 'Strength · whole body', fr: 'Force · corps entier', es: 'Fuerza · cuerpo entero' },
  'cooldown-basic': { pl: 'Spokojne zakończenie', en: 'Easy finish', fr: 'Fin de séance en douceur', es: 'Final suave' },
};
