'use client';
import {useEffect,useRef,useState} from 'react';
import {Table2,Download,RefreshCw,ExternalLink,Check,Copy,ShieldCheck,Unplug} from 'lucide-react';
import {type Profile,type State} from '@/lib/domain';
import {appsScript} from '@/lib/sheets-script';
import {Field} from './forms';
import {useLanguage,num} from './language';

type Connection={configured:boolean;endpoint:string;spreadsheetId:string;autoSync:boolean;lastRevision:number|null;lastSyncedAt:string|null;lastError:string|null};
type ApiResult=Connection&{success:boolean;error?:string;rows:number;weeks:number;revision:number};
const emptyConnection:Connection={configured:false,endpoint:'',spreadsheetId:'',autoSync:false,lastRevision:null,lastSyncedAt:null,lastError:null};
const endpointPattern=/^https:\/\/script\.google\.com\/macros\/s\/[A-Za-z0-9_-]+\/exec$/;

const errorTranslations:Record<string,string>={
 'Nie znaleziono profilu.':'This profile could not be found.',
 'Sprawdź dane połączenia i identyfikator profilu.':'Check the connection details and profile identifier.',
 'Klucz musi mieć co najmniej 32 znaki.':'The connection key must contain at least 32 characters.',
 'Ten plik arkusza jest już przypisany do innej osoby. Użyj osobnego pliku.':'This spreadsheet belongs to another profile. Use a separate file.',
 'Najpierw skonfiguruj połączenie z arkuszem.':'Configure the spreadsheet connection first.',
 'Nieprawidłowy profil.':'Invalid profile.',
 'Sprawdź konfigurację połączenia z arkuszem.':'Check the spreadsheet connection settings.',
 'Eksport przekracza limit wielkości.':'The export exceeds the size limit.',
 'Google nie zwrócił potwierdzenia.':'Google did not return a confirmation.',
 'Google zwrócił nieprawidłową odpowiedź. Sprawdź dostęp do skryptu.':'Google returned an invalid response. Check access to the script.',
 'Brak odpowiedzi Google.':'No response from Google.',
 'Google wymaga innej konfiguracji dostępu. Sprawdź wdrożenie skryptu.':'Google requires different access settings. Check the script deployment.',
 'Google nie potwierdził eksportu. Sprawdź arkusz przed ponowieniem.':'Google did not confirm the export. Check the spreadsheet before retrying.',
 'Google zwrócił stronę logowania lub nieprawidłową odpowiedź. Sprawdź dostęp do skryptu.':'Google returned a sign-in page or an invalid response. Check script access.',
 'Google nie potwierdził zapisu.':'Google did not confirm the save.',
 'Nieprawidłowe potwierdzenie zapisu. Sprawdź arkusz.':'Invalid save confirmation. Check the spreadsheet.',
 'Upłynął czas oczekiwania. Eksport mógł się udać; sprawdź arkusz przed ponowieniem.':'The request timed out. The export may have succeeded; check the spreadsheet before retrying.',
 'Nie udało się zsynchronizować arkusza. Spróbuj ponownie.':'The spreadsheet could not be synchronized. Try again.',
 'Invalid connection key or spreadsheet.':'Invalid connection key or spreadsheet.',
 'Update the bridge to FIELDWORK v2.':'Replace the Apps Script code and redeploy Trainleaf v2.',
 'This bridge is linked to a different profile.':'This Apps Script deployment is linked to another profile. Use a separate spreadsheet and deployment.',
 'A newer plan is already stored in this spreadsheet.':'A newer plan is already stored in this spreadsheet. Refresh the planner and retry.'
};
const scriptErrorsPl:Record<string,string>={
 'Invalid connection key or spreadsheet.':'Nieprawidłowy klucz połączenia lub arkusz.',
 'Update the bridge to FIELDWORK v2.':'Zastąp kod Apps Script wersją Trainleaf v2 i opublikuj nowe wdrożenie.',
 'This bridge is linked to a different profile.':'Ten skrypt jest przypisany do innej osoby. Użyj osobnego arkusza i wdrożenia.',
 'A newer plan is already stored in this spreadsheet.':'W arkuszu jest już nowsza wersja planu. Odśwież planer i spróbuj ponownie.',
 'Invalid export identity.':'Nieprawidłowe dane eksportu. Odśwież planer i spróbuj ponownie.',
 'Invalid weekly plan.':'Nieprawidłowe dane tygodnia. Odśwież planer i spróbuj ponownie.',
 'Repeated week.':'Eksport zawiera powtórzony tydzień.'
};

export default function Integrations({profile,state,busy,onCSV,notify}:{profile:Profile;state:State;busy:boolean;onCSV:()=>void;notify:(s:string)=>void}){
 const{t,lang}=useLanguage();const[connection,setConnection]=useState<Connection>(emptyConnection),[endpoint,setEndpoint]=useState(''),[spreadsheet,setSpreadsheet]=useState(''),[secret,setSecret]=useState(''),[autoSync,setAutoSync]=useState(false),[pending,setPending]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[dirty,setDirty]=useState(false),[result,setResult]=useState<{rows:number;weeks:number;revision:number}|null>(null);
 const activeProfile=useRef(profile.id),operation=useRef<string|null>(null),dirtyRef=useRef(false),statusRequest=useRef<AbortController|null>(null);activeProfile.current=profile.id;
 const sheetId=spreadsheet.match(/\/spreadsheets\/d\/([\w-]+)/)?.[1]||spreadsheet.trim();
 const locked=pending||loading||busy;
 function translatedError(message:string){if(lang==='pl'){if(scriptErrorsPl[message])return scriptErrorsPl[message];if(message.startsWith('Tab "'))return t('Zakładka o tej nazwie zawiera dane spoza Trainleaf. Zmień jej nazwę w arkuszu i ponów zapis.','');return message}if(errorTranslations[message])return errorTranslations[message];if(message.startsWith('Tab "'))return 'A matching tab contains data not managed by Trainleaf. Rename it in Google Sheets, then retry.';return /[ąćęłńóśźż]/i.test(message)?t('','The operation failed. Check the connection settings and script deployment, then retry.'):message}
 function changed(){setDirty(true);dirtyRef.current=true;setResult(null)}
 function applyConnection(data:Connection,replaceFields:boolean){setConnection({...emptyConnection,...data});if(replaceFields){setEndpoint(data.endpoint||'');setSpreadsheet(data.spreadsheetId||'');setAutoSync(!!data.autoSync)}}
 async function refreshStatus(id=profile.id,replaceFields=false){
  statusRequest.current?.abort();const controller=new AbortController();statusRequest.current=controller;setLoading(true);
  try{const response=await fetch('/api/sheets?profileId='+encodeURIComponent(id),{cache:'no-store',signal:controller.signal});const data=await response.json() as Connection&{error?:string};if(!response.ok)throw Error(data.error||t('Nie udało się odczytać statusu.','Could not load the connection status.'));if(activeProfile.current!==id)return;applyConnection(data,replaceFields&&!dirtyRef.current);}
  catch(e){if(controller.signal.aborted||activeProfile.current!==id)return;setError(e instanceof Error?e.message:t('Nie udało się odczytać statusu.','Could not load the connection status.'));}
  finally{if(activeProfile.current===id&&!controller.signal.aborted)setLoading(false)}
 }
 useEffect(()=>{setConnection(emptyConnection);setEndpoint('');setSpreadsheet('');setSecret('');setAutoSync(false);setDirty(false);dirtyRef.current=false;setError('');setResult(null);setPending(false);void refreshStatus(profile.id,true);return()=>statusRequest.current?.abort()},[profile.id]);
 async function request(action:'configure'|'sync'|'disconnect',autoOverride?:boolean){
  const id=profile.id;if(operation.current===id)return;
  if(action==='disconnect'&&!confirm(t('Odłączyć arkusz tej osoby i wyłączyć automatyczny zapis? Plik Google Sheets pozostanie na Twoim koncie.','Disconnect this profile and stop automatic syncing? The Google Sheets file will remain in your account.')))return;
  if(action==='configure'&&!endpointPattern.test(endpoint.trim())){setError(t('Wklej adres wdrożenia Apps Script kończący się na /exec.','Paste the Apps Script deployment URL ending in /exec.'));return}
  if(action==='configure'&&!/^[\w-]{20,150}$/.test(sheetId)){setError(t('Wklej pełny link Google Sheets lub poprawny identyfikator pliku.','Paste the complete Google Sheets URL or a valid file identifier.'));return}
  operation.current=id;setPending(true);setError('');setResult(null);
  try{
   const body=action==='configure'?{action,profileId:id,endpoint:endpoint.trim(),spreadsheetId:sheetId,secret:autoOverride===undefined?secret:'',autoSync:autoOverride??autoSync}:action==='sync'?{action,profileId:id}:{profileId:id};
   const response=await fetch('/api/sheets',{method:action==='disconnect'?'DELETE':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json() as ApiResult;if(!response.ok||!data.success)throw Error(data.error||t('Nie udało się wykonać operacji.','The operation could not be completed.'));if(activeProfile.current!==id)return;
   if(action==='configure'){dirtyRef.current=false;setDirty(false);setSecret('');applyConnection(data,true);notify(autoOverride===undefined?t('Zapisano konfigurację połączenia','Connection settings saved'):autoOverride?t('Włączono automatyczny zapis do arkusza','Automatic spreadsheet syncing enabled'):t('Wyłączono automatyczny zapis do arkusza','Automatic spreadsheet syncing disabled'));}
   else if(action==='disconnect'){dirtyRef.current=false;setDirty(false);setSecret('');applyConnection(emptyConnection,true);notify(t('Odłączono arkusz tej osoby','This profile’s spreadsheet was disconnected'));}
   else{setResult({rows:Number(data.rows)||0,weeks:Number(data.weeks)||0,revision:Number(data.revision)||0});setConnection(current=>({...current,lastRevision:data.revision,lastSyncedAt:data.lastSyncedAt,lastError:null}));notify(t('Google Sheets potwierdził zapis','Google Sheets confirmed the save'));}
   if(action!=='disconnect')await refreshStatus(id,true);
  }catch(e){if(activeProfile.current===id){setError(e instanceof Error?e.message:t('Błąd połączenia.','Connection error.'));if(action==='sync')await refreshStatus(id,false)}}
  finally{if(operation.current===id)operation.current=null;if(activeProfile.current===id)setPending(false)}
 }
 async function copyScript(){try{await navigator.clipboard.writeText(appsScript);notify(t('Skopiowano skrypt Trainleaf v2','Trainleaf v2 script copied'))}catch{setError(t('Zaznacz i skopiuj kod poniżej.','Select and copy the code below.'))}}
 async function generateKey(){const value=crypto.randomUUID()+crypto.randomUUID();setSecret(value);changed();try{await navigator.clipboard.writeText(value);notify(t('Wygenerowano i skopiowano klucz — wklej go we właściwościach skryptu','Key generated and copied — paste it into the script properties'))}catch{setError(t('Klucz wygenerowano, ale nie udało się go skopiować. Wygeneruj ponownie albo wprowadź własny losowy klucz, min. 32 znaki.','The key was generated but could not be copied. Generate it again or enter your own random key of at least 32 characters.'))}}
 const syncedAt=connection.lastSyncedAt?new Date(connection.lastSyncedAt):null;
 const timestamp=syncedAt&&!Number.isNaN(syncedAt.getTime())?syncedAt.toLocaleString(lang==='pl'?'pl-PL':'en-GB',{dateStyle:'medium',timeStyle:'short'}):t('Jeszcze nie zapisano','Not synced yet');
 const counts={workouts:state.workouts.filter(w=>w.profileId===profile.id).length,fatigue:state.fatigue.filter(w=>w.profileId===profile.id).length,periods:state.periods.filter(w=>w.profileId===profile.id).length,events:state.events.filter(w=>w.profileId===profile.id).length};
 return <div className="integration-layout"><section className="panel integration-card"><div className="heading-icon"><Table2 size={24}/></div><h2>Google Sheets · {profile.name}</h2><p>{t('Każda osoba ma osobny plik. Nowe tygodnie otrzymują własne zakładki; kolejne zapisy aktualizują istniejące tygodnie.','Each person has a separate file. New weeks get their own tabs; subsequent saves update existing weeks.')}</p>
 <div className="integration-info">{t('Tygodniowe zakładki mają siedem bloków dni od poniedziałku do niedzieli, jak w przesłanych planach. Kolumny pokazują ćwiczenia, serie, powtórzenia, ciężar lub wysiłek, przerwy, wskazówki i wykonanie.','Weekly tabs contain seven daily blocks from Monday to Sunday, following the supplied plans. Columns show exercises, sets, repetitions, weight or effort, rest, cues and actual work.')}<br/>{t('Status konfiguracji: ','Configuration status: ')}<strong>{loading?t('Sprawdzanie…','Checking…'):connection.configured?t('zapisana','saved'):t('jeszcze nie skonfigurowano','not configured yet')}</strong>.</div>
 <form onSubmit={e=>{e.preventDefault();void request('configure')}}><Field label={t('Link lub identyfikator arkusza tej osoby','This person’s spreadsheet URL or identifier')}><input required disabled={locked} value={spreadsheet} placeholder="https://docs.google.com/spreadsheets/d/…" onChange={e=>{setSpreadsheet(e.target.value);changed()}}/></Field><Field label={t('Adres opublikowanego skryptu · /exec','Published script URL · /exec')}><input required disabled={locked} type="url" value={endpoint} placeholder="https://script.google.com/macros/s/…/exec" onChange={e=>{setEndpoint(e.target.value);changed()}}/></Field><Field label={connection.configured?t('Klucz połączenia · puste pole zachowuje obecny','Connection key · leave blank to retain the existing key'):t('Klucz połączenia · co najmniej 32 znaki','Connection key · at least 32 characters')}><input type="password" disabled={locked} autoComplete="new-password" minLength={32} maxLength={500} required={!connection.configured} value={secret} onChange={e=>{setSecret(e.target.value);changed()}}/></Field>
 {!connection.configured&&<label style={{display:'flex',alignItems:'flex-start',gap:10,fontSize:'.85rem',lineHeight:1.6}}><input type="checkbox" disabled={locked} checked={autoSync} onChange={e=>{setAutoSync(e.target.checked);changed()}} style={{marginTop:5}}/><span>{t('Włącz automatyczny zapis po zapisaniu zmian w planerze','Enable automatic syncing after changes are saved in the planner')}</span></label>}
 <div className="profile-actions" style={{flexWrap:'wrap'}}><button className="btn secondary" disabled={locked} type="button" style={{whiteSpace:'normal'}} onClick={generateKey}>{t('Wygeneruj i skopiuj klucz','Generate and copy a key')}</button><button className="btn primary" disabled={locked} type="submit">{pending?t('Zapisywanie…','Saving…'):t('Zapisz konfigurację','Save settings')}</button></div></form>
 <details><summary>{t('Połączenie i aktualizacja skryptu · Trainleaf v2','Setup and script update · Trainleaf v2')}</summary><div className="integration-info" style={{marginTop:18}}><strong>{t('Masz starszy skrypt? Zastąp cały kod poniższą wersją v2 i opublikuj nowe wdrożenie. Sam zapis kodu w edytorze nie aktualizuje opublikowanej aplikacji.','Already using an older script? Replace all code with v2 below and publish a new deployment. Saving the code in the editor does not update the deployed web app.')}</strong></div><ol>
 <li>{t('Utwórz osobny plik Google Sheets dla tej osoby. Wybierz ','Create a separate Google Sheets file for this person. Choose ')}<strong>{t('Rozszerzenia → Apps Script','Extensions → Apps Script')}</strong>{t(', zastąp kod zawartością poniżej i zapisz.',', replace the code with the version below and save.')}</li>
 <li>{t('W ','In ')}<strong>{t('Ustawienia projektu → Właściwości skryptu','Project Settings → Script Properties')}</strong>{t(' dodaj ',' add ')}<code>FIELDWORK_SHEET_ID</code>{t(' z identyfikatorem pliku (fragment linku między ',' with the file identifier (the URL segment between ')}<code>/d/</code>{t(' i ',' and ')}<code>/edit</code>{t(') oraz ',') and ')}<code>FIELDWORK_SECRET</code>{t(' z tym samym kluczem, który wpiszesz w formularzu.',' with the same key you enter in the form.')}</li>
 <li>{t('Wybierz ','Choose ')}<strong>{t('Wdróż → Nowe wdrożenie → Aplikacja internetowa','Deploy → New deployment → Web app')}</strong>{t('. Ustaw wykonanie jako Ty i dostęp „Wszyscy”. Zatwierdź dostęp skryptu do arkusza na swoim koncie Google. Zapis jest dodatkowo chroniony kluczem.','. Set execution to your account and access to “Anyone”. Authorize access to the spreadsheet in your Google account. Writes are additionally protected by the connection key.')}</li>
 <li>{t('Wklej adres wdrożenia kończący się na ','Paste the deployment URL ending in ')}<code>/exec</code>{t(', podaj identyfikator pliku oraz klucz i zapisz konfigurację. Wykonaj pierwszy ręczny zapis, aby sprawdzić połączenie.',', enter the file identifier and key, and save the settings. Run the first manual sync to verify the connection.')}</li>
 <li>{t('Przy aktualizacji istniejącego wdrożenia wybierz Zarządzaj wdrożeniami → Edytuj → Nowa wersja → Wdróż albo utwórz nowe wdrożenie i podmień adres /exec w formularzu.','To update an existing deployment, choose Manage deployments → Edit → New version → Deploy, or create a new deployment and replace the /exec URL in the form.')}</li>
 </ol><button type="button" className="btn secondary small" disabled={pending} onClick={copyScript}><Copy size={15}/>{t('Kopiuj skrypt v2','Copy v2 script')}</button><pre className="code-preview" aria-label={t('Kod Google Apps Script','Google Apps Script code')}>{appsScript}</pre><a className="text-btn" href="https://developers.google.com/apps-script/guides/web" target="_blank" rel="noreferrer">{t('Instrukcja Google Apps Script','Google Apps Script documentation')}</a></details>
 {error&&<div className="form-error-inline" role="alert" style={{marginTop:18}}>{translatedError(error)}</div>}</section>
 <div className="integration-side"><section className="panel integration-card"><h2>{t('Zapis i status połączenia','Sync and connection status')}</h2><p>{t('Wybrana osoba: ','Selected person: ')}<strong>{profile.name}</strong></p>
 {connection.configured&&<><label style={{display:'flex',alignItems:'flex-start',gap:10,fontSize:'.85rem',lineHeight:1.6}}><input type="checkbox" checked={connection.autoSync} disabled={locked||dirty} onChange={e=>void request('configure',e.target.checked)} style={{marginTop:5}}/><span><strong>{t('Automatyczny zapis','Automatic sync')}</strong><br/>{t('Po zapisaniu zmian tej osoby w aplikacji. Nowe tygodnie są tworzone automatycznie.','After this person’s changes are saved in the app. New weeks are created automatically.')}</span></label><p className="micro" style={{marginTop:12}}>{t('Zapis działa w tle. Błąd arkusza nie usuwa zmian zapisanych w planerze. Po błędzie kolejny zapis danych ponawia próbę; możesz też ponowić ręcznie.','Sync runs in the background. A spreadsheet error does not undo planner changes. The next data save retries a failed sync; you can also retry manually.')}</p></>}
 <div className="info-list"><span><Check size={16}/>{num(counts.workouts,lang)} {t('treningów · plan i wykonanie','workouts · planned and actual')}</span><span><Check size={16}/>{num(counts.fatigue,lang)} {t('pomiarów zmęczenia','fatigue measurements')}</span><span><Check size={16}/>{num(counts.periods,lang)} {t('cykli treningowych','training cycles')}</span><span><Check size={16}/>{num(counts.events,lang)} {t('wydarzeń i wyjazdów','events and trips')}</span></div>
 <button type="button" className="btn primary" style={{width:'100%',whiteSpace:'normal'}} disabled={!connection.configured||dirty||locked} onClick={()=>void request('sync')}><RefreshCw size={16} className={pending?'spin':''}/>{pending?t('Łączenie…','Connecting…'):connection.lastError?t('Ponów zapis do Google Sheets','Retry Google Sheets sync'):t('Zapisz teraz do Google Sheets','Sync to Google Sheets now')}</button>{dirty&&<p className="micro" style={{marginTop:12}}>{t('Zapisz zmienioną konfigurację przed synchronizacją lub zmianą automatycznego zapisu.','Save the changed settings before syncing or changing automatic sync.')}</p>}
 <div className="integration-status" aria-live="polite"><p style={{margin:'0 0 9px'}}>{t('Ostatni potwierdzony zapis: ','Last confirmed sync: ')}<strong>{timestamp}</strong></p><p style={{margin:'0 0 9px'}}>{t('Wersja zapisanych danych: ','Synced data revision: ')}<strong>{connection.lastRevision===null?'—':connection.lastRevision}</strong></p>{result&&<p>{t('Google potwierdził zapis: ','Google confirmed the save: ')}{num(result.weeks,lang)} {t('tygodni, ','weeks, ')}{num(result.rows,lang)} {t('wierszy danych.','data rows.')}</p>}{connection.lastError&&<div className="form-error-inline" role="alert"><strong>{t('Ostatni błąd: ','Last error: ')}</strong>{translatedError(connection.lastError)}</div>}<button type="button" className="text-btn" disabled={pending||loading} onClick={()=>{setError('');void refreshStatus(profile.id,true)}}><RefreshCw size={13} style={{display:'inline',marginRight:6}}/>{loading?t('Sprawdzanie statusu…','Checking status…'):t('Odśwież status','Refresh status')}</button></div>
 {connection.configured&&/^[\w-]{20,150}$/.test(connection.spreadsheetId)&&<div style={{display:'flex',flexWrap:'wrap',gap:10,marginTop:18}}><a className="btn secondary" href={'https://docs.google.com/spreadsheets/d/'+connection.spreadsheetId+'/edit'} target="_blank" rel="noreferrer"><ExternalLink size={15}/>{t('Otwórz arkusz','Open spreadsheet')}</a><button type="button" className="btn secondary" disabled={locked} onClick={()=>void request('disconnect')}><Unplug size={15}/>{t('Odłącz','Disconnect')}</button></div>}
 </section><section className="panel integration-card"><h2>{t('Pobierz CSV','Download CSV')}</h2><p>{t('Pobierz dane aktywnej osoby i otwórz je w Google Sheets lub Excelu. CSV jest tabelą danych; układ tygodni powstaje przez połączenie ze skryptem v2.','Download the active person’s data for Google Sheets or Excel. CSV is a data table; the weekly layout is created through the v2 script connection.')}</p><button type="button" className="btn secondary" disabled={busy} onClick={onCSV}><Download size={16}/>{t('Pobierz plik CSV','Download CSV file')}</button></section>
 <section className="panel integration-card"><ShieldCheck size={23} color="#7392b8"/><p>{t('Aplikacja jest źródłem planu. Każdy zapis nadpisuje zarządzane zakładki tygodni oraz tabelę danych. Notatki wpisane bezpośrednio w tych zakładkach nie wracają do aplikacji i mogą zostać zastąpione — wpisuj je w planerze.','The app is the source of the plan. Each sync overwrites managed weekly tabs and the data table. Notes entered directly in those tabs are not imported into the app and may be replaced — enter them in the planner.')}</p><p>{t('Niezarządzane zakładki pozostają bez zmian. Odłączenie wyłącza dalsze zapisy i zachowuje plik na koncie Google.','Unmanaged tabs remain unchanged. Disconnecting stops future syncs and keeps the file in your Google account.')}</p></section></div></div>;
}
