'use client';
import {useState} from 'react';
import {Sun,Sunrise,Moon,Check,ArrowRight} from 'lucide-react';
import {addDays,clone,localDay,type Wellness,type Fatigue} from '@/lib/domain';
import {wellnessSlots,slotNames,slotQuestions,wellnessQuestions,wellnessText,wellnessSources,wellnessResponseSchema,type WellnessSlot,type WellnessMetric} from '@/lib/wellness';
import {useLanguage,fmtDay,num} from './language';
import {Modal,Field,Actions} from './forms';

const slotIcons={morning:Sunrise,daytime:Sun,evening:Moon};
export function WellbeingToday({entries,date,onOpen,onHistory}:{entries:Wellness[];date:string;onOpen:(date:string,slot:WellnessSlot)=>void;onHistory:()=>void}){
 const{t,lang}=useLanguage();
 return <section className="panel wellbeing-today"><div className="panel-header"><h2>{t('Samopoczucie','Wellbeing')}</h2><button className="text-btn" onClick={onHistory}>{t('Historia','History')} <ArrowRight size={15}/></button></div><p>{t('Krótki zapis o różnych porach dnia.','A quick check-in at different times of day.')}</p><div className="wellness-slots">{wellnessSlots.map(slot=>{const entry=entries.find(w=>w.date===date&&w.slot===slot),Icon=slotIcons[slot];return <button className={'wellness-slot '+(entry?'filled':'')} key={slot} onClick={()=>onOpen(date,slot)}><Icon size={22}/><span><strong>{slotNames[slot][lang]}</strong><small>{entry?t('Zapisano','Recorded'):t('Brak wpisu','No entry')}</small></span>{entry?<Check size={17}/>:<span>＋</span>}</button>})}</div></section>;
}
export function WellbeingView({entries,legacy,date,onDate,onOpen}:{entries:Wellness[];legacy:Fatigue[];date:string;onDate:(date:string)=>void;onOpen:(date:string,slot:WellnessSlot)=>void}){
 const{t,lang}=useLanguage(),[slot,setSlot]=useState<WellnessSlot>('morning'),[metric,setMetric]=useState<WellnessMetric>('fatigue'),[range,setRange]=useState(7);
 const q=wellnessQuestions[metric],days=Array.from({length:range},(_,i)=>addDays(date,i-range+1)),points=days.map(day=>({day,entry:entries.find(w=>w.date===day&&w.slot===slot)})),values=points.map(p=>p.entry?.answers[metric]).filter((v):v is number=>v!==undefined);
 return <><div className="toolbar"><Field label={t('Dzień','Day')}><input type="date" required max={localDay()} value={date} onChange={e=>e.target.value&&onDate(e.target.value)}/></Field><button className="btn secondary" onClick={()=>onDate(localDay())}>{t('Dzisiaj','Today')}</button></div><div className="wellness-day-grid">{wellnessSlots.map(s=>{const entry=entries.find(w=>w.date===date&&w.slot===s),Icon=slotIcons[s];return <section className="panel wellness-day" key={s}><div className="card-top"><Icon size={24}/><span className="badge">{entry?t('Zapisano','Recorded'):t('Brak wpisu','No entry')}</span></div><h2>{slotNames[s][lang]}</h2><dl>{slotQuestions[s].map(k=><div key={k}><dt>{wellnessQuestions[k].label[lang]}</dt><dd>{entry?.answers[k]===undefined?'—':num(entry.answers[k]!,lang)+(k==='sleepHours'?' h':'/'+wellnessQuestions[k].max)}</dd></div>)}</dl>{entry?.notes&&<p className="pre-line">{entry.notes}</p>}{entry&&<small>{entry.recordedBy==='athlete'?t('Wpis zawodnika','Athlete entry'):t('Wpis trenera / własny','Coach / personal entry')}</small>}<button className="btn secondary" onClick={()=>onOpen(date,s)}>{entry?t('Otwórz zapis','Open entry'):t('Uzupełnij','Check in')}</button></section>})}</div>
 <section className="panel wellness-history"><div className="panel-header"><h2>{t('Zmiany w czasie','Changes over time')}</h2><select aria-label={t('Zakres historii','History range')} value={range} onChange={e=>setRange(Number(e.target.value))}><option value={7}>{t('7 dni','7 days')}</option><option value={28}>{t('28 dni','28 days')}</option></select></div><div className="toolbar"><Field label={t('Pora dnia','Time of day')}><select value={slot} onChange={e=>{const s=e.target.value as WellnessSlot;setSlot(s);if(!slotQuestions[s].includes(metric))setMetric(slotQuestions[s][0])}}>{wellnessSlots.map(s=><option key={s} value={s}>{slotNames[s][lang]}</option>)}</select></Field><Field label={t('Pomiar','Measurement')}><select value={metric} onChange={e=>setMetric(e.target.value as WellnessMetric)}>{slotQuestions[slot].map(k=><option key={k} value={k}>{wellnessQuestions[k].label[lang]}</option>)}</select></Field><p>{values.length} {t('pomiarów','measurements')} · {t('średnia','mean')}: <b>{values.length?num(values.reduce((a,b)=>a+b,0)/values.length,lang):'—'}</b>{metric==='sleepHours'?' h':'/'+q.max}</p></div><p>{q.ends[lang]}</p><div className="wellness-chart-scroll"><div className="wellness-chart" style={{gridTemplateColumns:`repeat(${range},minmax(32px,1fr))`}}>{points.map(({day,entry})=>{const v=entry?.answers[metric];return <button key={day} className="wellness-point" aria-label={`${fmtDay(day,lang)} · ${q.label[lang]}: ${v??t('brak pomiaru','no measurement')}`} onClick={()=>onOpen(day,slot)}><b>{v===undefined?'—':num(v,lang)}</b><span className="wellness-track">{v!==undefined&&<i style={{height:`${Math.max(2,v/q.max*100)}%`}}/>}</span><small>{fmtDay(day,lang,{day:'numeric',month:'numeric'})}</small></button>})}</div></div><p className="micro">{t('Porównuj tę samą porę dnia. Kreska oznacza brak odpowiedzi; zero jest zapisanym wynikiem.','Compare the same time of day. A dash means no answer; zero is a recorded value.')}</p></section>
 {!!legacy.length&&<details className="panel wellness-legacy"><summary>{t('Wcześniejsze pomiary zmęczenia','Earlier fatigue measurements')} ({legacy.length})</summary><p>{t('Starsze wpisy nie mają przypisanej pory dnia.','These older entries have no recorded time of day.')}</p>{legacy.filter(f=>f.date>=days[0]&&f.date<=date).map(f=><div className="fatigue-list-item" key={f.id}><span>{fmtDay(f.date,lang)} · {f.notes}</span><b>{f.value}/10</b></div>)}</details>}
 <details className="panel wellness-sources"><summary>{t('Jak korzystać z pomiarów · źródła','Using these measurements · sources')}</summary><p>{t('Odpowiedzi pomagają obserwować zmiany i rozmawiać o treningu. To autorskie pytania do samoobserwacji, nie zwalidowany test gotowości. Trzy pory dnia są sposobem prowadzenia dziennika.','Your answers help track changes and discuss training. These are original reflection questions, not a validated readiness test. Three daily slots provide a diary structure.')}</p>{wellnessSources.map(s=><a className="source-link" href={s.url} target="_blank" rel="noreferrer" key={s.url}>{s.label} ↗</a>)}</details></>;
}
export function WellbeingForm({initial,onSave,onClose,busy,error,readOnly=false}:{initial:Wellness;onSave:(entry:Wellness)=>void;onClose:()=>void;busy:boolean;error:string;readOnly?:boolean}){
 const{t,lang}=useLanguage(),[v,set]=useState(clone(initial)),[localError,setLocalError]=useState('');
 const submit=()=>{const r=wellnessResponseSchema.safeParse(v);if(!r.success){setLocalError(t('Odpowiedz na przynajmniej jedno pytanie i sprawdź zakresy.','Answer at least one question and check the ranges.'));return}onSave(v)};
 return <Modal title={`${t('Samopoczucie','Wellbeing')} · ${slotNames[v.slot][lang]}`} onClose={onClose} busy={busy} error={localError||error}><form onSubmit={e=>{e.preventDefault();if(!readOnly)submit()}}><div className="modal-body wellness-form"><p>{fmtDay(v.date,lang,{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</p><p>{v.slot==='morning'?t('Po przebudzeniu. Pytania o sen dotyczą ostatniej nocy.','After waking. Sleep questions refer to last night.'):v.slot==='daytime'?t('W ciągu dnia, najlepiej o podobnej porze.','During your day, preferably at a similar time.'):t('Pod koniec dnia, po codziennych aktywnościach.','Toward the end of the day, after your daily activities.')}</p>{readOnly&&<p className="notice">{t('Zapis zawodnika. Trener może go przeglądać; odpowiedzi aktualizuje zawodnik.','Athlete entry. The coach can review it; the athlete updates the answers.')}</p>}
 {slotQuestions[v.slot].map(k=>{const q=wellnessQuestions[k];return <Field key={k} label={q.question[lang]}><div className="wellness-answer">{k==='sleepHours'?<input aria-label={q.question[lang]} disabled={readOnly} type="number" min={q.min} max={q.max} step={q.step} placeholder="—" value={v.answers[k]??''} onChange={e=>set({...v,answers:{...v.answers,[k]:e.target.value===''?undefined:Number(e.target.value)}})}/>:<select aria-label={q.question[lang]} disabled={readOnly} value={v.answers[k]??''} onChange={e=>set({...v,answers:{...v.answers,[k]:e.target.value===''?undefined:Number(e.target.value)}})}><option value="">{t('Wybierz odpowiedź','Select an answer')}</option>{Array.from({length:q.max-q.min+1},(_,i)=>i+q.min).map(n=><option key={n} value={n}>{n}</option>)}</select>}<small>{q.ends[lang]}</small></div></Field>})}
 <Field label={t('Notatka · opcjonalna','Note · optional')}><textarea readOnly={readOnly} maxLength={3000} value={v.notes} onChange={e=>set({...v,notes:e.target.value})}/></Field><p className="micro">{t('Nie musisz odpowiadać na wszystkie pytania. Puste odpowiedzi pozostają puste.','You can skip questions. Unanswered questions remain blank.')}</p></div>{readOnly?<div className="modal-actions"><button type="button" className="btn secondary" onClick={onClose}>{t('Zamknij','Close')}</button></div>:<Actions busy={busy} onClose={onClose} label={t('Zapisz samopoczucie','Save wellbeing')}/>}</form></Modal>;
}
