import { z } from 'zod';
import {exerciseTypes,inferExerciseTypes,type ExerciseType} from './exercise-types';
import {wellnessFields,wellnessResponseSchema,wellnessText,slotNames} from './wellness';
export const categories = { strength: 'Siłowy', running: 'Biegowy', throwing: 'Rzutowy', conditioning: 'Wydolnościowy' } as const;
export const muscles = { quads: 'Czworogłowe uda', hamstrings: 'Tył uda', glutes: 'Pośladki', calves: 'Łydki', chest: 'Klatka piersiowa', shoulders: 'Barki', lats: 'Najszersze grzbietu', upper_back: 'Górna część pleców', lower_back: 'Prostowniki grzbietu', biceps: 'Biceps', triceps: 'Triceps', forearms: 'Przedramiona', abs: 'Prosty brzucha', obliques: 'Skośne brzucha', adductors: 'Przywodziciele uda', abductors: 'Odwodziciele biodra', hip_flexors: 'Zginacze biodra', back: 'Plecy · ogólnie', arms: 'Ramiona · ogólnie', core: 'Tułów · ogólnie' } as const;
export const metrics = { kg: 'kg·powt.', reps: 'powt.', meters: 'm', throws: 'rzuty', minutes: 'min' } as const;
export const sections = { warmup: 'Rozgrzewka', main: 'Część główna', cooldown: 'Cooldown' } as const;
export type Category = keyof typeof categories; export type Muscle = keyof typeof muscles; export type Metric = keyof typeof metrics; export type Section = keyof typeof sections;
const id = z.string().min(1).max(100).regex(/^[\w-]+$/), short = z.string().trim().min(1).max(140), note = z.string().max(3000);
export const daySchema = z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v => !Number.isNaN(new Date(v+'T12:00:00Z').getTime()) && new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v, 'Nieprawidłowa data');
const number = z.number().finite().min(0).max(100000), category = z.enum(['strength','running','throwing','conditioning']), metric = z.enum(['kg','reps','meters','throws','minutes']), section = z.enum(['warmup','main','cooldown']);
const video = z.string().max(2000).refine(v=>!v || /^https:\/\//i.test(v) && (()=>{try{const u=new URL(v);return !u.username&&!u.password}catch{return false}})(), {message:'Wklej poprawny link https://',params:{code:'videoLinkInvalid'}});
const shares = z.array(z.object({ muscle: z.enum(Object.keys(muscles) as [Muscle,...Muscle[]]), weight: z.number().finite().min(0).max(1) })).max(20).refine(a=>new Set(a.map(x=>x.muscle)).size===a.length && (!a.length || Math.abs(a.reduce((s,x)=>s+x.weight,0)-1)<0.001), {message:'Udziały mięśni muszą sumować się do 100%',params:{code:'muscleSharesInvalid'}});
export const exerciseSchema = z.object({id,name:short,category,metric,shares,video,notes:note,nameEn:z.string().max(140).optional(),notesEn:note.optional(),cues:note.optional(),cuesEn:note.optional(),variants:note.optional(),variantsEn:note.optional(),sourceUrls:z.array(video).max(12).optional(),provenance:z.string().max(1000).optional(),prescription:z.string().max(500).optional(),types:z.array(z.enum(Object.keys(exerciseTypes) as [ExerciseType,...ExerciseType[]])).min(1).max(9).refine(a=>new Set(a).size===a.length).optional()});
export const doseSchema = z.object({sets:z.number().int().min(1).max(100),quantity:number,kg:number,prescription:z.string().max(500).optional(),tempo:z.string().max(100).optional(),rest:z.string().max(100).optional(),effort:z.string().max(100).optional()});
export const itemSchema = z.object({id,exercise:exerciseSchema,planned:doseSchema,actual:doseSchema.nullable(),athleteNotes:note.optional()});
const sectionSchema = z.object({warmup:z.array(itemSchema).max(60),main:z.array(itemSchema).max(100),cooldown:z.array(itemSchema).max(60)});
export const workoutSchema = z.object({id,profileId:id,name:short,date:daySchema,time:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),category,status:z.enum(['planned','completed','skipped']),duration:z.number().finite().min(0).max(1440),actualMinutes:z.number().finite().min(0).max(1440).nullable(),rpe:z.number().finite().min(0).max(10).nullable(),notes:note,athleteNotes:note.optional(),sections:sectionSchema});
export const templateSchema = z.object({id,name:short,category,section,items:z.array(itemSchema).max(100)});
export const profileSchema = z.object({id,name:short,role:z.string().max(100),notes:note,warmupId:z.string().max(100)});
export const fatigueSchema = z.object({id,profileId:id,date:daySchema,value:z.number().int().min(0).max(10),notes:note});
export const wellnessSchema=z.object({id,profileId:id,date:daySchema,slot:wellnessFields.slot,answers:wellnessFields.answers,notes:note,recordedBy:z.enum(['coach','athlete']).default('coach')}).superRefine((v,ctx)=>{const r=wellnessResponseSchema.safeParse(v);if(!r.success)for(const issue of r.error.issues)ctx.addIssue({...issue,path:issue.path});});
export type Wellness=z.infer<typeof wellnessSchema>;
export const periodSchema = z.object({id,profileId:id,name:short,start:daySchema,end:daySchema,phase:short,goal:note,level:z.enum(['macro','meso','micro']).optional(),parentId:z.string().max(100).optional()}).refine(p=>p.start<=p.end,'Koniec okresu musi przypadać po początku');
export const eventSchema=z.object({id,profileId:id,title:short,start:daySchema,end:daySchema,time:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),kind:z.enum(['event','trip','competition']),location:z.string().max(300),notes:note,createdBy:z.enum(['coach','athlete'])}).refine(e=>e.start<=e.end,'Koniec wydarzenia musi przypadać po początku');
export const exerciseNoteSchema=z.object({id,profileId:id,exerciseId:id,notes:note});
export const stateSchema = z.object({version:z.literal(1),catalogVersion:z.number().int().optional(),profiles:z.array(profileSchema).min(1).max(100),exercises:z.array(exerciseSchema).max(1000),templates:z.array(templateSchema).max(200),workouts:z.array(workoutSchema).max(3000),fatigue:z.array(fatigueSchema).max(6000),wellness:z.array(wellnessSchema).max(18000).default([]),periods:z.array(periodSchema).max(500),events:z.array(eventSchema).default([]),exerciseNotes:z.array(exerciseNoteSchema).default([])}).superRefine((s,ctx)=>{
 const p=new Set(s.profiles.map(x=>x.id));for(const [key,arr] of Object.entries(s)){if(Array.isArray(arr)&&new Set(arr.map(x=>x.id)).size!==arr.length)ctx.addIssue({code:'custom',message:'Powtórzony identyfikator: '+key});}
 for(const x of [...s.workouts,...s.fatigue,...s.wellness,...s.periods,...s.events,...s.exerciseNotes])if(!p.has(x.profileId))ctx.addIssue({code:'custom',message:'Nieznany profil'});
 if(new Set(s.wellness.map(x=>x.profileId+':'+x.date+':'+x.slot)).size!==s.wellness.length)ctx.addIssue({code:'custom',message:'Jeden zapis samopoczucia na porę dnia i osobę.'});
 if(new Set(s.exerciseNotes.map(x=>x.profileId+':'+x.exerciseId)).size!==s.exerciseNotes.length)ctx.addIssue({code:'custom',message:'Jedna notatka do ćwiczenia na osobę'});
 for(const x of s.periods){if(!x.parentId)continue;const parent=s.periods.find(p=>p.id===x.parentId);const expected=x.level==='micro'?'meso':x.level==='meso'?'macro':null;if(!parent||parent.profileId!==x.profileId||parent.level!==expected||x.start<parent.start||x.end>parent.end)ctx.addIssue({code:'custom',message:'Cykl musi mieścić się w nadrzędnym cyklu tej samej osoby'});}
 if(new Set(s.fatigue.map(x=>x.profileId+':'+x.date)).size!==s.fatigue.length)ctx.addIssue({code:'custom',message:'Jeden pomiar zmęczenia na dzień'});
 for(const x of s.profiles)if(x.warmupId&&!s.templates.some(t=>t.id===x.warmupId&&t.section==='warmup'))ctx.addIssue({code:'custom',message:'Nieznana rozgrzewka'});
 for(const w of s.workouts){const items=Object.values(w.sections).flat();if(new Set(items.map(x=>x.id)).size!==items.length)ctx.addIssue({code:'custom',message:'Powtórzone ćwiczenie w sesji'});if(w.status==='completed'&&!items.some(x=>x.actual))ctx.addIssue({code:'custom',message:'Zapisz wykonanie przynajmniej jednego ćwiczenia'});}
});
export type Exercise=z.infer<typeof exerciseSchema>; export type Dose=z.infer<typeof doseSchema>; export type Item=z.infer<typeof itemSchema>; export type Workout=z.infer<typeof workoutSchema>; export type Template=z.infer<typeof templateSchema>; export type Profile=z.infer<typeof profileSchema>; export type Fatigue=z.infer<typeof fatigueSchema>; export type Period=z.infer<typeof periodSchema>; export type State=z.infer<typeof stateSchema>;
export type CalendarEvent=z.infer<typeof eventSchema>;export type ExerciseNote=z.infer<typeof exerciseNoteSchema>;
export const uid=()=>crypto.randomUUID(); export const clone=<T,>(v:T):T=>JSON.parse(JSON.stringify(v));
export function localDay(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export function addDays(day:string,n:number){const d=new Date(day+'T12:00:00');d.setDate(d.getDate()+n);return localDay(d);}
export function monday(day:string){return addDays(day,-((new Date(day+'T12:00:00').getDay()+6)%7));}
export function valueOf(d:Dose,m:Metric){return d.sets*d.quantity*(m==='kg'?d.kg:1);}
export function summarize(workouts:Workout[],mode:'planned'|'actual',metric:Metric){const out=Object.fromEntries(Object.keys(muscles).map(k=>[k,0])) as Record<Muscle,number>;let total=0,unassigned=0;for(const w of workouts){if(w.status==='skipped'||mode==='actual'&&w.status!=='completed')continue;for(const i of Object.values(w.sections).flat()){const d=i[mode];if(!d||i.exercise.metric!==metric)continue;const v=valueOf(d,metric);total+=v;if(!i.exercise.shares.length)unassigned+=v;for(const a of i.exercise.shares)out[a.muscle]+=v*a.weight;}}return {total,muscles:out,unassigned};}
export function summarizeSets(workouts:Workout[],mode:'planned'|'actual',weighted=true){const out=Object.fromEntries(Object.keys(muscles).map(k=>[k,0])) as Record<Muscle,number>;let total=0,unassigned=0;for(const w of workouts){if(w.status==='skipped'||mode==='actual'&&w.status!=='completed')continue;for(const i of Object.values(w.sections).flat()){const d=i[mode];if(!d||i.exercise.category!=='strength'||inferExerciseTypes(i.exercise).every(t=>t==='mobility'||t==='stretching'))continue;total+=d.sets;if(!i.exercise.shares.length)unassigned+=d.sets;for(const a of i.exercise.shares)out[a.muscle]+=d.sets*(weighted?a.weight:a.weight>0?1:0);}}return{total,muscles:out,unassigned};}
export function copyWeek(s:State,profileId:string,from:string,to:string){const start=monday(from),target=monday(to);if(start===target)throw Error('Wybierz inny tydzień docelowy');const delta=Math.round((Date.parse(target+'T12:00:00Z')-Date.parse(start+'T12:00:00Z'))/86400000);const copies=s.workouts.filter(w=>w.profileId===profileId&&w.date>=start&&w.date<=addDays(start,6)).map(w=>({...clone(w),id:uid(),date:addDays(w.date,delta),status:'planned' as const,actualMinutes:null,rpe:null,athleteNotes:'',sections:Object.fromEntries(Object.entries(w.sections).map(([k,items])=>[k,items.map(i=>({...clone(i),id:uid(),actual:null,athleteNotes:''}))])) as Workout['sections']}));return{...s,workouts:[...s.workouts,...copies]};}
export function makeItem(e:Exercise):Item{return {id:uid(),exercise:clone(e),planned:{sets:1,quantity:e.metric==='meters'?100:e.metric==='minutes'?5:10,kg:0},actual:null};}
export function newWorkout(profile:Profile,templates:Template[],date=localDay()):Workout{return {id:uid(),profileId:profile.id,name:'',date,time:'18:00',category:'strength',status:'planned',duration:60,actualMinutes:null,rpe:null,notes:'',sections:{warmup:(templates.find(t=>t.id===profile.warmupId)?.items||[]).map(i=>({...clone(i),id:uid(),actual:null})),main:[],cooldown:[]}};}
export function sheetSafe(v:unknown){return typeof v==='string'&&/^[\s]*[=+\-@]/.test(v)?"'"+v:v??'';}
export function exportRows(s:State,profileId:string){
 const p=s.profiles.find(x=>x.id===profileId);if(!p)throw Error('Nie znaleziono osoby');
 const rows:unknown[][]=[['Rodzaj wpisu','Osoba','Data','Trening / okres','Status / faza','Sekcja','Ćwiczenie','Jednostka','Serie plan','Ilość plan','kg plan','Objętość plan','Serie wykonane','Ilość wykonana','kg wykonane','Objętość wykonana','Zmęczenie 0–10','RPE sesji','Czas wykonany min','Koniec okresu','Notatki','Udziały mięśniowe','Film','ID wpisu']];
 for(const w of s.workouts.filter(x=>x.profileId===profileId).sort((a,b)=>a.date.localeCompare(b.date))){
  const items=Object.entries(w.sections).flatMap(([sec,arr])=>arr.map(i=>({sec,i})));
  if(!items.length)rows.push(['trening',p.name,w.date,w.name,w.status,'','','','','','','','','','','','',w.status==='completed'?w.rpe:null,w.status==='completed'?w.actualMinutes:null,'',[w.notes,w.athleteNotes].filter(Boolean).join(' | '),'','',w.id]);
  items.forEach(({sec,i},index)=>{const actual=w.status==='completed'?i.actual:null;rows.push(['trening',p.name,w.date,w.name,w.status,sections[sec as Section],i.exercise.name,metrics[i.exercise.metric],i.planned.sets,i.planned.quantity,i.planned.kg,valueOf(i.planned,i.exercise.metric),actual?.sets,actual?.quantity,actual?.kg,actual?valueOf(actual,i.exercise.metric):null,'',index===0&&w.status==='completed'?w.rpe:null,index===0&&w.status==='completed'?w.actualMinutes:null,'',[w.notes,w.athleteNotes&&'Zawodnik: '+w.athleteNotes,i.athleteNotes&&'Ćwiczenie: '+i.athleteNotes].filter(Boolean).join(' | '),i.exercise.shares.map(a=>`${muscles[a.muscle]} ${Math.round(a.weight*100)}%`).join('; '),i.exercise.video,w.id]);});
 }
 for(const f of s.fatigue.filter(x=>x.profileId===profileId))rows.push(['zmęczenie',p.name,f.date,'','','','','','','','','','','','','',f.value,'','','',f.notes,'','',f.id]);
 for(const w of s.wellness.filter(x=>x.profileId===profileId)){const row:unknown[]=Array(24).fill('');row[0]='samopoczucie';row[1]=p.name;row[2]=w.date;row[3]=slotNames[w.slot].pl;row[20]=[wellnessText(w.answers),w.notes,w.recordedBy==='coach'?'Wpis trenera':'Wpis zawodnika'].filter(Boolean).join(' | ');row[23]=w.id;rows.push(row);}
 for(const x of s.periods.filter(x=>x.profileId===profileId))rows.push(['okres',p.name,x.start,x.name,x.phase,'','','','','','','','','','','','','','',x.end,x.goal,'','',x.id]);
 for(const e of s.events.filter(x=>x.profileId===profileId)){const row:unknown[]=Array(24).fill('');row[0]='wydarzenie';row[1]=p.name;row[2]=e.start;row[3]=e.title;row[4]=e.kind;row[19]=e.end;row[20]=[e.time,e.location,e.notes,e.createdBy].filter(Boolean).join(' | ');row[23]=e.id;rows.push(row);}
 for(const n of s.exerciseNotes.filter(x=>x.profileId===profileId)){const row:unknown[]=Array(24).fill('');row[0]='notatka ćwiczenia';row[1]=p.name;row[6]=s.exercises.find(e=>e.id===n.exerciseId)?.name||n.exerciseId;row[20]=n.notes;row[23]=n.id;rows.push(row);}
 return rows.map(row=>row.map(sheetSafe));
}
