/** Original bilingual coaching notes. External references remain on their publishers' sites. */
export type Bilingual = { pl: string; en: string };
export type ArticleTopic = 'strength' | 'running' | 'conditioning' | 'throwing' | 'recovery' | 'periodization';
export type ResearchMuscle = 'quads' | 'hamstrings' | 'glutes' | 'calves' | 'lats' | 'upper_back' | 'lower_back' | 'chest' | 'shoulders' | 'biceps' | 'triceps' | 'forearms' | 'abs' | 'obliques' | 'adductors' | 'abductors' | 'hip_flexors';
export type ResearchArticle = { id: string; title: Bilingual; topic: ArticleTopic; author: string; source: string; url: string; summary: Bilingual };
export type ExerciseGuidance = { aliases: string[]; cues: Bilingual; variants: Bilingual; sourceUrls: string[]; muscles: { muscle: ResearchMuscle; role: 'primary' | 'secondary' }[] };
const bi = (pl: string, en: string): Bilingual => ({ pl, en });
const NSCA = 'https://www.nsca.com/education/articles/';
const UAP = 'https://www.theuap.com/blog/';
const ACE = 'https://www.acefitness.org/resources/everyone/exercise-library/';
const NASM = 'https://www.nasm.org/resource-center/exercise-library/';
export const researchVerifiedOn = '2026-10-03';
export const researchSourceUrls = {
  cycles: NSCA + 'kinetic-select/hierarchical-structure-of-periodization-cycles/',
  seasons: NSCA + 'kinetic-select/application-of-program-design-to-training-seasons/',
  patterns: NSCA + 'ptq/teaching-resistance-training-movement-patterns/',
  sprint: NSCA + 'kinetic-select/sprinting-mechanics-and-technique/',
  deceleration: NSCA + 'kinetic-select/effective-deceleration-technique-for-court-and-field-sports/',
  agility: NSCA + 'kinetic-select/transfer-of-training-for-agility/',
  speed: NSCA + 'kinetic-select/factors-determining-agility-speed/',
  endurance: NSCA + 'kinetic-select/anaerobic-and-muscle-endurance-development/',
  conditioning: UAP + 'how-to-get-in-shape-fast-for-your-ultimate-season',
  plyometrics: UAP + 'sample-plyometric-workout',
  load: 'https://pubmed.ncbi.nlm.nih.gov/28463642/',
  sleep: 'https://pubmed.ncbi.nlm.nih.gov/33144349/',
  resistance: 'https://acsm.org/resistance-training-guidelines-update-2026/',
};
const article = (id: string, topic: ArticleTopic, pl: string, en: string, author: string, source: string, url: string, summaryPl: string, summaryEn: string): ResearchArticle => ({ id, topic, title: bi(pl, en), author, source, url, summary: bi(summaryPl, summaryEn) });

export const articles: ResearchArticle[] = [
  article('acsm-2026', 'strength', 'Trening oporowy: zalecenia ACSM 2026', 'Resistance training: ACSM 2026 guidance', 'American College of Sports Medicine', 'ACSM', researchSourceUrls.resistance, 'Aktualizacja zaleceń dla zdrowych dorosłych: regularność i dobór programu do celu.', 'Updated guidance for healthy adults: consistent training and programming that fits the goal.'),
  article('movement-patterns', 'strength', 'Jak uczyć podstawowych wzorców ruchu', 'Teaching fundamental movement patterns', 'Merrick Lincoln, Kaitlyn Ill, Matthew Ibrahim', 'NSCA · Personal Training Quarterly', researchSourceUrls.patterns, 'Praktyczna progresja przysiadu, zawiasu biodrowego oraz ćwiczeń pchania i przyciągania.', 'Practical progressions for squatting, hip hinging, pushing, and pulling.'),
  article('rdl-technique', 'strength', 'Martwy ciąg rumuński: technika', 'Romanian deadlift: technique', 'American Council on Exercise', 'ACE · Certified', 'https://www.acefitness.org/continuing-education/certified/may-2025/8865/the-ace-do-it-better-series-the-romanian-deadlift/', 'Nauka ruchu z biodra, kontrola sztangi i dobór zakresu ruchu.', 'Teaching the hip hinge, controlling the bar, and choosing movement range.'),
  article('single-joint', 'strength', 'Uginanie nóg i przywodzenie: rola ćwiczeń izolowanych', 'Leg curls and adduction: the role of isolation exercises', 'Andrew Vigotsky, Nick Tumminello', 'NSCA · Personal Training Quarterly', NSCA + 'ptq/are-the-seated-leg-extension-leg-curl-and-adduction-machine-exercises-non-functional-or-risky/', 'Dlaczego ćwiczenia na maszynach mogą uzupełniać ruchy wielostawowe.', 'Why machine exercises can complement compound movements.'),
  article('sprint-mechanics', 'running', 'Mechanika sprintu', 'Sprinting mechanics and technique', "NSCA's Guide to Program Design", 'NSCA · Kinetic Select', researchSourceUrls.sprint, 'Start, przyspieszenie, bieg z dużą prędkością i hamowanie wymagają odmiennych wskazówek.', 'Starting, accelerating, running at speed, and braking need different coaching cues.'),
  article('deceleration', 'running', 'Hamowanie w sportach boiskowych', 'Deceleration in court and field sports', 'Developing Speed', 'NSCA · Kinetic Select', researchSourceUrls.deceleration, 'Kontrola sił podczas hamowania przygotowuje do kolejnego przyspieszenia lub zmiany kierunku.', 'Managing braking forces prepares the athlete for reacceleration or a direction change.'),
  article('agility-transfer', 'running', 'Transfer treningu do zwinności', 'Transfer of training for agility', 'Developing Agility and Quickness', 'NSCA · Kinetic Select', researchSourceUrls.agility, 'Siła stanowi podstawę; zwroty i reakcje wymagają także praktyki ruchowej.', 'Strength provides a foundation; direction changes and reactions also need movement practice.'),
  article('agility-speed', 'running', 'Szybkość jako składnik zwinności', 'Speed as a component of agility', 'Developing Agility and Quickness', 'NSCA · Kinetic Select', researchSourceUrls.speed, 'Związek przyspieszenia, techniki biegu i wymagań sportów z częstymi zwrotami.', 'How acceleration and running technique relate to sports with frequent direction changes.'),
  article('ultimate-conditioning', 'conditioning', 'Powrót do wydolności przed sezonem ultimate', 'Preparing conditioning for your ultimate season', 'Melissa Witmer', 'The Ultimate Athlete Project', researchSourceUrls.conditioning, 'Propozycje stopniowego powrotu do pracy biegowej i zmieniania kierunku ruchu.', 'Coaching suggestions for a gradual return to running and multidirectional work.'),
  article('endurance-development', 'conditioning', 'Rozwój wytrzymałości mięśniowej i beztlenowej', 'Anaerobic and muscle endurance development', 'Developing Endurance', 'NSCA · Kinetic Select', researchSourceUrls.endurance, 'Rola długości wysiłku, odpoczynku i specyfiki zadania w treningu wydolności.', 'The role of effort duration, recovery, and task specificity in conditioning.'),
  article('five-training-changes', 'conditioning', 'Pięć zmian w treningu ultimate', 'Five changes to ultimate training', 'Melissa Witmer', 'The Ultimate Athlete Project', UAP + 'five-changes-to-revolutionize-your-training', 'Perspektywa trenerki: cele sesji, interwały i różnicowanie kierunków ruchu.', 'A coach’s perspective on session goals, intervals, and varying movement directions.'),
  article('plyometric-example', 'conditioning', 'Przykłady ćwiczeń skocznościowych', 'Examples of plyometric exercises', 'Melissa Witmer', 'The Ultimate Athlete Project', researchSourceUrls.plyometrics, 'Demonstracje skoków i liczenia kontaktów z podłożem; przykład do indywidualizacji.', 'Jump demonstrations and tracking ground contacts; an example to individualize.'),
  article('someflow-practice', 'throwing', 'Jak ćwiczyć rzuty', 'How to practice throwing', 'LT', 'Some Flow', 'https://someflow.substack.com/p/how-to-practice-throwing', 'Analiza praktyki rzutowej: zmienność, feedback i świadoma praca nad techniką.', 'Throwing-practice analysis: variability, feedback, and deliberate technique work.'),
  article('someflow-low-high', 'throwing', 'Rzut z niskiego punktu do wyższego celu', 'Throw low to high', 'LT', 'Some Flow', 'https://someflow.substack.com/p/throw-low-to-high', 'Przykłady wideo i analiza jednego wariantu trajektorii; opinia trenerska.', 'Video examples and analysis of one trajectory option; a coaching perspective.'),
  article('parts', 'throwing', 'Pięć aspektów rzutu dla handlera', 'Five throwing principles every handler should know', 'John McNaughton; Brett Matzuka', 'The Ultimate Athlete Project', UAP + 'throwing-principles-every-handler-should-know', 'Pivot, repertuar rzutów, wypuszczenie dysku, trajektoria i prędkość jako cele praktyki.', 'Pivoting, throw selection, release, trajectory, and speed as practice goals.'),
  article('variable-throws', 'throwing', 'Więcej zmienności w praktyce rzutów', 'One step to better throwing practice', 'The Ultimate Athlete Project / Ulty Results', 'The Ultimate Athlete Project', UAP + 'one-step-to-better-throwing-practice', 'Jak zmieniać kolejność i warunki prób, aby przygotowywać rzuty do gry.', 'How varying trial order and conditions can prepare throwing skills for play.'),
  article('sleep-consensus', 'recovery', 'Sen zawodnika: konsensus ekspertów', 'Sleep and the athlete: expert consensus', 'Neil P. Walsh i współautorzy / et al.', 'British Journal of Sports Medicine · PubMed', researchSourceUrls.sleep, 'Sen, podróże i rozkład treningów; zalecenia wymagają indywidualizacji.', 'Sleep, travel, and training schedules; recommendations need individualization.'),
  article('load-consensus', 'recovery', 'Monitorowanie obciążeń zawodnika', 'Monitoring athlete training loads', 'Pitre C. Bourdon i współautorzy / et al.', 'International Journal of Sports Physiology and Performance · PubMed', researchSourceUrls.load, 'Rozróżnia pracę zewnętrzną od odpowiedzi organizmu i opisuje monitorowanie w kontekście.', 'Distinguishes external work from the athlete’s response and contextual monitoring.'),
  article('ioc-load', 'recovery', 'Obciążenie i ryzyko urazu: konsensus MKOl', 'Load and injury risk: IOC consensus', 'Tor-Oskar Soligard i współautorzy / et al.', 'British Journal of Sports Medicine', 'https://doi.org/10.1136/bjsports-2016-096581', 'Kontekst treningu, startów i regeneracji; ryzyko urazu ma wiele przyczyn.', 'Training, competition, and recovery context; injury risk has multiple causes.'),
  article('plyometric-progression', 'recovery', 'Progresja skoków i kontrola objętości', 'Plyometric progression and volume management', 'Melissa Witmer', 'The Ultimate Athlete Project', UAP + 'plyometrics-3-mistakes-that-increase-your-risk-of-injury', 'Gotowość do lądowania i stopniowanie trudności; dawkę dobiera się do osoby.', 'Landing readiness and progressive difficulty; the dose should suit the athlete.'),
  article('cycle-hierarchy', 'periodization', 'Makro-, mezo- i mikrocykle', 'Macrocycles, mesocycles, and microcycles', 'Developing Power', 'NSCA · Kinetic Select', researchSourceUrls.cycles, 'Hierarchia planu: od długiego celu do bloków, tygodni i sesji.', 'A planning hierarchy from longer-term goals to blocks, weeks, and sessions.'),
  article('training-seasons', 'periodization', 'Projektowanie treningu w sezonie', 'Program design across training seasons', 'Essentials of Strength Training and Conditioning', 'NSCA · Kinetic Select', researchSourceUrls.seasons, 'Zmiana priorytetów między przygotowaniem, startami i aktywną regeneracją.', 'Changing priorities across preparation, competition, and active recovery.'),
  article('planning-process', 'periodization', 'Kroki układania planu okresowego', 'Steps in the periodization planning process', 'Margaret T. Jones', 'Human Kinetics · NSCA’s Guide to Program Design', 'https://us.humankinetics.com/blogs/excerpt/basic-steps-in-the-periodization-training-process', 'Ustalanie celów i kalendarza przed doborem mniejszych jednostek treningowych.', 'Establishing goals and the calendar before choosing smaller training units.'),
  article('uap-seasons', 'periodization', 'Plan sezonu ultimate: przykład trenerski', 'An ultimate season plan: a coaching example', 'Melissa Witmer / The Ultimate Athlete Project', 'The Ultimate Athlete Project', 'https://www.theuap.com/strength-and-conditioning', 'Opis faz programu ultimate, od przygotowania siłowego do startów i taperu.', 'An overview of ultimate programming from strength preparation to competition and tapering.'),
];

export const cycleEducation = {
  intro: bi('Wielkość cyklu określa skalę planu; faza określa jego cel. Przygotowanie, starty i okres przejściowy mogą należeć do tego samego makrocyklu.', 'Cycle size describes the scale of a plan; a phase describes its purpose. Preparation, competition, and transition can belong to one macrocycle.'),
  macro: { title: bi('Makrocykl', 'Macrocycle'), description: bi('Plan prowadzący do głównego celu lub okresu startowego; zwykle obejmuje miesiące. Roczny plan może zawierać więcej niż jeden makrocykl.', 'A plan leading to a main goal or competition period, usually spanning months. An annual plan can contain more than one macrocycle.'), sourceUrls: [researchSourceUrls.cycles] },
  meso: { title: bi('Mezocykl', 'Mesocycle'), description: bi('Blok kilku mikrocykli ze wspólnym priorytetem, np. siłą lub przygotowaniem do powtarzanych sprintów. Długość dobiera się do kalendarza i odpowiedzi zawodnika.', 'A block of several microcycles with a shared priority, such as strength or repeated-sprint preparation. Its length follows the calendar and athlete response.'), sourceUrls: [researchSourceUrls.cycles] },
  micro: { title: bi('Mikrocykl', 'Microcycle'), description: bi('Krótka sekwencja sesji i odpoczynku, często tydzień. Może mieć inną długość, gdy wymaga tego turniej, podróż lub harmonogram zespołu.', 'A short sequence of sessions and recovery, often one week. Tournament, travel, or team schedules may call for another length.'), sourceUrls: [researchSourceUrls.cycles] },
  phases: [
    { id: 'preparation', title: bi('Przygotowanie', 'Preparation'), description: bi('Buduj bazę i rozwijaj cechy potrzebne w ultimate; stopniowo zwiększaj specyfikę treningu.', 'Build a foundation and the qualities needed for ultimate; gradually increase training specificity.') },
    { id: 'competition', title: bi('Starty', 'Competition'), description: bi('Utrzymuj wypracowane cechy i planuj trening wokół meczów. Taper przed ważnym startem ma ograniczyć zmęczenie.', 'Maintain developed qualities and plan around matches. A taper before a key event aims to reduce fatigue.') },
    { id: 'transition', title: bi('Okres przejściowy', 'Transition'), description: bi('Zaplanuj mniej obciążającą aktywność i regenerację przed kolejnym cyklem.', 'Plan lower-load activity and recovery before the next cycle.') },
  ],
  naming: bi('„Minicykl” nie jest tutaj dodatkowym standardowym poziomem. Krótkie bloki można nazywać własną etykietą i przypisać do mikrocyklu.', '“Minicycle” is not an additional standard level here. Short blocks can have a custom label within a microcycle.'),
  sourceUrls: [researchSourceUrls.cycles, researchSourceUrls.seasons],
};

export const muscleEducation = {
  title: bi('Jak czytać mapę mięśni', 'How to read the muscle map'),
  description: bi('Mapa pokazuje przypisane do regionów wykonanie w wybranej jednostce. To szacunek planistyczny, a nie pomiar siły mięśnia, zmęczenia, aktywacji EMG ani ryzyka urazu.', 'The map shows work attributed to regions in the selected unit. It is a planning estimate, not a measurement of muscle force, fatigue, EMG activation, or injury risk.'),
  units: bi('Porównuj kg × powtórzenia z tą samą miarą. Metry, minuty, rzuty, kontakty skokowe i serie zapisuj osobno. Łączny czas × RPE opisuje odczuwane obciążenie całej sesji, nie konkretnego mięśnia.', 'Compare kg × repetitions with the same measure. Keep metres, minutes, throws, jump contacts, and sets separate. Duration × RPE describes perceived whole-session load, not a specific muscle.'),
  sets: bi('Seria robocza jest oddzielnym wskaźnikiem. Sam tonaż nie uwzględnia zakresu ruchu, tempa, wysiłku ani pracy ekscentrycznej. Serii na jedną stronę nie zamieniaj automatycznie na dwie serie dla całej grupy.', 'A working set is a separate indicator. Volume load alone misses range of motion, tempo, effort, and eccentric work. Do not automatically turn one set per side into two sets for the whole group.'),
  attribution: bi('Główne i pomocnicze mięśnie to jakościowe przypisania ruchu. Udziały ustala trener dla wariantu ćwiczenia; procenty w aplikacji są umową do rozdziału wyniku, a nie proporcjami fizjologicznymi.', 'Primary and secondary muscles are qualitative movement attributions. Coaches configure each exercise variant; app percentages are accounting choices, not physiological proportions.'),
  targets: bi('Cele tygodniowe dobieraj do osoby, historii treningu i fazy sezonu. Kolor oznacza realizację wybranego celu. Czerwony nie jest uniwersalną granicą bezpieczeństwa, a zielony nie gwarantuje regeneracji.', 'Set weekly targets for the athlete, training history, and season phase. Colour represents progress against a chosen target. Red is not a universal safety limit, and green does not guarantee recovery.'),
  coverage: bi('Brak koloru oznacza brak przypisanych danych, nie brak pracy mięśnia. Biegi, rzuty i stabilizacja angażują więcej tkanek, niż można pokazać na uproszczonej mapie.', 'No colour means no attributed data, not no muscle work. Running, throwing, and stabilization involve more tissues than a simplified map can show.'),
  groups: [
    { id: 'quads', name: bi('Czworogłowe uda', 'Quadriceps'), anatomy: bi('Przód uda; prostowanie kolana.', 'Front thigh; knee extension.') },
    { id: 'hamstrings', name: bi('Mięśnie kulszowo-goleniowe', 'Hamstrings'), anatomy: bi('Tył uda; zginanie kolana i udział w prostowaniu biodra.', 'Posterior thigh; knee flexion and contribution to hip extension.') },
    { id: 'glutes', name: bi('Pośladkowy wielki', 'Gluteus maximus'), anatomy: bi('Prostowanie biodra. Odwodziciele mają osobny region.', 'Hip extension. Hip abductors have their own region.') },
    { id: 'calves', name: bi('Łydki', 'Calves'), anatomy: bi('Brzuchaty i płaszczkowaty; zgięcie podeszwowe stopy.', 'Gastrocnemius and soleus; ankle plantarflexion.') },
    { id: 'adductors', name: bi('Przywodziciele biodra', 'Hip adductors'), anatomy: bi('Przyśrodkowa część uda; przywodzenie i udział w stabilizacji biodra.', 'Medial thigh; hip adduction and stabilization.') },
    { id: 'abductors', name: bi('Odwodziciele biodra', 'Hip abductors'), anatomy: bi('M.in. pośladkowy średni i mały; odwodzenie i kontrola miednicy.', 'Including gluteus medius and minimus; hip abduction and pelvic control.') },
    { id: 'hip_flexors', name: bi('Zginacze biodra', 'Hip flexors'), anatomy: bi('M.in. biodrowo-lędźwiowy. Część mięśni leży głęboko i nie ma widocznej powierzchni.', 'Including iliopsoas. Some muscles lie deep and have no visible surface region.') },
    { id: 'lats', name: bi('Najszerszy grzbietu', 'Latissimus dorsi'), anatomy: bi('Przyciąganie ramienia; tylna i boczna część tułowia.', 'Pulling the upper arm; posterior and lateral trunk.') },
    { id: 'upper_back', name: bi('Górna część pleców', 'Upper back'), anatomy: bi('Region obejmujący m.in. czworoboczny i równoległoboczne; ruch i kontrola łopatki.', 'A region including trapezius and rhomboids; scapular movement and control.') },
    { id: 'lower_back', name: bi('Prostowniki grzbietu', 'Spinal extensors'), anatomy: bi('Region lędźwiowy i mięśnie przykręgosłupowe; kontrola tułowia.', 'Lumbar region and spinal muscles; trunk control.') },
    { id: 'chest', name: bi('Mięśnie piersiowe', 'Pectorals'), anatomy: bi('Przód klatki piersiowej; udział w ruchach pchania.', 'Front chest; contribution to pushing movements.') },
    { id: 'shoulders', name: bi('Barki', 'Shoulders'), anatomy: bi('Uproszczony region naramiennych; stożek rotatorów nie jest osobnym pomiarem.', 'A simplified deltoid region; rotator-cuff load is not separately measured.') },
    { id: 'biceps', name: bi('Zginacze łokcia', 'Elbow flexors'), anatomy: bi('Region bicepsa; obejmuje także pracę innych zginaczy łokcia.', 'Biceps region, also representing other elbow flexors.') },
    { id: 'triceps', name: bi('Triceps', 'Triceps'), anatomy: bi('Tył ramienia; prostowanie łokcia.', 'Posterior upper arm; elbow extension.') },
    { id: 'forearms', name: bi('Przedramiona', 'Forearms'), anatomy: bi('Chwyt oraz ruch i stabilizacja nadgarstka.', 'Grip and wrist movement and stabilization.') },
    { id: 'abs', name: bi('Przód brzucha', 'Anterior abdominals'), anatomy: bi('Uproszczony region brzucha; także funkcja stabilizacji.', 'A simplified anterior abdominal region; includes stabilization.') },
    { id: 'obliques', name: bi('Skośne brzucha', 'Obliques'), anatomy: bi('Boki tułowia; rotacja i opór przeciw rotacji lub zgięciu bocznemu.', 'Lateral trunk; rotation and resistance to rotation or lateral flexion.') },
  ],
  sourceUrls: [researchSourceUrls.load, 'https://doi.org/10.1136/bjsports-2016-096581', ACE, researchSourceUrls.resistance],
};

function guidance(aliases: string[], cuesPl: string, cuesEn: string, variantsPl: string, variantsEn: string, primary: ResearchMuscle[], secondary: ResearchMuscle[], sourceUrls: string[]): ExerciseGuidance {
  return { aliases, cues: bi(cuesPl, cuesEn), variants: bi(variantsPl, variantsEn), sourceUrls, muscles: [...primary.map(muscle => ({ muscle, role: 'primary' as const })), ...secondary.map(muscle => ({ muscle, role: 'secondary' as const }))] };
}

/** Attribution is an editable coaching starting point, not a measured contribution. */
export const exerciseGuidance: Record<string, ExerciseGuidance> = {
  'back-squat': guidance(['back squat', 'barbell squat', 'przysiad ze sztangą'], 'Napnij tułów, utrzymuj całą stopę na podłożu i prowadź kolana zgodnie z kierunkiem palców.', 'Brace the trunk, keep the whole foot grounded, and let knees follow the toes.', 'Przysiad przedni zmienia położenie obciążenia; pauza rozwija kontrolę. Dobierz głębokość do możliwości.', 'Front loading changes balance demands; a pause develops control. Choose an appropriate depth.', ['quads','glutes'], ['adductors','lower_back','abs'], [ACE+'11/back-squat/']),
  'front-squat': guidance(['front squat', 'przysiad przedni'], 'Utrzymaj obciążenie z przodu, tułów stabilny i kontrolowany ruch bioder oraz kolan.', 'Keep the load in front, a stable trunk, and controlled hip and knee movement.', 'Hantle ułatwiają dobór chwytu; sztanga wymaga wygodnej pozycji rack. Wariant przedni zwykle wymaga bardziej pionowego tułowia.', 'Dumbbells offer grip options; the barbell needs a comfortable rack. Front loading usually calls for a more upright trunk.', ['quads','glutes'], ['abs','upper_back','adductors'], [NASM+'goblet-squat']),
  'goblet-squat': guidance(['goblet squat','squat','przysiad goblet'], 'Trzymaj ciężar blisko klatki, usiądź między biodrami i wstań przez nacisk całej stopy.', 'Hold the weight close to the chest, descend between the hips, and stand through the whole foot.', 'Pauza uczy pozycji dolnej; ciężar z przodu pomaga ćwiczyć równowagę i kontrolę przysiadu.', 'A pause trains the bottom position; front loading helps practice balance and squat control.', ['quads','glutes'], ['adductors','abs'], [ACE+'362/goblet-squat/']),
  'deadlift': guidance(['deadlift','conventional deadlift','martwy ciąg'], 'Ustaw ciężar blisko stóp, napnij tułów i odpychaj podłoże. Biodra i barki unoszą się razem.', 'Set the load close to the feet, brace, and push the floor away. Hips and shoulders rise together.', 'Podwyższenie ciężaru skraca zakres; wariant rumuński przenosi akcent na zawias biodrowy.', 'Raising the load shortens the range; the Romanian variation emphasizes hip hinging.', ['glutes','hamstrings','quads'], ['lower_back','forearms','lats','abs'], [ACE+'6/deadlift/']),
  'trap-bar-deadlift': guidance(['trap bar deadlift','hex bar deadlift','martwy ciąg trap bar'], 'Stań centralnie, napnij tułów i wstań bez szarpania oraz odchylania pleców.', 'Stand centrally, brace, and rise without jerking or leaning back.', 'Wyższe uchwyty skracają zakres. Większe zgięcie kolan zmienia udział ruchu kolana względem biodra.', 'High handles shorten the range. Greater knee bend changes the balance of knee and hip motion.', ['quads','glutes'], ['hamstrings','lower_back','forearms','abs'], [NASM+'barbell-deadlift']),
  'romanian-deadlift': guidance(['rdl','romanian deadlift','martwy ciąg rumuński'], 'Cofaj biodra przy lekko ugiętych kolanach. Trzymaj ciężar blisko nóg i zakończ zejście przed utratą kontroli tułowia.', 'Send hips back with soft knees. Keep the load near the legs and stop before trunk control changes.', 'Wolniejsze opuszczanie rozwija kontrolę; zakres wynika z ruchu biodra, nie z konieczności dotknięcia podłogi.', 'Slower lowering develops control; range follows the hip hinge rather than the need to touch the floor.', ['hamstrings','glutes'], ['lower_back','adductors','forearms'], [NASM+'romanian-deadlift-barbell']),
  'single-leg-romanian-deadlift': guidance(['single leg rdl','single-leg romanian deadlift','rdl jednonóż'], 'Cofaj wolną nogę, utrzymuj miednicę możliwie równo i kontroluj stopę podporową.', 'Reach the free leg back, keep the pelvis level, and control the stance foot.', 'Podparcie ręką ogranicza wymagania równowagi; wariant kickstand ułatwia skupienie na sile biodra.', 'Hand support reduces balance demands; a kickstand stance makes hip strength easier to emphasize.', ['hamstrings','glutes'], ['abductors','abs','lower_back'], [NASM+'romanian-deadlift-barbell']),
  'bulgarian-split-squat': guidance(['bulgarian split squat','rear foot elevated split squat','przysiad bułgarski'], 'Ustaw stabilnie przednią stopę i opuszczaj biodra bez skręcania miednicy. Tylna noga pomaga utrzymać pozycję.', 'Plant the front foot and lower without rotating the pelvis. The rear leg helps maintain position.', 'Lekki skłon może zwiększać wymagania biodra; bardziej pionowy tułów zmienia akcent. Podparcie pomaga równowadze.', 'A slight forward lean can increase hip demands; a more upright trunk changes emphasis. Support helps balance.', ['quads','glutes'], ['adductors','abductors','abs'], [ACE+'366/bulgarian-split-squat/']),
  'reverse-lunge': guidance(['reverse lunge','lunge','wykrok w tył','zakrok'], 'Zrób kontrolowany krok w tył i wróć, naciskając przednią stopą. Utrzymuj kolano w kierunku palców.', 'Step back with control and return through the front foot. Let the knee follow the toes.', 'Dłuższy krok zmienia wymagania biodra; krótszy zmienia zgięcie kolana. Nie traktuj długości kroku jako izolacji mięśnia.', 'A longer step changes hip demands; a shorter step changes knee bend. Step length does not isolate a muscle.', ['quads','glutes'], ['adductors','abductors','abs'], [ACE+'366/bulgarian-split-squat/']),
  'lateral-lunge': guidance(['lateral lunge','lateral','wykrok boczny'], 'Przenieś biodra nad nogę pracującą, utrzymując stopę na podłożu. Drugą nogę wydłużaj bez zapadania tułowia.', 'Move the hips over the working leg with the foot grounded. Lengthen the other leg without collapsing the trunk.', 'Płytszy zakres ułatwia kontrolę; dłuższy krok zwiększa wymagania w płaszczyźnie bocznej.', 'A shallower range helps control; a longer step increases lateral-plane demands.', ['quads','glutes','adductors'], ['abductors','abs'], [ACE+'364/lateral-lunge/']),
  'step-up': guidance(['step up','step-up','wejście na podest'], 'Postaw całą stopę na podeście. Wstań głównie nogą na podeście i zejdź pod kontrolą.', 'Place the whole foot on the step. Rise mainly through that leg and lower under control.', 'Wyższy podest zwiększa zakres biodra i kolana; niższy ułatwia kontrolę bez odbicia tylną nogą.', 'A higher step increases hip and knee range; a lower one helps control without pushing off the rear leg.', ['quads','glutes'], ['abductors','adductors','abs'], [ACE+'28/step-up/']),
  'hip-thrust': guidance(['hip thrust','glute bridge','hip bridge','unoszenie bioder','most biodrowy'], 'Unieś biodra bez wyginania lędźwi. Zakończ ruch przy stabilnych żebrach i miednicy.', 'Extend the hips without arching the lower back. Finish with ribs and pelvis controlled.', 'Most na podłodze skraca zakres; wariant jednonóż zwiększa wymagania kontroli miednicy.', 'A floor bridge shortens the range; a single-leg version adds pelvic-control demands.', ['glutes'], ['hamstrings','abs'], [ACE+'318/hip-bridge/']),
  'leg-curl': guidance(['leg curl','hamstring curl','uginanie nóg'], 'Zginaj kolano bez unoszenia bioder i opuszczaj ciężar spokojnie. Dopasuj oś maszyny do kolana.', 'Flex the knee without lifting the hips and lower smoothly. Align the machine axis with the knee.', 'Wariant siedzący zmienia ustawienie biodra; jednonóż pozwala śledzić każdą stronę osobno.', 'The seated version changes hip position; single-leg work lets you track sides separately.', ['hamstrings'], ['calves'], [NASM+'lying-leg-curl']),
  'nordic-hamstring-curl': guidance(['nordic hamstring curl','nordic curl','nordic','nordic hamstring'], 'Zabezpiecz stopy, utrzymuj linię bioder i tułowia. Opuszczaj się tylko tak daleko, jak kontrolujesz; podeprzyj rękami.', 'Secure the feet and maintain hip–trunk alignment. Lower only as far as controlled; catch yourself with the hands.', 'Guma lub krótszy zakres ułatwia kontrolowane opuszczanie. Wprowadzaj objętość stopniowo.', 'A band or shorter range helps controlled lowering. Introduce volume gradually.', ['hamstrings'], ['glutes','abs'], [NSCA+'nsca-coach/exercise-progressions-for-resuming-strength-training-following-posterior-chain-muscle-injury/']),
  'copenhagen-adduction': guidance(['copenhagen plank','copenhagen adduction','copenhagen'], 'Podeprzyj górną nogę i unieś miednicę, zachowując linię tułowia. Zacznij od krótkiej dźwigni.', 'Support the upper leg and lift the pelvis with a straight trunk. Start with a short lever.', 'Podparcie kolana zmniejsza trudność; podparcie stopy wydłuża dźwignię i zwiększa wymagania przywodzicieli.', 'Knee support reduces difficulty; foot support lengthens the lever and increases adductor demands.', ['adductors'], ['obliques','shoulders'], [NSCA+'ptq/are-the-seated-leg-extension-leg-curl-and-adduction-machine-exercises-non-functional-or-risky/']),
  'calf-raise': guidance(['calf raise','standing calf raise','calf','wspięcia na palce'], 'Unieś pięty bez kołysania i opuszczaj je pod kontrolą. Zachowaj stabilny nacisk przodostopia.', 'Raise the heels without rocking and lower under control. Maintain a stable forefoot.', 'Proste kolano bardziej angażuje brzuchaty łydki; zgięte zmienia akcent w stronę płaszczkowatego.', 'A straight knee emphasizes gastrocnemius more; a bent knee shifts emphasis toward soleus.', ['calves'], [], [ACE+'51/calf-raises/']),
  'bench-press': guidance(['bench press','chest press','wyciskanie leżąc'], 'Ustaw stabilnie stopy i łopatki. Kontroluj opuszczanie, utrzymując nadgarstek nad przedramieniem.', 'Set the feet and shoulder blades securely. Control the descent with wrists stacked over forearms.', 'Węższy chwyt zmienia wymagania tricepsa; hantle dają inne możliwości chwytu i niezależną pracę ramion.', 'A closer grip changes triceps demands; dumbbells offer grip choices and independent arm work.', ['chest','triceps'], ['shoulders'], [ACE+'5/chest-press/']),
  'push-up': guidance(['push up','push-up','pushup','pompki'], 'Utrzymuj linię tułowia i przesuwaj ciało jako całość. Dobierz ustawienie rąk do wygodnego ruchu barków.', 'Keep the trunk aligned and move the body as one unit. Choose hand placement that allows comfortable shoulder motion.', 'Ręce na podwyższeniu zmniejszają obciążenie; stopy na podwyższeniu zmieniają wymagania barków.', 'Elevating the hands reduces resistance; elevating the feet changes shoulder demands.', ['chest','triceps'], ['shoulders','abs'], [NASM+'push-up']),
  'overhead-press': guidance(['overhead press','shoulder press','press','wyciskanie nad głowę'], 'Napnij tułów i wyciskaj bez odchylania lędźwi. Pozwól łopatkom poruszać się z ramionami.', 'Brace and press without leaning back through the lower spine. Allow shoulder blades to move with the arms.', 'Pozycja siedząca ogranicza udział nóg; praca jednorącz zwiększa wymagania kontroli bocznej tułowia.', 'Seated pressing reduces leg involvement; one-arm work increases lateral trunk-control demands.', ['shoulders','triceps'], ['abs','upper_back'], [ACE+'186/seated-shoulder-press/']),
  'pull-up': guidance(['pull up','pull-up','chin-up','podciąganie'], 'Zacznij z kontrolowanego zwisu. Przyciągnij ciało bez bujania i opuść spokojnie.', 'Start from a controlled hang. Pull without swinging and lower smoothly.', 'Pomoc gumy lub maszyny zmniejsza opór; podchwyt zmienia ustawienie i wymagania zginaczy łokcia.', 'Band or machine assistance reduces resistance; an underhand grip changes elbow-flexor demands.', ['lats','biceps'], ['upper_back','forearms'], [NASM+'pull-up']),
  'barbell-row': guidance(['barbell row','bent over row','bent-over row','wiosłowanie sztangą'], 'Utrzymaj zawias biodrowy i stabilny tułów. Prowadź łokcie do tyłu bez podrzucania ciężaru.', 'Maintain the hinge and a stable trunk. Drive elbows back without throwing the load.', 'Podparcie klatki zmniejsza pracę stabilizacyjną lędźwi; tor łokcia zmienia akcent przyciągania.', 'Chest support reduces lumbar stabilization demands; elbow path changes pulling emphasis.', ['lats','upper_back'], ['biceps','forearms','lower_back'], [ACE+'12/bent-over-row/']),
  'single-arm-row': guidance(['single arm row','dumbbell row','row','wiosłowanie hantlem'], 'Podeprzyj tułów, przyciągaj łokieć i unikaj obracania całego ciała dla rozpędu.', 'Support the trunk, pull through the elbow, and avoid rotating the whole body for momentum.', 'Bez podparcia rośnie wymaganie kontroli tułowia; tor do biodra lub klatki zmienia akcent.', 'Removing support increases trunk-control demands; pulling toward hip or chest changes emphasis.', ['lats','upper_back'], ['biceps','forearms','obliques'], [ACE+'12/bent-over-row/']),
  'face-pull': guidance(['face pull','face-pull','przyciąganie liny do twarzy'], 'Przyciągaj linę do okolicy twarzy bez unoszenia żeber. Użyj obciążenia pozwalającego kontrolować łopatki.', 'Pull toward the face without flaring the ribs. Choose a load that allows scapular control.', 'Wysokość linki i rotacja ramienia zmieniają zadanie barku; większy ciężar nie zastępuje kontroli.', 'Cable height and arm rotation change the shoulder task; more weight does not replace control.', ['upper_back','shoulders'], ['biceps'], [NASM+'face-pull']),
  'biceps-curl': guidance(['biceps curl','bicep curl','uginanie ramion'], 'Zginaj łokcie bez zamachu tułowiem i kontroluj opuszczanie.', 'Flex the elbows without trunk swinging and control lowering.', 'Chwyt młotkowy zmienia udział zginaczy łokcia i przedramienia; podparcie ogranicza rozpęd.', 'A hammer grip changes elbow-flexor and forearm involvement; support limits momentum.', ['biceps'], ['forearms'], [ACE+'70/bicep-curl/']),
  'plank': guidance(['plank','podpór na przedramionach','deska'], 'Utrzymuj żebra nad miednicą i oddychaj, zachowując stabilną pozycję.', 'Keep ribs over the pelvis and breathe while maintaining position.', 'Podwyższenie rąk ułatwia; dłuższa dźwignia zwiększa wymagania przeciwdziałania wyprostowi tułowia.', 'Elevating the hands helps; a longer lever increases anti-extension demands.', ['abs'], ['obliques','shoulders','glutes'], [NASM+'plank']),
  'side-plank': guidance(['side plank','sideplank','podpór bokiem'], 'Ustaw łokieć pod barkiem i utrzymuj miednicę bez opadania oraz rotacji.', 'Stack the elbow under the shoulder and hold the pelvis without dropping or rotating.', 'Podparcie kolan skraca dźwignię; uniesienie górnej nogi dodaje pracę odwodzicieli biodra.', 'Knee support shortens the lever; lifting the top leg adds hip-abductor work.', ['obliques'], ['shoulders','abductors'], [NASM+'side-plank']),
  'dead-bug': guidance(['dead bug','deadbug','martwy robak'], 'Wydłużaj przeciwległe kończyny, zachowując stabilne żebra i miednicę. Oddychaj bez unoszenia lędźwi.', 'Extend opposite limbs with ribs and pelvis stable. Breathe without lifting the lower back.', 'Krótka dźwignia ułatwia kontrolę; prostowanie nogi zwiększa wymagania stabilizacji.', 'A short lever helps control; straightening the leg increases stabilization demands.', ['abs'], ['obliques','hip_flexors'], [NASM+'dead-bug']),
  'farmers-carry': guidance(['farmer carry','farmer’s carry','farmers carry','spacer farmera'], 'Idź z wyprostowanym tułowiem i stabilnym chwytem. Nie unoś barków dla podtrzymania ciężaru.', 'Walk with an upright trunk and steady grip. Avoid shrugging to hold the load.', 'Ciężar po jednej stronie zwiększa opór przeciw zgięciu bocznemu; dwa ciężary zmieniają wymagania chwytu.', 'A load on one side increases anti-lateral-flexion demands; two loads change grip demands.', ['forearms'], ['upper_back','abs','obliques'], [ACE+'359/farmer-s-carry/']),
  'box-jump': guidance(['box jump','box jumps','skok na skrzynię'], 'Odbij się i wyląduj stabilnie całą stopą. Zejdź ze skrzyni, zanim wykonasz kolejną próbę.', 'Take off and land steadily through the whole foot. Step down before the next attempt.', 'Niższa skrzynia ułatwia naukę. Jej wysokość nie mierzy wysokości wyskoku; nie zastępuj skoku podciąganiem kolan.', 'A lower box helps learning. Box height is not jump height; pulling knees up does not replace jumping.', ['quads','glutes','calves'], ['hamstrings','abs'], [NASM+'box-jumps']),
  'lateral-bound': guidance(['lateral bound','heiden bound','skater jump','skok boczny'], 'Odepchnij podłoże w bok i zatrzymaj stabilne lądowanie na jednej nodze.', 'Push sideways and hold a stable single-leg landing.', 'Pauza przy lądowaniu rozwija kontrolę; skoki ciągłe zmieniają wymagania reaktywności i kontaktów z podłożem.', 'Pausing develops landing control; continuous bounds change reactive and ground-contact demands.', ['glutes','quads','calves'], ['abductors','adductors','hamstrings'], [researchSourceUrls.plyometrics]),
  'acceleration-sprint': guidance(['acceleration sprint','acceleration','accel','przyspieszenia po prostej'], 'Odpychaj podłoże w tył i stopniowo prostuj sylwetkę. Kończ próbę kontrolowanym wyhamowaniem.', 'Push backward against the ground and rise gradually. Finish with controlled braking.', 'Krótki start akcentuje przyspieszenie; dłuższy odcinek pozwala osiągnąć większą prędkość.', 'Short starts emphasize acceleration; longer runs allow higher speed.', ['glutes','quads','hamstrings','calves'], ['hip_flexors','abs'], [researchSourceUrls.sprint]),
  'flying-sprint': guidance(['flying sprint','max velocity sprint','lotny sprint'], 'Rozpędzaj się stopniowo. Biegnij wysoko i swobodnie; zostaw miejsce na hamowanie.', 'Build speed gradually. Run tall and relaxed; leave space to brake.', 'Dłuższy rozbieg zmienia osiąganą prędkość; pełniejszy odpoczynek pomaga jakości szybkich prób.', 'A longer approach changes attained speed; fuller recovery supports fast-repetition quality.', ['hamstrings','glutes','calves'], ['quads','hip_flexors','abs'], [researchSourceUrls.sprint]),
  'shuttle-run': guidance(['shuttle run','shuttle','bieg wahadłowy'], 'Hamuj przed linią i odpychaj podłoże po zwrocie. Ćwicz zwroty w obie strony.', 'Brake before the line and push away after turning. Practice both turning sides.', 'Krótszy wahadłowy dystans dodaje zwroty; dłuższy dodaje odcinki szybszego biegu.', 'Shorter shuttles add turns; longer ones add faster running segments.', ['quads','glutes','calves'], ['hamstrings','adductors','abductors','abs'], [researchSourceUrls.deceleration]),
  'change-of-direction': guidance(['change of direction','cutting','cut','zmiana kierunku'], 'Obniż sylwetkę podczas hamowania i skieruj kolejne odepchnięcie ku nowemu celowi.', 'Lower during braking and direct the next push toward the new target.', 'Zaplanowany zwrot ćwiczy ruch; sygnał partnera dodaje percepcję i decyzję.', 'A planned cut trains movement; a partner cue adds perception and decision-making.', ['quads','glutes','calves'], ['hamstrings','adductors','abductors','obliques'], [researchSourceUrls.agility,researchSourceUrls.deceleration]),
  'lateral-shuffle': guidance(['lateral shuffle','shuffle','przemieszczanie bokiem'], 'Utrzymuj kontrolę bioder i odpychaj podłoże w bok. Dobierz kroki do tempa zadania.', 'Control the hips and push sideways. Match steps to the task speed.', 'Reakcja na partnera dodaje decyzję; krok krzyżowy jest innym rozwiązaniem dla większego dystansu.', 'Reacting to a partner adds decisions; crossover steps offer another option for longer distances.', ['abductors','adductors','quads'], ['glutes','calves','abs'], [researchSourceUrls.speed]),
  'easy-run': guidance(['easy run','continuous run','easy','bieg ciągły','spokojny bieg'], 'Wybierz spokojne tempo i naturalny krok. Zapisuj czas lub dystans oraz odczuwany wysiłek.', 'Choose an easy pace and natural stride. Record time or distance and perceived effort.', 'Marszobieg ułatwia powrót; krótkie przerwy zmieniają ciągły wysiłek w interwały.', 'Run–walk intervals help returning athletes; brief recoveries turn continuous work into intervals.', ['calves','quads','glutes'], ['hamstrings','hip_flexors','abs'], [researchSourceUrls.endurance]),
  'tempo-intervals': guidance(['tempo intervals','running intervals','interwały tempowe'], 'Utrzymuj zaplanowane tempo i odpoczynek. Zakończ serię, gdy cel tempa przestaje być osiągalny.', 'Maintain the planned pace and recovery. End the set when the pace goal cannot be met.', 'Zmiana długości pracy i odpoczynku zmienia cel wydolnościowy; tempo nie oznacza automatycznie sprintu.', 'Changing work and recovery duration changes conditioning emphasis; tempo does not automatically mean sprinting.', ['quads','glutes','calves'], ['hamstrings','hip_flexors'], [researchSourceUrls.conditioning]),
  'repeated-sprints': guidance(['repeated sprints','repeated sprint','powtarzane sprinty'], 'Zapisuj czasy prób i przerwy. Oddziel taki trening od sprintów wykonywanych z pełnym odpoczynkiem.', 'Record repetition times and recoveries. Distinguish this session from sprints with full recovery.', 'Krótsza przerwa zwiększa wymagania powtarzania wysiłku; dłuższa pomaga utrzymać prędkość.', 'Shorter recovery raises repeated-effort demands; longer recovery supports speed.', ['glutes','quads','hamstrings','calves'], ['hip_flexors','abs'], [researchSourceUrls.endurance]),
  'jump-rope': guidance(['jump rope','rope','skakanka'], 'Skacz nisko i rytmicznie, zachowując kontrolę lądowania i rozluźnione barki.', 'Jump low and rhythmically with controlled landings and relaxed shoulders.', 'Jednonóż zwiększa obciążenie pojedynczej nogi; dłuższy ciągły blok zmienia cel w stronę wydolności.', 'Single-leg work raises individual-leg demands; longer continuous blocks shift emphasis toward conditioning.', ['calves'], ['quads','forearms','shoulders'], [UAP+'plyometrics-3-mistakes-that-increase-your-risk-of-injury']),
  'stationary-bike': guidance(['stationary bike','bike','rower stacjonarny'], 'Ustaw siodło do wygodnego ruchu kolana i pedałuj płynnie. Zapisuj czas, opór i RPE.', 'Set the saddle for comfortable knee motion and pedal smoothly. Record duration, resistance, and RPE.', 'Większy opór zmienia siłę nacisku; interwały i jazda ciągła mają inne cele sesji.', 'Higher resistance changes pedal-force demands; intervals and continuous riding serve different session goals.', ['quads','glutes'], ['hamstrings','calves'], [researchSourceUrls.endurance]),
};

export function findExerciseGuidance(name: string): ExerciseGuidance | undefined {
  const normalize = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/ł/g,'l').replace(/[^a-z0-9]+/g, ' ').trim();
  const query = normalize(name);
  const entry = Object.entries(exerciseGuidance).find(([key, value]) => normalize(key) === query || value.aliases.some(alias => normalize(alias) === query));
  return entry?.[1];
}



