import { useState, type FormEvent } from 'react';
import type { Goal, GoalInput, GoalMetric, LocalSnapshot, SportId, TrainingType, Workout } from '../data/domain';
import { SPORTS, TRAINING_TYPES, isWellnessGoalMetric } from '../data/domain';
import type { LocalRepository } from '../data/repository';
import { addDays, exerciseVolumes, goalProgress, isCompletedHistory, today } from '../data/analytics';
import { dateLabel, Feedback, sportName, useAction } from './common';
import { Help } from './TrainingFields';
import { WellbeingTrends } from '../features/wellbeing/WellbeingTrends';
import { insightPeriod, insightRanges, completedSummary, sessionBuckets, type InsightRange } from '../features/progress/summary';
import { BotanicalBranch } from '../features/progress/BotanicalBranch';
import './wellness.css';
import { currentTranslator, useI18n } from '../i18n';
import { trainingTypeLabel } from '../i18n/labels';

type Props = { repository: LocalRepository; snapshot: LocalSnapshot; onChanged: () => Promise<void>; onWorkoutOpen?: (workout: Workout) => void; onWellnessOpen?: () => void };
const number = (n: number) => currentTranslator().n(n, 2);
const goalMetrics: readonly GoalMetric[] = ['count', 'minutes', 'activeDays', 'checkinDays', 'sleepAverageHours'];
export function ProgressView({ repository, snapshot, onChanged, onWorkoutOpen, onWellnessOpen }: Props) {
  const i18n = useI18n(), { t } = i18n;
  const shortDay = (day: string) => i18n.date(day, { day: '2-digit', month: '2-digit' });
  const signed = (value: number) => `${value > 0 ? '+' : ''}${number(value)}`;
  const [sport, setSport] = useState<SportId | ''>('');
  const [trainingType, setTrainingType] = useState<TrainingType | ''>('');
  const [anchor, setAnchor] = useState(today());
  const [range, setRange] = useState<InsightRange>('week');
  const [tab, setTab] = useState<'training' | 'wellbeing'>('training');
  const [editing, setEditing] = useState<Goal | null | undefined>(undefined);
  const [notice, setNotice] = useState('');
  const period = insightPeriod(anchor, range);
  const days = period.days;
  const totals = completedSummary(snapshot.workouts, period.start, period.end, sport, trainingType);
  const previous = completedSummary(snapshot.workouts, period.previousStart, period.previousEnd, sport, trainingType);
  const buckets = sessionBuckets(snapshot.workouts, period.start, period.end, sport, trainingType);
  const volumes = exerciseVolumes(snapshot.workouts, period.start, period.end, sport, trainingType);
  const max = Math.max(1, ...buckets.map(w => w.count));
  const completed = snapshot.workouts.filter(w => isCompletedHistory(w) && w.date >= period.start && w.date <= period.end && (!sport || w.sportId === sport) && (!trainingType || w.trainingType === trainingType));
  const leadingType = TRAINING_TYPES.map(type => ({ ...type, count: completed.filter(w => w.trainingType === type.id).length })).sort((a, b) => b.count - a.count)[0];
  const ratings = completed.filter(w => [w.postWorkout.aerobicFatigue, w.postWorkout.muscularFatigue, w.postWorkout.satisfaction, w.rpe].some(value => value !== null)).sort((a, b) => b.date.localeCompare(a.date) || (b.time ?? '').localeCompare(a.time ?? '') || b.id.localeCompare(a.id)).slice(0, 4);
  if (editing !== undefined) return <GoalForm key={editing?.id ?? 'new'} repository={repository} snapshot={snapshot} goal={editing} onClose={() => setEditing(undefined)} onSaved={async () => { setEditing(undefined); setNotice(currentTranslator().t('progress.goalSaved')); try { await onChanged(); } catch { setNotice(currentTranslator().t('progress.goalSavedRefreshFailed')); } }} />;
  return <div className="progress-view stack"><div className="page-heading"><div><h1>{t('progress.title')}</h1><p className="pv-period">{t('progress.periodLine', { start: dateLabel(period.start), end: dateLabel(period.end) })}</p></div></div>
    {notice && <p role="status" className="success">{notice}</p>}
    {!onWellnessOpen && <div className="pv-tabs" role="group" aria-label={t('progress.area')}><button aria-pressed={tab === 'training'} onClick={() => setTab('training')}>{t('progress.tabTraining')}</button><button aria-pressed={tab === 'wellbeing'} onClick={() => setTab('wellbeing')}>{t('progress.tabWellbeing')}</button></div>}
    {tab === 'wellbeing' ? <><WellbeingTrends records={snapshot.wellness} />{onWellnessOpen && <button className="pv-insight-link" onClick={onWellnessOpen}>{t('progress.wellbeingHistory')} <span aria-hidden="true">→</span></button>}</> : <>
      <div className="pv-section-heading"><div className="wbt-range" role="group" aria-label={t('progress.range')}>{insightRanges.map(item => <button key={item.id} aria-pressed={range === item.id} onClick={() => setRange(item.id)}>{t(`wellbeing.range_${item.id}`)}</button>)}</div></div>
      <section className="pv-work" aria-label={t('progress.work')}><BotanicalBranch /><p className="eyebrow">{t('progress.workEyebrow')}</p><h2>{t('progress.workTitle')}</h2><div className="pv-work-facts"><div><strong>{totals.count}</strong><span>{t('progress.completedSessions', { count: totals.count })}</span></div><div><strong>{totals.activeDays}</strong><span>{t('progress.activeDays', { count: totals.activeDays })}</span></div><div><strong>{totals.minutes === null ? '—' : number(totals.minutes)}</strong><span>{t('progress.recordedMinutes')} <Help label={t('progress.timeHelpLabel')}>{t('progress.timeHelp', { measured: totals.measuredMinutes, total: totals.count })}</Help></span></div><div><strong>{Math.round(totals.activeDays / days * 100)}<small>%</small></strong><span>{t('progress.regularity')} <Help label={t('progress.regularityHelpLabel')}>{t('progress.regularityHelp', { count: days })}</Help></span></div></div><p className="pv-completeness">{t('progress.activity', { active: totals.activeDays, days })}</p></section>
      <section className="pv-observations"><h2>{t('progress.periodRhythm')}</h2><p>{totals.count ? t('progress.summary', { count: totals.count, days: totals.activeDays }) : t('progress.summaryEmpty')}</p>{leadingType.count > 0 && <p>{t('progress.leading', { type: trainingTypeLabel(i18n, leadingType.id).toLocaleLowerCase(i18n.locale), count: leadingType.count })}</p>}{totals.minutes !== null && <p>{t('progress.averageTime', { average: number(totals.minutes / totals.measuredMinutes), measured: totals.measuredMinutes, total: totals.count })}</p>}<p className="pv-comparison">{t('progress.previous', { count: days, previous: previous.count, difference: signed(totals.count - previous.count) })} <Help label={t('progress.compareHelpLabel')}>{t('progress.compareHelp', { count: days, start: dateLabel(period.start), end: dateLabel(period.end), previousStart: dateLabel(period.previousStart), previousEnd: dateLabel(period.previousEnd) })}</Help></p></section>
      <section className="pv-sessions" aria-label={t('progress.chart')}><div className="pv-section-heading"><h2>{t('progress.rhythm')}</h2><span>{t('progress.every7')}</span></div><svg className="pv-activity-chart" viewBox="0 0 300 112" role="img" aria-label={buckets.map(w => t('progress.bucket', { range: w.end !== w.start ? `${dateLabel(w.start)}–${dateLabel(w.end)}` : dateLabel(w.start), sessions: t('planning.sessionCount', { count: w.count }) })).join('; ')}><line x1="0" x2="300" y1="102" y2="102" stroke="#bdcdb2" />{buckets.map((w, i) => { const cell = 300 / buckets.length; const height = w.count / max * 80; return <rect key={w.start} x={i * cell + cell * .2} y={102 - height} width={cell * .6} height={height} rx="2" fill="#729165" />; })}</svg><div className="wbt-chart-ends"><span>{dateLabel(period.start)}</span><span>{dateLabel(period.end)}</span></div><details className="pv-activity-values"><summary>{t('progress.sessionsOverTime')}</summary><div className="pv-bars">{buckets.map(w => <div className="pv-bar-row" key={w.start}><span>{shortDay(w.start)}{w.end !== w.start ? `–${shortDay(w.end)}` : ''}</span><div className="pv-bar-track"><div style={{ width: `${w.count / max * 100}%` }} /></div><strong>{w.count}</strong></div>)}</div></details></section>


      <details className="pv-filters"><summary>{t(sport || trainingType || anchor !== today() ? 'progress.filtersActive' : 'progress.filters')}</summary><div className="pv-filter-fields"><label className="field">{t('progress.sport')}<select value={sport} onChange={e => setSport(e.target.value as SportId | '')}><option value="">{t('progress.allSports')}</option>{SPORTS.map(s => <option key={s.id} value={s.id}>{t(`sport.${s.id}`)}</option>)}</select></label><label className="field">{t('progress.trainingType')}<select value={trainingType} onChange={e => setTrainingType(e.target.value as TrainingType | '')}><option value="">{t('progress.allTypes')}</option>{TRAINING_TYPES.map(type => <option key={type.id} value={type.id}>{t(`trainingType.${type.id}`)}</option>)}</select></label><label className="field">{t('progress.anchor')}<input type="date" max={today()} value={anchor} onChange={e => { if (e.target.value) setAnchor(e.target.value); }} /></label></div></details>
    </>}
    <section className="pv-goals stack" aria-label={t('progress.goals')}><div className="pv-section-heading"><h2 id="goals-heading">{t('progress.yourGoals')}</h2><button className="secondary" onClick={() => setEditing(null)}>{t('progress.addGoal')}</button></div>{!snapshot.goals.length && <div className="pv-goals-intro"><BotanicalBranch /><p>{t('progress.goalsIntroTitle')}</p><span>{t('progress.goalsIntroText')}</span></div>}{snapshot.goals.map(goal => { const progress = goalProgress(goal, snapshot.workouts, anchor, snapshot.wellness); const measured = progress.hasData; return <article className="pv-goal-card" key={goal.id}><h3>{goal.name}</h3><p>{isWellnessGoalMetric(goal.metric) ? t(`progress.metric_${goal.metric}`) : t('progress.metricAndSport', { metric: t(`progress.metric_${goal.metric}`), sport: goal.sportId ? sportName(goal.sportId) : t('progress.allSports') })}</p><p>{dateLabel(progress.start)} – {dateLabel(progress.end)}</p><p className="pv-goal-actual"><strong>{progress.actual === null || goal.metric === 'minutes' && !measured ? '—' : number(progress.actual)}</strong> {t(`progress.target_${goal.metric}`, { count: progress.target })}</p>{measured && progress.actual !== null && <progress aria-label={t('progress.goalProgress', { name: goal.name })} value={Math.min(progress.actual, progress.target)} max={progress.target} />}<p>{!measured || progress.percent === null ? t('progress.noGoalData') : goal.metric === 'sleepAverageHours' ? progress.met ? t('progress.sleepMet') : t('progress.sleepBelow', { percent: progress.percent }) : t('progress.percentOfGoal', { percent: progress.percent })}</p><p className="pv-completeness">{t('progress.daysWithData', { observed: progress.observedDays, expected: progress.expectedDays })} <Help label={t('progress.goalDataLabel', { name: goal.name })}>{t('progress.goalDataHelp')}</Help></p><button className="secondary" onClick={() => setEditing(goal)}>{t('progress.editGoal')}</button></article>; })}</section>
    {tab === 'training' && <>{onWellnessOpen && <button className="pv-insight-link" onClick={onWellnessOpen}><span>{t('progress.yourWellbeing')}<small>{t('progress.wellbeingSub')}</small></span><span aria-hidden="true">→</span></button>}
      <details className="pv-calculations"><summary>{t('progress.calculations')}</summary><div className="stack"><div className="pv-section-heading"><h3>{t('progress.index')}</h3><Help label={t('progress.index')}>{t('progress.indexHelp')}</Help></div><p>{t('progress.valueAndSessions', { value: totals.customLoad === null ? t('progress.noMeasurements') : number(totals.customLoad), measured: totals.measuredLoad, total: totals.count })}</p><div className="pv-section-heading"><h3>{t('progress.timeRpe')}</h3><Help label={t('progress.timeRpeHelpLabel')}>{t('progress.timeRpeHelp')}</Help></div><p>{t('progress.valueAndSessions', { value: totals.rpeLoad === null ? t('progress.noMeasurements') : number(totals.rpeLoad), measured: totals.measuredRpe, total: totals.count })}</p><h3>{t('progress.volume')} <Help label={t('progress.volume')}>{t('progress.volumeHelp')}</Help></h3><div className="table-scroll"><table><caption>{t('progress.volumeCaption')}</caption><thead><tr><th>{t('progress.thUnit')}</th><th>{t('progress.thPlan')}</th><th>{t('progress.thActual')}</th><th>{t('progress.thMeasurements')}</th></tr></thead><tbody>{volumes.map(v => <tr key={v.metric}><td>{t(`progress.volume_${v.metric}`)}</td><td>{number(v.planned)}</td><td>{v.measurements ? number(v.actual) : '—'}</td><td>{v.measurements}</td></tr>)}</tbody></table></div></div></details>
      <section className="pv-ratings"><h2>{t('progress.ratings')}</h2>{!ratings.length ? <p className="pv-completeness">{t('progress.ratingsEmpty')}</p> : ratings.map(w => { const content = <><strong>{w.title || t('progress.untitled')}</strong><small>{dateLabel(w.date)}</small><span className="pv-rating-values">{([[t('progress.ratingAerobic'), w.postWorkout.aerobicFatigue], [t('progress.ratingMuscular'), w.postWorkout.muscularFatigue], [t('progress.ratingSatisfaction'), w.postWorkout.satisfaction]] as const).map(([label, value]) => <span key={label}>{label}<b>{value === null ? '—' : t('progress.outOfTen', { value })}</b></span>)}</span></>; return onWorkoutOpen ? <button className="pv-rating" key={w.id} onClick={() => onWorkoutOpen(w)}>{content}<span className="sr-only">{t('progress.openWorkout')}</span></button> : <article className="pv-rating" key={w.id}>{content}</article>; })}</section>
    </>}

  </div>;
}
function GoalForm({ repository, snapshot, goal, onClose, onSaved }: Omit<Props, 'onChanged'> & { goal: Goal | null; onClose: () => void; onSaved: () => Promise<void> }) {
  const [revision] = useState(goal?.revision), [epoch] = useState(snapshot.epoch);
  const [cadence, setCadence] = useState(goal?.cadence ?? 'weekly');
  const [metric, setMetric] = useState<GoalMetric>(goal?.metric ?? 'count');
  const [target, setTarget] = useState(goal ? String(goal.target) : '');
  const [deleting, setDeleting] = useState(false);
  const { t } = useI18n();
  const action = useAction();
  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const data = new FormData(e.currentTarget);
    const input: GoalInput = { profileId: snapshot.profile!.id, name: String(data.get('name')), cadence, metric, target: Number(target), sportId: isWellnessGoalMetric(metric) ? null : (String(data.get('sportId')) || null) as SportId | null, start: cadence === 'range' ? String(data.get('start')) : null, end: cadence === 'range' ? String(data.get('end')) : null };
    await action.run(async () => { if (goal) await repository.updateGoal(goal.id, revision!, input, epoch); else await repository.createGoal(input, epoch); await onSaved(); });
  }
  return <div className="progress-view stack"><button className="back" disabled={action.busy} onClick={onClose}>{t('progress.backToProgress')}</button><h1>{t(goal ? 'progress.editGoal' : 'progress.newGoal')}</h1><Feedback {...action} /><form onSubmit={submit} className="form-layout"><fieldset disabled={action.busy} className="pv-goal-fields stack"><legend className="sr-only">{t('progress.goalData')}</legend><label className="field">{t('progress.goalName')}<input name="name" required maxLength={160} defaultValue={goal?.name ?? ''} /></label><label className="field">{t('progress.goalMetric')}<select value={metric} onChange={e => { setMetric(e.target.value as GoalMetric); setTarget(''); }}>{goalMetrics.map(id => <option key={id} value={id}>{t(`progress.metric_${id}`)}</option>)}</select></label><label className="field">{metric === 'sleepAverageHours' ? t('progress.sleepTarget') : t(`progress.targetLabel_${metric}`)}<input name="target" type="number" min={metric === 'sleepAverageHours' || metric === 'minutes' ? 0 : 1} max={metric === 'sleepAverageHours' ? 24 : 1000000} step={metric === 'sleepAverageHours' || metric === 'minutes' ? 'any' : 1} required value={target} onChange={e => setTarget(e.target.value)} /></label>{!isWellnessGoalMetric(metric) && <label className="field">{t('progress.goalSport')}<select name="sportId" defaultValue={goal?.sportId ?? ''}><option value="">{t('progress.allSports')}</option>{SPORTS.map(s => <option key={s.id} value={s.id}>{t(`sport.${s.id}`)}</option>)}</select></label>}<label className="field">{t('progress.goalCadence')}<select value={cadence} onChange={e => setCadence(e.target.value as typeof cadence)}><option value="weekly">{t('progress.cadenceWeekly')}</option><option value="range">{t('progress.cadenceRange')}</option></select></label>{cadence === 'range' && <div className="form-row"><label className="field">{t('progress.goalStart')}<input name="start" type="date" required defaultValue={goal?.start ?? today()} /></label><label className="field">{t('progress.goalEnd')}<input name="end" type="date" required defaultValue={goal?.end ?? addDays(today(), 27)} /></label></div>}</fieldset><button className="primary" disabled={action.busy}>{t('progress.saveGoal')}</button></form>{goal && (!deleting ? <button className="text-button danger" onClick={() => setDeleting(true)}>{t('progress.deleteGoal')}</button> : <div className="confirm-box"><p>{t('progress.deleteGoalText')}</p><button className="secondary danger" disabled={action.busy} onClick={() => action.run(async () => { await repository.deleteGoal(goal.id, revision!, epoch); await onSaved(); })}>{t('progress.confirmDeleteGoal')}</button><button className="text-button" onClick={() => setDeleting(false)}>{t('progress.cancel')}</button></div>)}</div>;
}



