import {computeTrainleafLoad,snapshotTrainleafLoad,loadDisplay,loadSummary} from './load-model.js';
import {seed,exercises as baseExercises} from './data.js';
import {SIX_MONTH_TODAY,createSixMonthDemo} from './demo-history.js';
import {monthFilter,historyCount} from './history-ui.js';
import {renderSessionDetail} from './session-ui.js';
import {forecastReserve,createReserveReference,historyConfirmationDays} from './energy-model.js';
import {renderPlanning} from './planning-ui.js';
import {renderProgressView,renderWellnessTrends,renderWellnessDetail,renderGoalsView} from './insights-ui.js';
import {renderAnatomy,mountAnatomy,muscleGroups} from './anatomy-ui.js';
import {esc,icon,trainingTypes,typeOf,typeBadge,helpButton,bindHelp,helpTexts} from './ui-core.js';
import {leafArt,leafMark,updateLeaves} from './leaf-ui.js';
import {feelingField,updateFeeling} from './feeling-ui.js';
import {renderWeek,weekDates} from './week-ui.js';
import {renderMore,renderProfile,renderModules,bindProfile,readProfile,readModules,sportChoices} from './profile-ui.js';
import {prepareExercise,renderExerciseEditor,handleExerciseClick,handleExerciseInput} from './exercise-editor.js';

const previewParams=new URLSearchParams(location.search),populatedDemo=previewParams.get('demo')==='six-months',iteration3Demo=populatedDemo&&previewParams.get('v')==='iteration3';
const demoToday=populatedDemo?SIX_MONTH_TODAY:'2026-10-03',key=(iteration3Demo?'trainleaf-six-month-demo-iteration3-v1':populatedDemo?'trainleaf-six-month-demo-v1':'fieldwork-ui-demo-v1')+(previewParams.get('qa')==='1'?'-qa':''),clone=x=>structuredClone(x);
let saved;try{saved=JSON.parse(localStorage.getItem(key))}catch{}
const state=saved||(populatedDemo?createSixMonthDemo():clone(seed));if(!saved)for(const w of state.workouts){if(w.status==='completed'&&!w.loadSnapshot)w.loadSnapshot=snapshotTrainleafLoad(w)}
state.workouts??=[];state.profile??=clone(seed.profile);
state.periods??=state.period?[{...state.period,id:'legacy-period',parentId:null}]:clone(seed.periods);
state.customExercises??=[];
state.events??=populatedDemo?[{id:'demo-trip-autumn',title:'Wyjazd drużyny',kind:'trip',start:'2026-10-09',end:'2026-10-11',notes:'Wspólny weekend poza miastem.'},{id:'demo-tournament',title:'Turniej klubowy',kind:'event',start:'2026-10-17',end:'2026-10-17',notes:'Wydarzenie w kalendarzu, oddzielnie od treningów.'}]:[];
state.goals??=populatedDemo?[{id:'demo-goal-active',title:'Miejsce na ruch',type:'activeDays',target:4,period:'week'},{id:'demo-goal-checkin',title:'Chwila na check-in',type:'checkins',target:5,period:'week'}]:[];
state.muscleTargets??={};
state.confirmedRestDays??=[];state.historyConfirmations??=[];
const catalog=[...clone(baseExercises),...state.customExercises];
for(const workout of state.workouts){workout.exercises??=[];for(const ex of workout.exercises){const source=catalog.find(c=>c.name===ex.name);ex.id??=crypto.randomUUID();ex.muscles??=source?.muscles||[];ex.modality??=source?.modality;}}
let view='journal',activeNav='journal',draft=state.draft||null,day=demoToday,notice='',error='',scenario='normal',picking=false,selectedExercise=0,query='',filter='Wszystkie',historyTab='completed',todayExpanded=false,periodId=null,returnView='journal';
const app=document.querySelector('#app');
let planMode='week',planFilters={search:'',trainingType:''},selectedSeasonId=null,selectedSessionId=null,sessionReturn='journal',selectedWellnessKey=null,wellnessOrigin='progress',wellnessSlot='Rano',wellnessMetric='Sen (godziny)',wellnessRange='month',wellnessOriginalKey=null,wellnessShownKey=null,wellnessCache={},eventId=null,goalId=null,selectedMuscleId=null,selectedRolesIndex=null,mappingOriginalPlan=false,pendingReference=null,disposeAnatomy=null;
let progressRange='week',historyMonth='',wellnessMonth='',historyLimit=20,wellnessLimit=20;
let historyConfirmationDraft=null;
if(populatedDemo){document.title='Trainleaf · 6 miesięcy danych';document.querySelector('.review-heading>span').textContent='Przykładowa historia · 4 kwi – 4 paź 2026';}
const button=(label,attrs='',cls='')=>`<button type="button" class="${cls}" ${attrs}>${label}</button>`;
const go=(label,target,cls='')=>button(label,`data-go="${target}"`,cls);
const heading=(title,sub='')=>`<div class="page-heading"><h1>${title}</h1>${sub?`<p class="muted">${sub}</p>`:''}</div>`;
const back=(target='more')=>go('← Wróć',target,'subtle');
const field=(label,name,value='',type='text',extra='')=>`<label class="field">${label}<input name="${esc(name)}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const select=(label,name,values,value)=>`<label class="field">${label}<select name="${name}" aria-label="${esc(label)}" ${name==='trainingType'?'required':''}>${values.map(x=>{const o=typeof x==='string'?{value:x,label:x}:x;return `<option value="${esc(o.value)}" ${o.value===value?'selected':''}>${esc(o.label)}</option>`}).join('')}</select></label>`;
const note=(name,value='',label='Notatka · opcjonalnie')=>`<label class="field">${label}<textarea name="${name}">${esc(value)}</textarea></label>`;
const list=()=>scenario==='empty'?[]:state.workouts;
const dateLabel=date=>new Intl.DateTimeFormat('pl-PL',{day:'numeric',month:'long'}).format(new Date(date+'T12:00:00'));
function persist(){try{localStorage.setItem(key,JSON.stringify({...state,draft}));return true}catch{error='Nie udało się zapisać. Treść pozostaje w formularzu.';return false}}
function nav(target){if(target==='wellnessHub')target='wellnessTrends';if(['editor','postSession'].includes(target)){const origin=returnView==='session'?sessionReturn:returnView;activeNav=origin==='plan'?'plan':origin==='history'?'more':origin==='progress'?'progress':'journal'}if(['journal','plan','progress','more'].includes(target))activeNav=target;if(['wellnessTrends','wellnessDetail','goals','goalEditor'].includes(target))activeNav='progress';if(['library','templates','history','settings','onboarding','modules','export'].includes(target)&&!picking)activeNav='more';view=target;error='';render();window.scrollTo(0,0);app.focus({preventScroll:true})}
function start(workout=null,planned=false){returnView=['journal','plan','history','session'].includes(view)?view:'journal';draft=workout?clone(workout):{id:crypto.randomUUID(),title:'',trainingType:'strength',sport:state.profile.sports?.[0]||'',date:day,time:'',duration:'',rpe:'',notes:'',status:planned?'planned':'completed',exercises:[],groups:[]};persist();nav('editor')}
function currentPeriods(date){return (state.periods||[]).filter(p=>p.start<=date&&p.end>=date).sort((a,b)=>a.start.localeCompare(b.start)||b.end.localeCompare(a.end))}
function periodSummary(date){const matches=currentPeriods(date);return `<div class="auto-period"><span class="eyebrow">Okres według daty treningu</span>${matches.length?`<ul>${matches.map(p=>`<li><strong>${esc(p.name)}</strong><small>${p.parentId?'W ramach: '+esc(state.periods.find(x=>x.id===p.parentId)?.name||'okres nadrzędny'):'Okres niezależny'} · ${dateLabel(p.start)} – ${dateLabel(p.end)}</small></li>`).join('')}</ul>${matches.length>1?'<p>Ta data należy do wszystkich wymienionych okresów.</p>':''}`:'<p>Brak okresu treningowego</p>'}</div>`}
function card(w){const planned=w.status==='planned',missed=planned&&w.date<demoToday;return `<button style="--session-paper:${typeOf(w).background};--session-ink:${typeOf(w).color}" class="session-card ${planned?'is-planned':'is-completed'}" data-edit="${esc(w.id)}"><span class="session-card-top">${typeBadge(w)}<span class="session-state">${planned?(missed?'Plan bez wykonania':'Zaplanowany'):'Ukończony'}</span></span><strong>${esc(w.title)}</strong><span class="session-card-meta">${dateLabel(w.date)}${w.time?' · '+esc(w.time):''} · ${esc(w.duration||'—')} min</span><span class="session-card-sport">${esc(w.sport)}</span>${w.notes?`<span class="session-card-note">${esc(w.notes)}</span>`:''}<span class="session-card-link">Otwórz ${icon('arrow')}</span></button>`}
function journal(){const sessions=list().filter(w=>w.date===demoToday),checkin=wellnessEntries().find(w=>w.date===demoToday),periods=currentPeriods(demoToday);return `<div class="journal-heading"><div><h1>Dzisiaj</h1><p>${new Intl.DateTimeFormat('pl-PL',{weekday:'long',day:'numeric',month:'long'}).format(new Date(demoToday+'T12:00:00'))}</p></div><div class="month-stamp" aria-hidden="true"><strong>${demoToday.slice(8)}</strong><span>PAŹ 2026</span></div></div>
${checkin?`<button class="checkin-done" data-wellness-entry="${esc(checkin.date+'|'+checkin.slot)}"><span class="checkin-check">${icon('check')}</span><span>Check-in zrobiony<small>${esc(checkin.slot)} · zobacz wpis</small></span>${icon('chevron')}</button>`:`<section class="checkin-card" aria-labelledby="checkin-title">${leafArt()}<div class="leaf-copy"><div class="checkin-intro"><span class="eyebrow">Twój check-in</span><span class="checkin-optional">Opcjonalnie</span></div><h2 id="checkin-title">Jak się dziś czujesz?</h2><p>Sen, energia, samopoczucie.<br>Wystarczy jedna odpowiedź.</p>${button('Zrób check-in '+icon('arrow'),'data-checkin','primary wide')}</div></section>`}
<div class="section-heading"><h2>Treningi na dziś</h2>${button(todayExpanded?'Tylko dziś':'Cały tydzień',`data-today-week aria-expanded="${todayExpanded}" aria-controls="today-sessions"`,'subtle')}</div><div id="today-sessions">${todayExpanded?renderWeek({workouts:list(),selectedDay:demoToday,today:demoToday,showNavigation:false,showDayDetail:false,compact:true,energy:calendarEnergy()}):sessions.map(card).join('')||'<div class="empty"><h3>Dziś bez planu</h3><p>Miejsce na odpoczynek lub spontaniczny trening.</p></div>'}</div>
${button(icon('plus')+' Zapisz trening','data-new aria-label="＋ Zapisz trening"','wide today-add')}
${draft?`<div class="notice row"><span>Szkic: ${esc(draft.title||'Nowy trening')}</span>${go('Dokończ','editor','subtle')}</div>`:''}
<section class="today-context" aria-label="Cel i okres treningowy"><button class="context-feature goal-feature" data-go="goal">${leafArt()}<span class="leaf-copy"><span class="context-top"><span class="context-icon">${icon('target')}</span><span class="eyebrow">Mój cel</span>${icon('arrow')}</span><strong>${esc(state.goal||'Znaleźć czas na 3 treningi w tygodniu.')}</strong><span class="context-bottom">Twój kierunek, Twoje tempo</span></span></button><button class="context-feature period-feature" data-go="periods">${leafArt()}<span class="leaf-copy"><span class="context-top"><span class="context-icon">${icon('plan')}</span><span class="eyebrow">Obecny okres</span>${icon('arrow')}</span><strong>${periods.length>1?periods.length+' aktywne okresy':esc(periods[0]?.name||'Brak aktywnego okresu')}</strong><span class="context-bottom">${periods.length>1?periods.map(p=>esc(p.name)).join('<br>'):periods[0]?esc(periods[0].start+' — '+periods[0].end):'Możesz planować pojedyncze sesje.'}</span></span></button></section>`}
function plan(){return renderPlanning({workouts:list(),periods:state.periods,events:state.events,day,today:demoToday,mode:planMode,filters:planFilters,selectedSeasonId,energy:calendarEnergy()})+lastCheckinContext()+(planMode==='week'?renderAnatomy(anatomyProps()):'')}
function history(){const filters=[['completed','Wykonane'],['missed','Niewykonane plany'],['planned','Plany'],['drafts','Szkic']];let content;if(historyTab==='drafts')content=draft?`<div class="card"><span class="tag">Szkic</span><h2>${esc(draft.title||'Nowy trening')}</h2><p>${esc(draft.date)}</p>${go('Dokończ szkic','editor','primary')}</div>`:'<p class="empty">Nie ma otwartego szkicu.</p>';else{const all=list().filter(w=>historyTab==='completed'?w.status==='completed'&&w.date<=demoToday:historyTab==='missed'?w.status==='planned'&&w.date<demoToday:w.status==='planned'&&w.date>=demoToday).sort((a,b)=>b.date.localeCompare(a.date)||(b.time||'').localeCompare(a.time||''));if(historyMonth&&!all.some(w=>w.date.startsWith(historyMonth))){historyMonth='';historyLimit=20}const rows=all.filter(w=>!historyMonth||w.date.startsWith(historyMonth));content=monthFilter(all,'history-month',historyMonth)+historyCount(rows.length,Math.min(historyLimit,rows.length))+(rows.slice(0,historyLimit).map(card).join('')||'<p class="empty">Brak wpisów w tym widoku.</p>')+(rows.length>historyLimit?button('Pokaż kolejne 20','data-more-history','wide'):'')}return back()+heading('Historia','Wykonanie, plan i szkic mają osobne miejsca.')+`<div class="filter-tabs" aria-label="Rodzaj historii">${filters.map(([id,label])=>button(label,`data-history="${id}" aria-pressed="${historyTab===id}"`,historyTab===id?'primary':'')).join('')}</div>`+content}
function editor(){if(!draft)return heading('Nie ma otwartego szkicu')+go('Dzisiaj','journal');const planned=draft.status==='planned',future=draft.date>demoToday;const chosenSports=[...new Set([...(state.profile.sports||[]),draft.sport].filter(Boolean))];return back(returnView)+heading(planned?'Zaplanuj trening':'Zapisz trening')+`<div id="editor-period" aria-live="polite">${periodSummary(draft.date)}</div><span class="tag">Szkic</span>${!planned&&draft.loadSnapshot?loadCard(draft):''}<form id="workout">${field('Nazwa treningu','title',draft.title,'text','required maxlength="160" placeholder="Nazwa Twojej sesji"')}${select('Rodzaj treningu','trainingType',[{value:'',label:'Wybierz rodzaj treningu'},...trainingTypes.map(t=>({value:t.id,label:t.label}))],draft.trainingType)}<div id="chosen-type">${trainingTypes.some(t=>t.id===draft.trainingType)?typeBadge(draft):''}</div>${select('Dyscyplina','sport',chosenSports,draft.sport)}${go('Zmień sporty w profilu','onboarding','subtle')}${field('Data','date',draft.date,'date','required')}${field('Godzina · opcjonalnie','time',draft.time,'time')}${field(planned?'Planowany czas (min) · opcjonalnie':'Wykonany czas (min) · opcjonalnie','duration',draft.duration,'number','min="1" max="1440"')}${planned?plannedExpectations():''}${!planned?`<div class="label-help"><span>Wysiłek całej sesji · RPE</span>${helpButton('rpe')}</div>${select('RPE · opcjonalnie','rpe',[{value:'',label:'Bez odpowiedzi'},...Array.from({length:11},(_,i)=>String(i))],draft.rpe)}`:''}${note('notes',draft.notes)}${renderExerciseEditor(draft)}<div class="actions">${button('＋ Ćwiczenie','data-picker')}${go('Z szablonu','templates')}</div><div id="save-error" role="alert">${error?`<p class="error">${esc(error)}</p>`:''}</div><div id="future-message" aria-live="polite">${future?'<p class="notice">To przyszła data. Możesz zapisać plan; wykonanie dodasz najwcześniej w dniu treningu.</p>':''}</div><button id="save-workout" class="primary wide" ${!planned&&future?'disabled aria-describedby="future-message"':''}>${planned?'Zapisz plan':'Dalej · po treningu'}</button>${!planned&&future?button('Zapisz jako plan','data-convert-plan','wide'):''}</form>${planned?button('Zapisz wykonanie tego planu',`data-complete ${future?'disabled aria-describedby="future-message"':''}`,'wide completion-action'):''}<div class="actions">${button('Kopiuj jako nowy','data-copy')}${go('Zostaw szkic','journal')}</div>`}
function periods(){return back(activeNav==='plan'?'plan':'journal')+heading('Okresy treningowe','Wszystkie okresy obejmujące datę są widoczne w edytorze.')+state.periods.map(p=>`<button class="period-list-row" data-period="${esc(p.id)}"><strong>${esc(p.name)}</strong><small>${esc(p.start)} — ${esc(p.end)}</small><span>${p.parentId?'W ramach: '+esc(state.periods.find(x=>x.id===p.parentId)?.name||'okres nadrzędny'):'Okres niezależny'}</span>${currentPeriods(demoToday).some(x=>x.id===p.id)?'<span class="tag">Aktywny dziś</span>':''}</button>`).join('')+button('＋ Dodaj okres','data-period-new','wide')}
function period(){const p=state.periods.find(p=>p.id===periodId)||{id:periodId,name:'',start:day,end:day,phase:'',goal:'',parentId:''};return back('periods')+heading(p.name?'Edytuj okres':'Nowy okres')+`<form id="period">${field('Nazwa','name',p.name,'text','required')}${field('Od','start',p.start,'date','required')}${field('Do','end',p.end,'date','required')}${field('Fokus · opcjonalnie','phase',p.phase)}${select('Okres nadrzędny · opcjonalnie','parentId',[{value:'',label:'Brak'},...state.periods.filter(x=>x.id!==p.id).map(x=>({value:x.id,label:x.name}))],p.parentId||'')}${note('goal',p.goal,'Cel · opcjonalnie')}<p class="muted">Okresy mogą się nakładać. Edytor pokaże wszystkie pasujące do daty.</p><div id="save-error" role="alert"></div><button class="primary wide">Zapisz okres</button></form>`}
function library(){return back(picking?'editor':'more')+heading(picking?'Dodaj ćwiczenie':'Katalog','Opisy, metadane i Twoje notatki.')+`${field('Szukaj ćwiczenia','search',query,'search','placeholder="Nazwa ćwiczenia"')}${select('Rodzaj ćwiczenia','filter',['Wszystkie','Siła','Wytrzymałość','Technika','Mobilność','Mentalny'],filter)}<div id="exercise-list">${exerciseList()}</div>${go('＋ Własne ćwiczenie','custom','wide')}`}
function exerciseList(){return catalog.map((ex,i)=>({ex,i})).filter(({ex})=>(filter==='Wszystkie'||ex.kind===filter)&&ex.name.toLocaleLowerCase('pl').includes(query.toLocaleLowerCase('pl'))).map(({ex,i})=>`<button class="card-button exercise-row" data-exercise="${i}"><span class="exercise-symbol">${icon(ex.modality==='running'?'running':ex.kind==='Siła'?'strength':'mobility')}</span><span><strong>${esc(ex.name)}</strong><small>${esc(ex.kind)}${ex.muscles?.length?' · '+esc(ex.muscles.join(', ')):''}</small></span>${icon('chevron')}</button>`).join('')||'<p class="empty">Brak wyników. Zmień filtr albo dodaj własne ćwiczenie.</p>'}
function detail(){const ex=catalog[selectedExercise];return back('library')+heading(esc(ex.name),esc(ex.kind))+`<p>${esc(ex.description||'Nie dodano opisu wykonania.')}</p><div class="exercise-metadata"><span>Jednostka: ${esc(ex.unit)}</span><span>Grupy mięśniowe: ${esc(ex.muscles?.join(', ')||'bez oznaczeń')}</span></div><form id="exercise-note">${note('exerciseNote',state.exerciseNotes?.[ex.name]||'','Moja notatka')}<button>Zapisz notatkę</button></form>${button(picking?'Dodaj do treningu':'Utwórz trening z ćwiczeniem',picking?'data-add-exercise':'data-create-exercise','primary wide')}`}
function custom(){return back('library')+heading('Własne ćwiczenie')+`<form id="custom">${field('Nazwa','name','','text','required')}${select('Rodzaj ćwiczenia','kind',['Siła','Wytrzymałość','Technika','Mobilność','Mentalny'],'Siła')}${select('Sposób wykonania','modality',[{value:'strength',label:'Ćwiczenie siłowe'},{value:'running',label:'Bieg'},{value:'cycling',label:'Rower'},{value:'other',label:'Inne'}],'strength')}${select('Jednostka','unit',['powt.','min','m','rzuty'],'powt.')}${field('Grupy mięśniowe · oddziel przecinkami','muscles')}${note('description','','Opis wykonania · opcjonalnie')}<button class="primary wide">Dodaj do katalogu</button></form>`}
function templates(){return back(draft?'editor':'more')+heading('Szablony','Układy ćwiczeń do uzupełnienia własnymi parametrami.')+`<div class="card"><span class="tag">Szablon demonstracyjny</span><h2>Siła całego ciała</h2><p>Rozgrzewka, ćwiczenia siłowe i Cooldown.</p>${button('Użyj w treningu','data-template="whole"','primary')}</div><div class="card"><span class="tag">Sekcja demonstracyjna</span><h2>Mobilna rozgrzewka</h2><p>Mobilizacja bioder. Czas i serie uzupełniasz samodzielnie.</p>${button('Dodaj sekcję','data-template="section"')}</div>`}
const postQuestions=[['aerobic','Zmęczenie oddechowe / tlenowe'],['muscular','Zmęczenie mięśniowe / siłowe'],['satisfaction','Przyjemność / satysfakcja']];
const loadReasons={not_completed:'Wynik pojawi się po ukończeniu treningu.',missing_training_type:'Wybierz rodzaj treningu.',unknown_training_type:'Ten rodzaj nie ma ustalonej wagi.',missing_duration:'Brak wykonanego czasu.',invalid_duration:'Uzupełnij poprawny wykonany czas.',missing_aerobic:'Brak oceny zmęczenia oddechowego.',missing_muscular:'Brak oceny zmęczenia mięśniowego.',invalid_aerobic:'Sprawdź ocenę zmęczenia oddechowego.',invalid_muscular:'Sprawdź ocenę zmęczenia mięśniowego.'};
function loadCard(workout,preview=false){const computed=preview?computeTrainleafLoad(workout):null,preserved=preview&&workout.loadSnapshot&&JSON.stringify(computed.inputs)===JSON.stringify(workout.loadSnapshot.inputs);const snapshot=preview&&!preserved?computed:workout.loadSnapshot;return `<section class="load-summary"><div class="label-help"><h2>Trainleaf load</h2>${helpButton('trainleaf-load')}</div><strong>${loadDisplay(snapshot)}</strong><p>${snapshot?.inputs?.trainingType==='mental'?'Trening mentalny jest wyłączony z obciążenia fizycznego. Pozostaje w czasie i liczbie treningów.':snapshot?.status==='calculated'?(preview&&!preserved?'Podgląd wyniku. Zapisz go razem z treningiem.':'Zapisany wynik · '+esc(snapshot.algorithm)):esc(loadReasons[snapshot?.reason]||'Ten wpis nie ma zapisanego wyniku.')}</p>${preview?'<small>Możesz zapisać trening także bez wyniku.</small>':''}</section>`}
function progressLoad(rows,label='tydzień'){const summary=loadSummary(rows,demoToday);const text=summary.total===null?'—':new Intl.NumberFormat('pl-PL',{minimumFractionDigits:1,maximumFractionDigits:1}).format(summary.total);return `<section class="load-summary"><div class="label-help"><h2>Trainleaf load · ${esc(label)}</h2>${helpButton('trainleaf-load')}</div><strong>${text}</strong><p>${summary.calculatedCount} z ${summary.completedCount} wykonanych sesji ma zapisany wynik.${summary.missingCount?' Bez wyniku: '+summary.missingCount+'.':''}</p>${summary.mentalCount?'<p>Mentalne: '+summary.mentalCount+' · pozostają w statystykach czasu.</p>':''}${summary.mixedAlgorithms?'<p>Suma zapisanych wyników z różnych wersji algorytmu.</p>':''}</section>`}
function reviewSaveLabel(){const p=draft?.postSession;return p&&(postQuestions.some(([key])=>p[key]!==null&&p[key]!==undefined&&p[key]!=='')||p.notes?.trim())?'Zapisz bez dalszych odpowiedzi':'Pomiń ankietę i zapisz'}
function refreshLoadPreview(){const slot=document.querySelector('#load-preview');if(slot&&draft)slot.innerHTML=loadCard(draft,true);const skip=document.querySelector('[data-skip-review]');if(skip)skip.textContent=reviewSaveLabel()}
function postSession(){if(!draft)return heading('Nie ma sesji do zapisania')+go('Dzisiaj','journal');draft.postSession??={aerobic:null,muscular:null,satisfaction:null,notes:''};return back('editor')+heading('Po treningu','Jak czujesz się po tej sesji? Każde pytanie możesz pominąć.')+`<div class="session-review-heading">${typeBadge(draft)}<strong>${esc(draft.title)}</strong><small>${dateLabel(draft.date)} · ${esc(draft.duration||'—')} min</small></div><form id="post-session">${postQuestions.map(([key,label],i)=>`<div data-post-key="${key}">${feelingField(label,0,10,draft.postSession[key],100+i)}</div>`).join('')}${note('post-notes',draft.postSession.notes)}<div id="load-preview" aria-live="polite">${loadCard(draft,true)}</div><p class="form-aside">To ocena po tej sesji. Samopoczucie dnia i RPE zapisujesz osobno.</p><div id="save-error" role="alert">${error?`<p class="error">${esc(error)}</p>`:''}</div><button class="primary wide">Zapisz trening</button>${button(reviewSaveLabel(),'data-skip-review','wide')}</form>`}
function wellnessEntries(){return [...(state.wellnessEntries||[]),...(state.wellness?[state.wellness]:[])].filter((entry,index,all)=>all.findIndex(x=>x.date===entry.date&&x.slot===entry.slot)===index)}
function wellness(){const entry=wellnessCache[selectedWellnessKey]||{},date=entry.date||day,slot=entry.slot||'Rano';wellnessShownKey=date+'|'+slot;return back(wellnessOriginalKey?'wellnessDetail':wellnessOrigin)+heading(wellnessOriginalKey?'Edytuj check-in':'Nowy check-in','Wystarczy jedna odpowiedź. Resztę możesz pominąć.')+`<form id="wellness">${field('Data','date',date,'date','required max="'+demoToday+'"')}${select('Pora dnia','slot',['Rano','W ciągu dnia','Wieczorem'],slot)}<div id="wellness-fields"></div>${note('notes',entry.notes||'')}<div id="save-error" role="alert"></div><button class="primary wide">Zapisz check-in</button></form>`}
function wellnessFields(){const form=document.querySelector('#wellness');if(!form)return;const slot=form.elements.slot.value,entry=wellnessCache[form.elements.date.value+'|'+slot]||wellnessEntries().find(x=>x.date===form.elements.date.value&&x.slot===slot);wellnessShownKey=form.elements.date.value+'|'+slot;selectedWellnessKey=wellnessShownKey;const qs=slot==='Rano'?[['Sen (godziny)',0,24,.25],['Jakość snu',1,5,1],['Zmęczenie',0,10,1],['Bolesność mięśni',0,10,1]]:slot==='W ciągu dnia'?[['Energia',1,5,1],['Stres',0,10,1],['Nastrój',1,5,1],['Koncentracja',1,5,1]]:[['Zmęczenie',0,10,1],['Bolesność mięśni',0,10,1],['Stres',0,10,1],['Czas na odpoczynek',1,5,1]];document.querySelector('#wellness-fields').innerHTML=qs.map(([n,min,max,step],i)=>step===1?feelingField(n,min,max,entry?.[`answer-${n}`]??'',i):field(`${n} · ${min}–${max}`,`answer-${n}`,entry?.[`answer-${n}`]??'','number',`min="${min}" max="${max}" step="${step}" placeholder="Bez odpowiedzi"`)).join('');form.elements.notes.value=entry?.notes||''}
function wellnessHistory(){const all=wellnessEntries().sort((a,b)=>b.date.localeCompare(a.date)),entries=all.filter(e=>!wellnessMonth||e.date.startsWith(wellnessMonth));return back()+heading('Samopoczucie','Wpisy dnia, oddzielone od ocen po treningach.')+button('Dodaj check-in','data-checkin','primary wide')+monthFilter(all,'wellness-month',wellnessMonth)+historyCount(entries.length,Math.min(wellnessLimit,entries.length))+(entries.length?entries.slice(0,wellnessLimit).map(e=>`<button class="card wellness-entry" data-wellness-entry="${esc(e.date+'|'+e.slot)}"><strong>${esc(e.date)} · ${esc(e.slot)}</strong><dl>${Object.entries(e).filter(([k,v])=>k.startsWith('answer-')&&v!==''&&v!=null).map(([k,v])=>`<dt>${esc(k.slice(7))}</dt><dd>${esc(v)}</dd>`).join('')}</dl>${e.notes?`<p>${esc(e.notes)}</p>`:''}</button>`).join(''):'<p class="empty">Nie ma jeszcze wpisów samopoczucia.</p>')+(entries.length>wellnessLimit?button('Pokaż kolejne 20','data-more-wellness','wide'):'')}
function progress(){return renderProgressView({workouts:list(),wellness:wellnessEntries(),goals:state.goals,goal:state.goal,today:demoToday,range:progressRange})}
function appearanceSettings(){const preference=window.TrainleafAppearance?.getPreference()||'system';return `<section class="appearance-panel" aria-labelledby="appearance-settings-title"><h2 id="appearance-settings-title">Wygląd</h2><label class="field">Motyw<select data-appearance-select>${[['light','Jasny'],['dark','Ciemny'],['system','Systemowy']].map(([value,label])=>`<option value="${value}" ${value===preference?'selected':''}>${label}</option>`).join('')}</select></label><p data-appearance-status role="status">${preference==='system'?'Wygląd dopasowuje się do ustawienia urządzenia.':'Wybrany wygląd zostaje po ponownym uruchomieniu. Systemowy nadal jest dostępny.'}</p></section>`}
function settings(){return back()+heading('Ustawienia')+appearanceSettings()+go('Sporty w profilu','onboarding','wide')+go('Dostosuj skróty w Inne','modules','wide')+`<h2>Zapis i kopie</h2><div class="card"><p>Dane demonstracyjne są zapisane w tej przeglądarce.${populatedDemo?' Ten wariant zawiera sześć miesięcy fikcyjnych wpisów.':''}</p>${go('Eksport danych demonstracyjnych','export','wide')}</div><h2>O prototypie</h2><p>Trainleaf · iteracja 3 po teście APK. Data podglądu: ${dateLabel(demoToday)} 2026.</p>`}
function exports(){return back()+heading('Eksport danych','Ty wybierasz, gdzie zachować plik.')+`<form id="export">${select('Format','format',[{value:'csv',label:'CSV · zestawienie sesji'},{value:'json',label:'JSON · wszystkie dane prototypu'}],'json')}<p>To dane demonstracyjne. JSON prototypu nie jest kopią zgodną z aplikacją Android. Dane zapisują się lokalnie; wyeksportowany plik możesz przechować we własnym miejscu.</p><button class="primary wide">Pobierz plik demonstracyjny</button></form>`}
function render(){disposeAnatomy?.();disposeAnatomy=null;const screens={journal,plan,history,editor,session:()=>renderSessionDetail({workout:state.workouts.find(w=>w.id===selectedSessionId),periods:state.periods,today:demoToday,backView:sessionReturn}),wellnessTrends:()=>renderWellnessTrends({entries:wellnessEntries(),today:demoToday,slot:wellnessSlot,metric:wellnessMetric,range:wellnessRange}),wellnessDetail:()=>renderWellnessDetail({entry:entryFromKey(selectedWellnessKey)}),goals:()=>renderGoalsView({goals:state.goals,workouts:list(),entries:wellnessEntries(),today:demoToday}),goalEditor,eventEditor,muscleTargetEditor,exerciseRolesEditor,energySettings,periods,period,library,detail,custom,templates,postSession,wellness,wellnessHistory,progress,settings,export:exports,more:()=>renderMore(state.profile),onboarding:()=>renderProfile(state.profile).replace('data-go="settings"',draft?'data-go="editor"':'data-go="settings"'),modules:()=>renderModules(state.profile),goal:()=>back('journal')+heading('Mój cel')+`<form id="goal">${note('goal',state.goal||'Znaleźć czas na 3 treningi w tygodniu.','Cel · własnymi słowami')}<button class="primary">Zapisz cel</button></form>`};app.dataset.view=view;app.innerHTML=(notice?`<p class="notice" role="status">${esc(notice)}</p>`:'')+(screens[view]||journal)();document.querySelector('#nav').innerHTML=[['journal','Dzisiaj'],['plan','Plan'],['progress','Postępy'],['more','Inne']].map(([id,label])=>button(`<span class="nav-icon">${icon(id)}</span><span>${label}</span>`,`data-go="${id}" ${activeNav===id?'aria-current="page"':''}`)).join('');window.TrainleafAppearance?.refreshControls();if(view==='wellness')wellnessFields();if(view==='onboarding')bindProfile(app);updateLeaves(app);if(view==='plan'&&planMode==='week')disposeAnatomy=mountAnatomy(app,anatomyProps())}
function showError(message){error=message;let slot=document.querySelector('#save-error')||document.querySelector('#profile-error');if(!slot&&document.querySelector('#profile')){slot=document.createElement('div');slot.id='profile-error';document.querySelector('#profile').prepend(slot)}if(slot)slot.innerHTML=`<p class="error" role="alert">${esc(message)}</p>`;else{notice=message;render()}}
function saveDraft(){if(!draft)return;if(draft.status==='completed'&&draft.date>demoToday){showError('Nie można ukończyć treningu z przyszłą datą. Zmień datę lub zapisz plan.');return}if(['error','full'].includes(scenario)){showError(scenario==='full'?'Brak miejsca. Treść pozostaje w formularzu; spróbuj ponownie po zwolnieniu miejsca.':'Nie udało się zapisać. Treść pozostaje w formularzu; spróbuj ponownie.');return}if(draft.status==='completed'){const next=snapshotTrainleafLoad(draft);if(!draft.loadSnapshot||JSON.stringify(next.inputs)!==JSON.stringify(draft.loadSnapshot.inputs))draft.loadSnapshot=next}else delete draft.loadSnapshot;const original=draft,previous=state.workouts;state.workouts=[...state.workouts.filter(w=>w.id!==draft.id),clone(draft)];draft=null;if(!persist()){draft=original;state.workouts=previous;showError(error);return}notice=original.status==='planned'?'Zapisano plan.':'Zapisano trening.';day=original.date;selectedSessionId=original.id;nav(returnView==='session'?'session':original.status==='planned'?'plan':'journal')}
function updateFutureState(){document.querySelector('#editor-period').innerHTML=periodSummary(draft.date);const future=draft.date>demoToday,slot=document.querySelector('#future-message');slot.innerHTML=future?'<p class="notice">To przyszła data. Możesz zapisać plan; wykonanie dodasz najwcześniej w dniu treningu.</p>':'';const save=document.querySelector('#save-workout');save.disabled=draft.status==='completed'&&future;save.setAttribute('aria-describedby','future-message');const completion=document.querySelector('[data-complete]');if(completion)completion.disabled=future;let convert=document.querySelector('[data-convert-plan]');if(future&&draft.status==='completed'&&!convert)save.insertAdjacentHTML('afterend',button('Zapisz jako plan','data-convert-plan','wide'));if(!future)convert?.remove()}
function syncPost(range,skip=false){updateFeeling(range,skip);if(range.closest('#wellness'))cacheWellnessForm();const block=range.closest('[data-post-key]');if(block&&draft){draft.postSession??={aerobic:null,muscular:null,satisfaction:null,notes:''};draft.postSession[block.dataset.postKey]=skip?null:Number(range.value);persist();refreshLoadPreview()}}
function entryFromKey(key){return wellnessEntries().find(e=>e.date+'|'+e.slot===key)}
function anatomyProps(){const dates=weekDates(day),values=Object.values(state.muscleTargets).filter(t=>t.start<=dates[6]&&t.end>=dates[0]).sort((a,b)=>(a.scope==='week')-(b.scope==='week')||a.start.localeCompare(b.start)||String(a.updatedAt).localeCompare(String(b.updatedAt))),targets={};for(const t of values)targets[t.muscleId]={sets:t.target,source:t.source,periodId:t.periodId,start:t.start,end:t.end};return {workouts:list(),periods:state.periods,day,today:demoToday,targets}}
function calendarEnergy(){const dates=planMode==='month'?Array.from({length:42},(_,i)=>{const d=new Date(weekDates(day.slice(0,7)+'-01')[0]+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+i);return d.toISOString().slice(0,10)}):weekDates(view==='journal'?demoToday:day);return {...forecastReserve({workouts:list(),dates,today:demoToday,reference:state.reserveReference,confirmedRestDays:state.confirmedRestDays}),__referenceRequired:!state.reserveReference?.value}}
function savePatch(patch,message,target){if(['error','full'].includes(scenario)){showError(scenario==='full'?'Brak miejsca. Odpowiedzi pozostają w formularzu.':'Zapis się nie udał. Odpowiedzi pozostają w formularzu.');return false}const previous=Object.fromEntries(Object.keys(patch).map(k=>[k,state[k]]));Object.assign(state,patch);if(!persist()){Object.assign(state,previous);showError(error);return false}notice=message;nav(target);return true}
function cacheWellnessForm(){const f=document.querySelector('#wellness');if(!f||!wellnessShownKey)return;const entry=Object.fromEntries(new FormData(f)),[date,slot]=wellnessShownKey.split('|');wellnessCache[wellnessShownKey]={...entry,date,slot}}
function openWellness(key=null){wellnessOriginalKey=key;selectedWellnessKey=key||demoToday+'|Rano';const entry=key?entryFromKey(key):{date:demoToday,slot:'Rano'};wellnessCache={[selectedWellnessKey]:clone(entry||{date:demoToday,slot:'Rano'})};day=entry?.date||demoToday;nav('wellness')}
function openSession(id){const w=state.workouts.find(w=>w.id===id);if(!w)return;sessionReturn=['plan','history','journal','progress'].includes(view)?view:'journal';selectedSessionId=id;nav('session')}
function eventEditor(){const e=state.events.find(e=>e.id===eventId)||{title:'',kind:'event',start:day,end:day,time:'',location:'',notes:'',availability:''};return back('plan')+heading(e.title?'Edytuj wydarzenie':'Nowe wydarzenie')+`<p class="event-form-intro">Wydarzenie zaznacza czas w kalendarzu. Sesje treningowe planujesz osobno.</p><form id="event-editor">${field('Nazwa','title',e.title,'text','required maxlength="160"')}${select('Rodzaj','kind',[{value:'event',label:'Wydarzenie'},{value:'competition',label:'Zawody / turniej'},{value:'trip',label:'Wyjazd'}],e.kind)}${field('Od','start',e.start,'date','required')}${field('Do','end',e.end,'date','required')}${field('Godzina · opcjonalnie','time',e.time,'time')}${field('Miejsce · opcjonalnie','location',e.location,'text','maxlength="300"')}${select('Dostępność na trening · opcjonalnie','availability',[{value:'',label:'Bez określenia'},{value:'available',label:'Jestem dostępny'},{value:'limited',label:'Ograniczona'},{value:'unavailable',label:'Niedostępny'}],e.availability||'')}${note('notes',e.notes)}<div id="save-error" role="alert"></div><button class="primary wide">Zapisz wydarzenie</button></form>`}
const goalLabels=[['count','Liczba treningów'],['minutes','Czas treningów · min'],['activeDays','Dni aktywności'],['checkinDays','Dni z check-inem'],['sleepAverageHours','Średni sen · godziny']];
function goalEditor(){const g=state.goals.find(g=>g.id===goalId)||{title:'',type:'count',target:'',period:'week'};const type=({sessions:'count',checkins:'checkinDays',sleep:'sleepAverageHours'})[g.type]||g.type;return back('goals')+heading(g.id?'Edytuj cel':'Twój nowy cel')+`<form id="goal-editor">${field('Nazwa · opcjonalnie','title',g.title,'text','maxlength="160"')}${select('Co chcesz śledzić?','goal-type',goalLabels.map(([value,label])=>({value,label})),type)}${field('Twoja wartość docelowa','target',g.target,'number',`required min="${type==='sleepAverageHours'?'.25':'1'}" step="${type==='sleepAverageHours'?'.25':'1'}" ${type==='sleepAverageHours'?'max="24"':''}`)}<p class="field-hint">Wybierz wartość, która pasuje do Ciebie. Cel snu jest Twoim ustawieniem, bez domyślnej normy.</p>${select('Zakres celu','goal-period',[{value:'week',label:'Co tydzień'},{value:'custom',label:'Wybrany okres'}],typeof g.period==='object'?'custom':'week')}<div id="goal-dates" ${typeof g.period==='object'?'':'hidden'}>${field('Początek okresu','start',g.period?.start||demoToday,'date')}${field('Koniec okresu','end',g.period?.end||demoToday,'date')}</div><div id="save-error" role="alert"></div><button class="primary wide">Zapisz cel</button></form>`}
function muscleTargetEditor(){const existing=anatomyProps().targets[selectedMuscleId];return back('plan')+heading('Cel grupy mięśniowej')+`<form id="muscle-target">${select('Grupa mięśniowa','muscleId',muscleGroups.map(g=>({value:g.id,label:g.label})),selectedMuscleId||muscleGroups[0]?.id)}${field('Serie robocze na tydzień','target',existing?.sets??'','number','required min="0" step="0.5"')}<p class="field-hint">Twój cel objętości. 0 oznacza „poza celem tego tygodnia”. Zmiana celu okresu działa od bieżącego tygodnia; wcześniejsze tygodnie ustaw indywidualnie.</p>${select('Obowiązuje','scope',[{value:'week',label:'Tylko wybrany tydzień'},...currentPeriods(day).map(p=>({value:p.id,label:p.name}))],'week')}<div id="save-error" role="alert"></div><button class="primary wide">Zapisz cel mięśnia</button></form>`}
function rolesExercise(){return mappingOriginalPlan?draft?.planned?.exercises[selectedRolesIndex]:draft?.exercises[selectedRolesIndex]}
function exerciseRolesEditor(){const ex=rolesExercise();if(!ex)return back('editor');return back('editor')+heading('Rola mięśni',esc(ex.name))+`<p class="form-aside">Oznacz tylko znane role. Bezpośrednie serie liczymy w całości, pośrednie jako połowę. To przybliżenie objętości.</p><form id="exercise-roles">${muscleGroups.map(g=>select(g.label,'role-'+g.id,[{value:'',label:'Bez przypisania'},{value:'direct',label:'Bezpośrednia'},{value:'indirect',label:'Pośrednia'}],ex.muscleRoles?.direct?.includes(g.id)?'direct':ex.muscleRoles?.indirect?.includes(g.id)?'indirect':'')).join('')}<div id="save-error" role="alert"></div><button class="primary wide">Zapisz role w szkicu</button></form>`}
function plannedExpectations(){return `<details class="planned-expectations"><summary>Przewidywany wysiłek do symulacji planu</summary><p class="form-aside">Oczekiwania zapisane przed sesją. Faktyczne odczucia uzupełnisz po treningu.</p>${select('Podobna wykonana sesja · opcjonalnie','expected-source',[{value:'',label:'Wpiszę własne oczekiwania'},...state.workouts.filter(w=>w.status==='completed'&&w.date<=demoToday&&w.trainingType===draft.trainingType&&w.postSession?.aerobic!=null&&w.postSession?.muscular!=null).slice(-30).reverse().map(w=>({value:w.id,label:w.date+' · '+w.title}))],draft.plannedExertion?.source?.workoutId||'')}${select('Przewidywane zmęczenie oddechowe','expected-aerobic',[{value:'',label:'Brak oszacowania'},...Array.from({length:11},(_,i)=>String(i))],String(draft.plannedExertion?.aerobic??''))}${select('Przewidywane zmęczenie mięśniowe','expected-muscular',[{value:'',label:'Brak oszacowania'},...Array.from({length:11},(_,i)=>String(i))],String(draft.plannedExertion?.muscular??''))}</details>`}
function updateExpected(t){draft.plannedExertion??={aerobic:null,muscular:null,source:{kind:'own-estimate'},algorithm:'planned-exertion-v1'};if(t.name==='expected-source'){const source=state.workouts.find(w=>w.id===t.value);if(source){draft.plannedExertion={aerobic:source.postSession.aerobic,muscular:source.postSession.muscular,source:{kind:'own-session',workoutId:source.id,date:source.date},algorithm:'planned-exertion-v1'};for(const key of ['aerobic','muscular'])document.querySelector('[name=expected-'+key+']').value=String(draft.plannedExertion[key])}else draft.plannedExertion.source={kind:'own-estimate'}}else{draft.plannedExertion[t.name.slice(9)]=t.value===''?null:Number(t.value);draft.plannedExertion.source={kind:'own-estimate'}}persist()}
function lastCheckinContext(){const entry=wellnessEntries().filter(e=>e.date<=demoToday).sort((a,b)=>b.date.localeCompare(a.date)||['Wieczorem','W ciągu dnia','Rano'].indexOf(a.slot)-['Wieczorem','W ciągu dnia','Rano'].indexOf(b.slot))[0];return entry?`<details class="plan-checkin-context"><summary>Ostatni check-in · ${dateLabel(entry.date)} · ${esc(entry.slot)}</summary><dl class="survey-summary">${Object.entries(entry).filter(([key,value])=>key.startsWith('answer-')&&value!==''&&value!=null).map(([key,value])=>`<dt>${esc(key.slice(7))}</dt><dd>${esc(value)}</dd>`).join('')}</dl><p class="form-aside">Zapis z tego dnia. Nie jest przypisywany do przyszłych sesji ani przeliczany na rezerwę.</p>${go('Samopoczucie i trendy','wellnessTrends','subtle')}</details>`:''}
function historyDateOffset(date,offset){const value=new Date(date+'T12:00:00Z');value.setUTCDate(value.getUTCDate()+offset);return value.toISOString().slice(0,10)}
function historyConfirmationPreview(candidate){return candidate.error?`<p class="form-aside">${esc(candidate.error)}</p>`:`<p><strong>${candidate.dates.length} pustych dni</strong> otrzyma potwierdzenie braku treningu.</p><p class="form-aside">Dni z wpisami: ${candidate.blockedDays}. Plany bez wykonania i sesje bez obciążenia nadal wymagają uzupełnienia.</p>`}
function referenceDaysPreview(reference){return '<dl class="reference-days">'+Array.from({length:7},(_,index)=>{const date=historyDateOffset(reference.source.start,index),sessions=reference.sessions.filter(session=>session.date===date),value=sessions.reduce((sum,session)=>sum+session.value,0),occupied=list().some(workout=>workout.date===date&&!['skipped','deleted'].includes(workout.status)&&!workout.deletedAt);return `<div><dt>${dateLabel(date)}</dt><dd>${sessions.length?new Intl.NumberFormat('pl-PL',{maximumFractionDigits:1}).format(value):reference.source.kind==='planned'?'0 · przykład planu':occupied?'Brak wykonania':'0 · pusty dzień'}</dd></div>`}).join('')+'</dl>'}
function historyConfirmationForm(){const end=day>demoToday?demoToday:historyDateOffset(day,-1);historyConfirmationDraft??={start:historyDateOffset(end,-20),end,confirmed:false};const values=historyConfirmationDraft,candidate=historyConfirmationDays({workouts:list(),...values,today:demoToday});return `<section class="history-completeness"><h2>Kompletność historii</h2><p>Puste dni nie muszą oznaczać odpoczynku. Jeśli wszystkie treningi są już zapisane, możesz potwierdzić cały okres naraz.</p><form id="history-completeness">${field('Początek zakresu','start',values.start,'date',`required max="${demoToday}"`)}${field('Koniec zakresu','end',values.end,'date',`required max="${demoToday}"`)}<div id="history-preview" aria-live="polite">${historyConfirmationPreview(candidate)}</div><label class="choice"><input type="checkbox" name="confirmed" required ${values.confirmed?'checked':''}><span>W tym okresie mam zapisane wszystkie treningi.</span></label><button class="primary wide">Potwierdź kompletność okresu</button></form>${state.historyConfirmations.length?`<p class="form-aside">Ostatnio potwierdzony zakres: ${esc(state.historyConfirmations.at(-1).start)} – ${esc(state.historyConfirmations.at(-1).end)}.</p>`:''}</section>`}
function energySettings(){return back('plan')+heading('Rezerwa w planie','Porównanie rozkładu sesji, na początek każdego dnia.')+`<section class="energy-reference-current">${state.reserveReference?`<p>Stały punkt odniesienia: ${esc(state.reserveReference.source?.start)} – ${esc(state.reserveReference.source?.end)}</p><p class="form-aside">Pozostaje niezmienny przy przesuwaniu sesji.</p>`:'<p>Najpierw wskaż kompletnie zapisany, typowy dla Ciebie tydzień.</p>'}</section><div id="save-error" role="alert"></div><form id="energy-reference">${field('Dowolny dzień wybranego tygodnia','anchor',day,'date','required')}${select('Źródło punktu odniesienia','kind',[{value:'completed',label:'Ukończony typowy tydzień'},{value:'planned',label:'Własny przykładowy plan tygodnia'}],'completed')}${button('Sprawdź wybrany tydzień','data-reference-preview','wide')}<div id="reference-preview" aria-live="polite"></div><label class="choice"><input type="checkbox" name="confirmed" required><span id="reference-confirmation-label">Potwierdzam kompletność tygodnia i brak treningów w jego pustych dniach. Wybieram go jako punkt odniesienia.</span></label><button class="primary wide" id="confirm-reference" disabled>Ustaw punkt odniesienia</button></form>${historyConfirmationForm()}<details><summary>Jak czytać tę symulację?</summary><p>Pasek porównuje rozkład obciążeń w planie. Nie jest procentem energii ani pomiarem regeneracji. Warianty 1, 2 i 3 dni to robocze założenia modelu, a nie przedział ufności.</p><p>Liczymy wcześniejsze 21 dni. Braki pozostają widoczne. Dzisiejsza sesja wpływa na kolejne dni, nie na początek dzisiejszego.</p><p>Kreskowany pasek pokazuje tylko znaną część przy niepełnej historii. Przeszły plan bez wykonania i trening fizyczny bez zapisanego obciążenia pozostają brakami.</p></details>${wellnessEntries().filter(e=>e.date<=demoToday).sort((a,b)=>b.date.localeCompare(a.date))[0]?`<p class="form-aside">Ostatni rzeczywisty check-in: ${esc(wellnessEntries().filter(e=>e.date<=demoToday).sort((a,b)=>b.date.localeCompare(a.date))[0].date)}. Samopoczucie pozostaje osobnym kontekstem.</p>`:''}`}
function iterationClick(b){
 if(view==='wellness'&&b.dataset.go==='wellnessDetail'&&wellnessOriginalKey)selectedWellnessKey=wellnessOriginalKey;
 if(b.dataset.edit||b.dataset.weekSession){openSession(b.dataset.edit||b.dataset.weekSession);return true}
 if(b.dataset.sessionEdit){selectedSessionId=b.dataset.sessionEdit;start(state.workouts.find(w=>w.id===selectedSessionId));return true}
 if(b.dataset.sessionComplete){const w=state.workouts.find(w=>w.id===b.dataset.sessionComplete);if(!w||w.date>demoToday)return true;start(w);draft.planned=clone(w);draft.status='completed';draft.duration='';draft.rpe='';delete draft.postSession;delete draft.loadSnapshot;persist();render();return true}
 if(b.dataset.wellnessEntry){selectedWellnessKey=b.dataset.wellnessEntry;wellnessOrigin=view==='journal'?'journal':'wellnessTrends';nav('wellnessDetail');return true}
 if(b.dataset.editWellness){openWellness(b.dataset.editWellness);return true}
 if(b.hasAttribute('data-checkin')){wellnessOrigin=view==='journal'?'journal':'wellnessTrends';openWellness();return true}
 if(b.dataset.wellnessRange){wellnessRange=b.dataset.wellnessRange;render();document.querySelector('[data-wellness-range="'+wellnessRange+'"]')?.focus();return true}
 if(b.dataset.planMode){planMode=b.dataset.planMode;nav('plan');return true}
 if(b.dataset.planSeason){selectedSeasonId=b.dataset.planSeason;planMode='season';nav('plan');return true}
 if(b.dataset.planWeek){day=b.dataset.planWeek;planMode='week';nav('plan');return true}
 if(b.dataset.planDay){day=b.dataset.planDay;planMode='week';nav('plan');return true}
 if(b.dataset.monthShift){const d=new Date(day+'T12:00:00Z');d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+Number(b.dataset.monthShift));day=d.toISOString().slice(0,10);render();return true}
 if(b.hasAttribute('data-event-new')||b.dataset.eventEdit){eventId=b.dataset.eventEdit||crypto.randomUUID();nav('eventEditor');return true}
 if(b.hasAttribute('data-new-goal')||b.dataset.editGoal){goalId=b.dataset.editGoal||crypto.randomUUID();nav('goalEditor');return true}
 if(b.hasAttribute('data-muscle-target')){selectedMuscleId=b.dataset.muscleId||b.dataset.muscleTarget||null;nav('muscleTargetEditor');return true}
 if(b.hasAttribute('data-muscle-mapping')){const w=state.workouts.find(w=>w.id===b.dataset.sessionId);if(w){returnView='plan';draft=clone(w);mappingOriginalPlan=b.dataset.mappingChannel==='planned'&&w.status==='completed';selectedRolesIndex=(mappingOriginalPlan?draft.planned?.exercises||[]:draft.exercises).findIndex(e=>e.id===b.dataset.exerciseId);if(selectedRolesIndex>=0){persist();nav('exerciseRolesEditor')}else if(!mappingOriginalPlan){persist();nav('editor')}else{notice='Brakuje pierwotnej listy ćwiczeń planu. Wykonanie pozostaje oddzielnym zapisem.';render()}}return true}
 if(b.dataset.exerciseRoles!==undefined){mappingOriginalPlan=false;selectedRolesIndex=Number(b.dataset.exerciseRoles);nav('exerciseRolesEditor');return true}
 if(b.hasAttribute('data-reference-preview')){const f=document.querySelector('#energy-reference'),dates=weekDates(f.elements.anchor.value),r=createReserveReference({workouts:list(),start:dates[0],end:dates[6],today:demoToday,kind:f.elements.kind.value});pendingReference=r.error?null:r;document.querySelector('#confirm-reference').disabled=!pendingReference;if(r.error)showError(r.error);else{document.querySelector('#save-error').textContent='';document.querySelector('#reference-preview').innerHTML='<p><strong>'+dateLabel(dates[0])+' – '+dateLabel(dates[6])+'</strong></p><p>Sesje: '+r.sessions.length+' · zapisane obciążenie: '+new Intl.NumberFormat('pl-PL',{maximumFractionDigits:1}).format(r.value)+'</p>'+referenceDaysPreview(r)+(r.uncompletedPlanCount?'<p>Plany bez wykonania: '+r.uncompletedPlanCount+'. Przeszłe plany pozostają nieznane w prognozie. Potwierdź, że żadne wykonanie nie czeka na zapis.</p>':'')}return true}
 if(b.hasAttribute('data-energy-reference')||b.hasAttribute('data-energy-settings')){pendingReference=null;nav('energySettings');return true}
 return false;
}
function iterationSubmit(form,obj){
 if(form.id==='wellness'){if(!Object.entries(obj).some(([k,v])=>k.startsWith('answer-')&&v!=='')){showError('Uzupełnij przynajmniej jedną odpowiedź.');return true}if(obj.date>demoToday){showError('Check-in opisuje dzisiejszy lub wcześniejszy dzień.');return true}const entries=wellnessEntries().filter(e=>e.date+'|'+e.slot!==wellnessOriginalKey&&(e.date!==obj.date||e.slot!==obj.slot));cacheWellnessForm();selectedWellnessKey=obj.date+'|'+obj.slot;savePatch({wellnessEntries:[...entries,obj],wellness:null},'Check-in zapisany.',wellnessOrigin);return true}
 if(form.id==='event-editor'){if(obj.end<obj.start){showError('Koniec wydarzenia nie może być przed początkiem.');return true}savePatch({events:[...state.events.filter(e=>e.id!==eventId),{...obj,id:eventId,availability:obj.availability||null}]},'Wydarzenie zapisane.','plan');return true}
 if(form.id==='goal-editor'){if(obj['goal-period']==='custom'&&(!obj.start||!obj.end||obj.end<obj.start)){showError('Wybierz prawidłowy zakres celu.');return true}const type=obj['goal-type'],target=Number(obj.target);if(!Number.isFinite(target)||target<=0||(type==='sleepAverageHours'&&target>24)||(['count','activeDays','checkinDays'].includes(type)&&!Number.isInteger(target))){showError('Sprawdź wartość docelową.');return true}savePatch({goals:[...state.goals.filter(g=>g.id!==goalId),{id:goalId,title:obj.title,type,target,period:obj['goal-period']==='week'?'week':{start:obj.start,end:obj.end}}]},'Cel zapisany.','goals');return true}
 if(form.id==='exercise-roles'){const roles={direct:[],indirect:[]};for(const [key,value]of Object.entries(obj))if(key.startsWith('role-')&&['direct','indirect'].includes(value))roles[value].push(key.slice(5));rolesExercise().muscleRoles=roles;persist();notice='Role mięśni zapisane w szkicu.';nav('editor');return true}
 if(form.id==='muscle-target'){const dates=weekDates(day),period=state.periods.find(p=>p.id===obj.scope);if(period&&period.end<weekDates(demoToday)[0]){showError('Dla zakończonego okresu ustaw cel tylko na wybrany tydzień.');return true}const target={muscleId:obj.muscleId,target:Number(obj.target),unit:'effective-sets',source:'user',scope:period?'period':'week',periodId:period?.id||null,start:period?(period.start>weekDates(demoToday)[0]?period.start:weekDates(demoToday)[0]):dates[0],end:period?.end||dates[6],updatedAt:new Date().toISOString()};savePatch({muscleTargets:{...state.muscleTargets,[obj.muscleId+'|'+(period?.id||dates[0])+'|'+Date.now()]:target}},'Cel mięśnia zapisany.','plan');return true}
 if(form.id==='energy-reference'){if(!pendingReference||!obj.confirmed){showError('Najpierw sprawdź i potwierdź wybrany tydzień.');return true}savePatch({reserveReference:{...clone(pendingReference),confirmedComplete:true,confirmedRestDays:pendingReference.source.kind==='completed'?[...(pendingReference.emptyDates||[])]:[]}},'Punkt odniesienia zapisany.','plan');return true}
 if(form.id==='history-completeness'){const candidate=historyConfirmationDays({workouts:list(),start:obj.start,end:obj.end,today:demoToday});if(candidate.error||!obj.confirmed){showError(candidate.error||'Potwierdź, że wszystkie treningi z tego okresu są zapisane.');return true}const record={start:obj.start,end:obj.end,emptyDays:[...candidate.dates],confirmedAt:new Date().toISOString()};if(savePatch({confirmedRestDays:[...new Set([...state.confirmedRestDays,...candidate.dates])].sort(),historyConfirmations:[...state.historyConfirmations,record]},'Kompletność okresu potwierdzona. Brakujące dane sesji pozostają widoczne.','energySettings')){historyConfirmationDraft.confirmed=false;render()}return true}
 return false;
}
document.addEventListener('change',event=>{const t=event.target;if(t.closest('#energy-reference')&&['anchor','kind'].includes(t.name)){pendingReference=null;document.querySelector('#reference-preview').textContent='';document.querySelector('#confirm-reference').disabled=true;document.querySelector('#energy-reference [name=confirmed]').checked=false;document.querySelector('#reference-confirmation-label').textContent=document.querySelector('#energy-reference [name=kind]').value==='planned'?'Wybieram ten przykładowy plan jako punkt odniesienia. Nie potwierdza on mojej historii treningów.':'Potwierdzam kompletność tygodnia i brak treningów w jego pustych dniach. Wybieram go jako punkt odniesienia.'}if(t.closest('#history-completeness')){const form=t.closest('form');if(t.name!=='confirmed')form.elements.confirmed.checked=false;historyConfirmationDraft={start:form.elements.start.value,end:form.elements.end.value,confirmed:form.elements.confirmed.checked};document.querySelector('#history-preview').innerHTML=historyConfirmationPreview(historyConfirmationDays({workouts:list(),...historyConfirmationDraft,today:demoToday}))}if(t.name==='plan-search'||t.name==='plan-trainingtype'){planFilters[t.name==='plan-search'?'search':'trainingType']=t.value;render();document.querySelector('.plan-filters').open=true;document.querySelector('[name="'+t.name+'"]')?.focus()}if(t.name==='wellness-trend-slot'){wellnessSlot=t.value;wellnessMetric=t.value==='Rano'?'Sen (godziny)':t.value==='Wieczorem'?'Zmęczenie':'Energia';render()}if(t.name==='wellness-trend-metric'){wellnessMetric=t.value;render()}if(t.name==='goal-type'){const input=document.querySelector('[name=target]'),sleep=t.value==='sleepAverageHours';input.step=sleep?'.25':'1';input.min=sleep?'.25':'1';sleep?input.max='24':input.removeAttribute('max')}if(t.name==='goal-period')document.querySelector('#goal-dates').hidden=t.value!=='custom'});
helpTexts['energy-calendar'][2]=[{label:'Badanie obciążenia i samopoczucia u rugbystów',url:'https://pubmed.ncbi.nlm.nih.gov/39758184/'},{label:'Konsensus: indywidualność regeneracji',url:'https://pubmed.ncbi.nlm.nih.gov/29345524/'}];
bindHelp();
document.addEventListener('click',event=>{
 const b=event.target.closest('button');if(!b)return;
 if(b.hasAttribute('data-help')||b.hasAttribute('data-close-help'))return;
 notice='';if(iterationClick(b))return;
 if(draft){const action=handleExerciseClick(b,draft);if(action?.handled){if(action.changed)persist();render();if(action.focusSelector)document.querySelector(action.focusSelector)?.focus();return}}
 if(b.hasAttribute('data-skip-feeling')){const range=b.closest('.feeling').querySelector('.feeling-range');range.value=Math.round((Number(range.min)+Number(range.max))/2);syncPost(range,true);return}
 notice='';
 if(b.hasAttribute('data-checkin')){returnView=view==='journal'?'journal':'more';day=demoToday;nav('wellness')}
 else if(b.dataset.go){if(b.dataset.go==='library')picking=false;if(b.dataset.go==='wellness'){nav('wellnessTrends');return}nav(b.dataset.go)}
 else if(b.hasAttribute('data-today-week')){todayExpanded=!todayExpanded;render()}
 else if(b.hasAttribute('data-new')){day=demoToday;start()}
 else if(b.hasAttribute('data-plan'))start(null,true);
 else if(b.dataset.edit||b.dataset.weekSession)start(state.workouts.find(w=>w.id===(b.dataset.edit||b.dataset.weekSession)));
 else if(b.dataset.weekDate){day=b.dataset.weekDate;planMode='week';if(view==='journal')nav('plan');else render();document.querySelector('[data-week-date="'+day+'"]')?.focus()}
 else if(b.dataset.weekShift){const date=new Date(day+'T12:00:00');date.setDate(date.getDate()+Number(b.dataset.weekShift)*7);day=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;render();document.querySelector('[data-week-shift="'+b.dataset.weekShift+'"]')?.focus()}
 else if(b.dataset.history){historyTab=b.dataset.history;historyMonth='';historyLimit=20;render()}
 else if(b.dataset.progressRange){progressRange=b.dataset.progressRange;render();document.querySelector('[data-progress-range="'+progressRange+'"]')?.focus()}
 else if(b.hasAttribute('data-more-history')){historyLimit+=20;render();document.querySelector('[data-more-history]')?.focus({preventScroll:true})}
 else if(b.hasAttribute('data-more-wellness')){wellnessLimit+=20;render();document.querySelector('[data-more-wellness]')?.focus({preventScroll:true})}
 else if(b.dataset.period){periodId=b.dataset.period;nav('period')}
 else if(b.hasAttribute('data-period-new')){periodId=crypto.randomUUID();nav('period')}
 else if(b.hasAttribute('data-picker')){picking=true;nav('library')}
 else if(b.dataset.exercise!==undefined){selectedExercise=Number(b.dataset.exercise);nav('detail')}
 else if(b.hasAttribute('data-add-exercise')||b.hasAttribute('data-create-exercise')){if(!draft)start();draft.exercises.push(prepareExercise(catalog[selectedExercise]));persist();nav('editor')}
 else if(b.hasAttribute('data-complete')){if(draft.date>demoToday)return;draft.planned=clone(draft);draft.status='completed';draft.duration='';draft.rpe='';persist();render()}
 else if(b.hasAttribute('data-convert-plan')){draft.status='planned';persist();render()}
 else if(b.hasAttribute('data-copy')){draft.id=crypto.randomUUID();draft.title+=' (kopia)';draft.date=day;draft.status='planned';delete draft.postSession;delete draft.planned;delete draft.loadSnapshot;persist();notice='Nowy szkic. Oryginał pozostaje bez zmian.';render()}
 else if(b.hasAttribute('data-skip-review'))saveDraft();
 else if(b.dataset.template){if(!draft)start(null,true);const ids=b.dataset.template==='whole'?[4,0,1,4]:[4];draft.exercises.push(...ids.map((i,j)=>({...prepareExercise(catalog[i]),section:j===0?'warmup':j===ids.length-1&&ids.length>1?'cooldown':'main'})));if(!draft.title)draft.title=b.dataset.template==='whole'?'Siła całego ciała':'Mobilna rozgrzewka';persist();nav('editor')}
});
document.addEventListener('input',event=>{
 const t=event.target;
 if(t.closest('#wellness')&&!['slot','date'].includes(t.name))cacheWellnessForm();
 if(t.matches('.feeling-range')){syncPost(t);return}
 if(t.closest('#workout')&&draft&&t.name?.startsWith('expected-')){updateExpected(t);return}
 if(t.closest('#workout')&&draft){if(handleExerciseInput(t,draft)){persist();return}if(t.name){draft[t.name]=t.value;persist();if(t.name==='date')updateFutureState();if(t.name==='trainingType')document.querySelector('#chosen-type').innerHTML=typeBadge(draft)}}
 if(t.name==='post-notes'&&draft){draft.postSession.notes=t.value;persist();refreshLoadPreview()}
 if(t.name==='search'){query=t.value;document.querySelector('#exercise-list').innerHTML=exerciseList()}
});
document.addEventListener('pointerup',e=>{if(e.target.matches('.feeling-range'))syncPost(e.target)});
document.addEventListener('keyup',e=>{if(e.target.matches('.feeling-range')&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(e.key))syncPost(e.target)});
document.addEventListener('change',event=>{const t=event.target;if(t.name==='history-month'){historyMonth=t.value;historyLimit=20;render();document.querySelector('[name=history-month]')?.focus()}if(t.name==='wellness-month'){wellnessMonth=t.value;wellnessLimit=20;render();document.querySelector('[name=wellness-month]')?.focus()}if(t.name==='plan-date'&&t.value){day=t.value;render();if(document.querySelector('.plan-filters'))document.querySelector('.plan-filters').open=true;document.querySelector('[name=plan-date]')?.focus()}if(t.id==='scenario'){scenario=t.value;error='';render()}if(t.id==='large')document.documentElement.classList.toggle('large',t.checked);if(t.name==='filter'){filter=t.value;document.querySelector('#exercise-list').innerHTML=exerciseList()}if(t.closest('#wellness')&&['slot','date'].includes(t.name)){cacheWellnessForm();wellnessFields()}});
document.addEventListener('submit',event=>{
 event.preventDefault();const form=event.target,d=new FormData(form),obj=Object.fromEntries(d);
 if(iterationSubmit(form,obj))return;
 if(form.id==='workout'){if(draft.status==='completed'){if(draft.date>demoToday)return;persist();nav('postSession')}else saveDraft()}
 else if(form.id==='post-session')saveDraft();
 else if(form.id==='profile'){const result=readProfile(form,state.profile);if(result.error){showError(result.error);return}state.profile=result.profile;persist();notice='Zapisano sporty.';nav(draft?'editor':'more')}
 else if(form.id==='modules'){state.profile=readModules(form,state.profile);persist();notice='Zapisano skróty. Dane pozostają dostępne.';nav('more')}
 else if(form.id==='period'){if(obj.end<obj.start){form.elements.end.setCustomValidity('Koniec nie może być przed początkiem.');form.elements.end.reportValidity();form.elements.end.oninput=()=>form.elements.end.setCustomValidity('');return}let ancestor=obj.parentId;const visited=new Set([periodId]);while(ancestor){if(visited.has(ancestor)){showError('Okres nie może być swoim przodkiem. Zmień okres nadrzędny.');return}visited.add(ancestor);ancestor=state.periods.find(p=>p.id===ancestor)?.parentId}state.periods=[...state.periods.filter(p=>p.id!==periodId),{...obj,id:periodId,parentId:obj.parentId||null}];persist();notice='Zapisano okres.';nav('periods')}
 else if(form.id==='goal'){state.goal=obj.goal;persist();nav('journal')}
 else if(form.id==='wellness'){if(!Object.entries(obj).some(([k,v])=>k.startsWith('answer-')&&v!=='')){showError('Uzupełnij przynajmniej jedną odpowiedź.');return}state.wellnessEntries=[...wellnessEntries().filter(x=>x.date!==obj.date||x.slot!==obj.slot),obj];state.wellness=obj;persist();notice='Zapisano check-in.';nav(returnView)}
 else if(form.id==='exercise-note'){state.exerciseNotes={...state.exerciseNotes,[catalog[selectedExercise].name]:obj.exerciseNote};persist();notice='Zapisano notatkę.';render()}
 else if(form.id==='custom'){const entry={...obj,id:crypto.randomUUID(),muscles:obj.muscles.split(',').map(x=>x.trim()).filter(Boolean)};catalog.push(entry);state.customExercises.push(entry);persist();notice='Dodano własne ćwiczenie.';nav('library')}
 else if(form.id==='export'){const csv=obj.format==='csv',safe=x=>'"'+String(x??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const content=csv?'\ufeff'+[['Data','Trening','Rodzaj','Dyscyplina','Status','Minuty','RPE','Zmęczenie oddechowe','Zmęczenie mięśniowe','Satysfakcja','Trainleaf load','Wersja load'],...state.workouts.map(w=>[w.date,w.title,typeOf(w).label,w.sport,w.status,w.duration,w.rpe,w.postSession?.aerobic,w.postSession?.muscular,w.postSession?.satisfaction,w.loadSnapshot?.value,w.loadSnapshot?.algorithm])].map(r=>r.map(safe).join(';')).join('\r\n'):JSON.stringify({format:'ui-prototype-only',...state,draft},null,2),url=URL.createObjectURL(new Blob([content],{type:csv?'text/csv;charset=utf-8':'application/json'})),a=document.createElement('a');a.href=url;a.download='Trainleaf-prototyp-dane.'+(csv?'csv':'json');a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice='Przekazano plik do pobrania.';render()}
});
render();
