import {chromium,expect} from '@playwright/test';
import {fileURLToPath} from 'node:url';
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:360,height:800}});
const checks=[];
try{
 await page.goto('http://127.0.0.1:4186/');
 await expect(page.getByRole('heading',{name:'Dzisiaj',exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Zrób check-in'})).toBeVisible();
 await expect(page.getByRole('button',{name:/Siła całego ciała/})).toHaveCount(0);
 await page.screenshot({path:fileURLToPath(new URL('qa/today-360.png',import.meta.url)),fullPage:true});
 checks.push('Today title; pending check-in; history hidden');
 await page.getByRole('button',{name:'Zrób check-in'}).click();
 await page.getByRole('slider',{name:'Zmęczenie · 0–10',exact:true}).press('Home');
 await page.getByRole('button',{name:'Zapisz check-in'}).click();
 await expect(page.locator('.checkin-done')).toBeVisible();
 await expect(page.getByRole('button',{name:'Zrób check-in'})).toHaveCount(0);
 await page.reload();await expect(page.locator('.checkin-done')).toBeVisible();
 checks.push('Completed check-in collapses and persists after reload; zero accepted');
 await page.locator('.checkin-done').click();
 await expect(page.getByLabel('Zmęczenie · 0–10',{exact:true})).toHaveValue('0');
 await page.getByRole('button',{name:'Dzisiaj',exact:true}).click();
 await page.getByRole('button',{name:/Historia treningów/}).click();
 await expect(page.getByRole('button',{name:/Siła całego ciała/})).toBeVisible();
 checks.push('History remains accessible');
 await page.evaluate(()=>{const key='fieldwork-ui-demo-v1',s=JSON.parse(localStorage.getItem(key));s.wellness.date='2026-10-02';s.wellnessEntries=[];s.period.start='2026-11-01';s.period.end='2026-11-30';s.workouts.push({...s.workouts[0],id:'done-today',title:'Dzisiejszy wykonany',date:'2026-10-03'});localStorage.setItem(key,JSON.stringify(s))});
 await page.reload();await expect(page.getByRole('button',{name:'Zrób check-in'})).toBeVisible();
 await expect(page.getByText('Brak aktywnego okresu')).toBeVisible();
 await expect(page.getByRole('button',{name:/Dzisiejszy wykonany/})).toBeVisible();
 await expect(page.getByRole('button',{name:/Rzuty i praca nóg/})).toBeVisible();
 checks.push('Yesterday check-in does not hide prompt; inactive period excluded; planned and completed sessions shown');
 await page.getByRole('button',{name:'Plan',exact:true}).click();
 await page.getByRole('button',{name:'2026-09-30',exact:true}).click();
 await page.getByRole('button',{name:'Dzisiaj',exact:true}).click();
 await page.getByRole('button',{name:'Zrób check-in'}).click();
 await expect(page.getByLabel('Data',{exact:true})).toHaveValue('2026-10-03');
 checks.push('Check-in date independent of calendar selection');
 await page.getByRole('button',{name:'Dzisiaj',exact:true}).click();
 await page.locator('.review-tools').evaluate(el=>el.open=true);await page.locator('#large').check();await page.locator('.review-tools').evaluate(el=>el.open=false);
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Overflow at 200%');
 checks.push('360 px at 200% without horizontal overflow');
 await writeFile(new URL('qa/today-results.json',import.meta.url),JSON.stringify({checks},null,2));
 console.log(checks.join('\n'));
}finally{await browser.close()}
