import {esc,icon,typeOf,typeBadge,helpButton} from './ui-core.js';
import {loadDisplay} from './load-model.js';

const shown=value=>value===null||value===undefined||value===''?'—':esc(value);
const dateLabel=date=>new Intl.DateTimeFormat('pl-PL',{weekday:'long',day:'numeric',month:'long'}).format(new Date(date+'T12:00:00'));

export function renderSessionDetail({workout:w,periods=[],today,backView='plan'}){
  if(!w)return '<h1>Sesja niedostępna</h1><button data-go="plan">Wróć do planu</button>';
  const type=typeOf(w),planned=w.status==='planned',matches=periods.filter(p=>p.start<=w.date&&p.end>=w.date),groups=w.groups||[];
  return `<div class="context-crumb"><button data-go="${esc(backView)}">${backView==='plan'?'← Plan':backView==='history'?'← Historia':backView==='progress'?'← Postępy':'← Dzisiaj'}</button><span>Sesja</span></div>
  <article class="session-detail"><header class="session-detail-hero" style="--session-paper:${type.background};--session-ink:${type.color}">${typeBadge(w)}<p>${esc(dateLabel(w.date))}${w.time?' · '+esc(w.time):''}</p><h1>${esc(w.title||'Trening')}</h1><span class="session-status">${planned?(w.date<today?'Plan bez wykonania':'Zaplanowany'):'Ukończony'}</span><small>${esc(w.sport)}</small></header>
  <div class="session-detail-actions"><button class="primary" data-session-edit="${esc(w.id)}">${icon('edit')} Edytuj ${planned?'plan':'sesję'}</button>${planned?`<button data-session-complete="${esc(w.id)}" ${w.date>today?'disabled':''}>Zapisz wykonanie</button>`:''}</div>
  ${planned&&w.date>today?'<p class="form-aside">Wykonanie zapiszesz najwcześniej w dniu sesji.</p>':''}
  <dl class="session-facts"><div><dt>${planned?'Planowany czas':'Wykonany czas'}</dt><dd>${shown(w.duration)} <small>min</small></dd></div>${!planned?`<div><dt>Wysiłek · RPE ${helpButton('rpe')}</dt><dd>${shown(w.rpe)} <small>/ 10</small></dd></div>`:''}</dl>
  ${w.notes?`<section class="session-notebook"><span class="eyebrow">Twoja notatka</span><p>${esc(w.notes)}</p></section>`:''}
  <section class="session-exercises"><h2>Przebieg sesji</h2>${['warmup','main','cooldown'].map(section=>{const exercises=(w.exercises||[]).filter(e=>(e.section||'main')===section);return exercises.length?`<div class="session-exercise-section"><h3>${{warmup:'Rozgrzewka',main:'Część główna',cooldown:'Wyciszenie'}[section]}</h3><ol>${exercises.map(e=>{const group=groups.find(g=>g.id===e.groupId);return `<li><div><strong>${esc(e.name)}</strong>${group?`<span class="tag">Superseria · ${shown(group.rounds)} rund</span>`:''}<p>${e.sets!==''&&e.sets!=null?`${esc(e.sets)} × `:''}${shown(e.quantity)} ${esc(e.unit||'')}${e.kg!==''&&e.kg!=null?' · '+esc(e.kg)+' kg':''}${e.rir!==''&&e.rir!=null?' · RIR '+esc(e.rir):''}</p>${e.tempo||e.pace||e.rest?`<small>${[e.tempo?'Tempo '+e.tempo:'',e.pace?'Tempo '+e.pace:'',e.rest?'Przerwa '+e.rest:''].filter(Boolean).map(esc).join(' · ')}</small>`:''}${e.notes?`<p>${esc(e.notes)}</p>`:''}</div></li>`}).join('')}</ol></div>`:''}).join('')||'<p class="muted">Sesja została zapisana bez listy ćwiczeń.</p>'}</section>
  ${!planned?`<section class="session-after"><h2>Po treningu</h2><dl class="survey-summary">${[['aerobic','Zmęczenie oddechowe'],['muscular','Zmęczenie mięśniowe'],['satisfaction','Satysfakcja']].map(([key,label])=>`<dt>${label}</dt><dd>${shown(w.postSession?.[key])}${w.postSession?.[key]!==null&&w.postSession?.[key]!==undefined&&w.postSession?.[key]!==''?' / 10':''}</dd>`).join('')}</dl>${w.postSession?.notes?`<p>${esc(w.postSession.notes)}</p>`:''}<details class="session-load"><summary>Obciążenie tej sesji</summary><div class="label-help"><strong>Trainleaf load: ${loadDisplay(w.loadSnapshot)}</strong>${helpButton('trainleaf-load')}</div><small>${esc(w.loadSnapshot?.algorithm||'Brak zapisanego wyniku')}</small></details></section>`:''}
  ${matches.length?`<section class="session-period-context"><h2>W szerszym planie</h2>${matches.map(p=>`<span>${esc(p.name)}</span>`).join('')}</section>`:''}</article>`;
}
